// a lower bound that rules out an upper bound
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    int outer = 0;
    int inner = 0;
    for (int i = 0; i < 256; i++) {
        int x = data[i];
        if (x > 100) {
            outer++;
            if (x <= 50) {
                inner++;
            }
        }
    }

    printf("%lld\n", (long long)(outer));
    printf("%lld\n", (long long)(inner));
    return 0;
}
