// a switch whose value a range check before it has bounded
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    int outer = 0;
    int inner = 0;
    for (int i = 0; i < 256; i++) {
        int x = data[i];
        int n = x & 15;
        if (n < 4) {
            outer++;
            switch (n) {
                case 0: case 1: case 2: case 3: inner++; break;
                case 9: inner += 100; break;
                default: break;
            }
        }
    }

    printf("%lld\n", (long long)(outer));
    printf("%lld\n", (long long)(inner));
    return 0;
}
