// 24 live int values held call-off-the-path, which is what the pressure model counts
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int opaque(int v) {
    return v + 1;
}
static volatile int seed_in = 1;
static volatile int flag_in = 1;

int main(void) {
    int seed = seed_in;
    int flag = flag_in;

    int v0 = seed + (int)0;
    int v1 = seed + (int)1;
    int v2 = seed + (int)2;
    int v3 = seed + (int)3;
    int v4 = seed + (int)4;
    int v5 = seed + (int)5;
    int v6 = seed + (int)6;
    int v7 = seed + (int)7;
    int v8 = seed + (int)8;
    int v9 = seed + (int)9;
    int v10 = seed + (int)10;
    int v11 = seed + (int)11;
    int v12 = seed + (int)12;
    int v13 = seed + (int)13;
    int v14 = seed + (int)14;
    int v15 = seed + (int)15;
    int v16 = seed + (int)16;
    int v17 = seed + (int)17;
    int v18 = seed + (int)18;
    int v19 = seed + (int)19;
    int v20 = seed + (int)20;
    int v21 = seed + (int)21;
    int v22 = seed + (int)22;
    int v23 = seed + (int)23;

    int kept = 0;
    if (flag == 0) {
        kept = opaque(seed);
    } else {
        kept += v23;
        kept += v22;
        kept += v21;
        kept += v20;
        kept += v19;
        kept += v18;
        kept += v17;
        kept += v16;
        kept += v15;
        kept += v14;
        kept += v13;
        kept += v12;
        kept += v11;
        kept += v10;
        kept += v9;
        kept += v8;
        kept += v7;
        kept += v6;
        kept += v5;
        kept += v4;
        kept += v3;
        kept += v2;
        kept += v1;
        kept += v0;
    }

    int total = kept;

    printf("%lld\n", (long long)(total));
    return 0;
}
