// 6 live int values held call-off-the-path, which is what the pressure model counts
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int opaque(int v) {
    return v + 1;
}
static volatile int seed_in = 1;
static volatile int flag_in = 1;

int main(void) {
    int seed = seed_in;
    int flag = flag_in;

    int v0 = seed + (int)0;
    int v1 = seed + (int)1;
    int v2 = seed + (int)2;
    int v3 = seed + (int)3;
    int v4 = seed + (int)4;
    int v5 = seed + (int)5;

    int kept = 0;
    if (flag == 0) {
        kept = opaque(seed);
    } else {
        kept += v5;
        kept += v4;
        kept += v3;
        kept += v2;
        kept += v1;
        kept += v0;
    }

    int total = kept;

    printf("%lld\n", (long long)(total));
    return 0;
}
