// 12 live long long values held call-off-the-path, which is what the pressure model counts
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long opaque(long long v) {
    return v + 1;
}
static volatile long long seed_in = 1ll;
static volatile int flag_in = 1;

int main(void) {
    long long seed = seed_in;
    int flag = flag_in;

    long long v0 = seed + (long long)0ll;
    long long v1 = seed + (long long)1ll;
    long long v2 = seed + (long long)2ll;
    long long v3 = seed + (long long)3ll;
    long long v4 = seed + (long long)4ll;
    long long v5 = seed + (long long)5ll;
    long long v6 = seed + (long long)6ll;
    long long v7 = seed + (long long)7ll;
    long long v8 = seed + (long long)8ll;
    long long v9 = seed + (long long)9ll;
    long long v10 = seed + (long long)10ll;
    long long v11 = seed + (long long)11ll;

    long long kept = 0;
    if (flag == 0) {
        kept = opaque(seed);
    } else {
        kept += v11;
        kept += v10;
        kept += v9;
        kept += v8;
        kept += v7;
        kept += v6;
        kept += v5;
        kept += v4;
        kept += v3;
        kept += v2;
        kept += v1;
        kept += v0;
    }

    long long total = kept;

    printf("%lld\n", (long long)(total));
    return 0;
}
