// 6 live long long values held call-off-the-path, which is what the pressure model counts
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long opaque(long long v) {
    return v + 1;
}
static volatile long long seed_in = 1ll;
static volatile int flag_in = 1;

int main(void) {
    long long seed = seed_in;
    int flag = flag_in;

    long long v0 = seed + (long long)0ll;
    long long v1 = seed + (long long)1ll;
    long long v2 = seed + (long long)2ll;
    long long v3 = seed + (long long)3ll;
    long long v4 = seed + (long long)4ll;
    long long v5 = seed + (long long)5ll;

    long long kept = 0;
    if (flag == 0) {
        kept = opaque(seed);
    } else {
        kept += v5;
        kept += v4;
        kept += v3;
        kept += v2;
        kept += v1;
        kept += v0;
    }

    long long total = kept;

    printf("%lld\n", (long long)(total));
    return 0;
}
