// 6 live unsigned long long values held both-classes, which is what the pressure model counts
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 1ull;
static volatile int flag_in = 1;

int main(void) {
    unsigned long long seed = seed_in;
    int flag = flag_in;

    unsigned long long v0 = seed + (unsigned long long)0ull;
    unsigned long long v1 = seed + (unsigned long long)1ull;
    unsigned long long v2 = seed + (unsigned long long)2ull;
    unsigned long long v3 = seed + (unsigned long long)3ull;
    unsigned long long v4 = seed + (unsigned long long)4ull;
    unsigned long long v5 = seed + (unsigned long long)5ull;

    double d0 = 1.0, d1 = 2.0, d2 = 3.0, d3 = 4.0;
    double dsum = d0 + d1 + d2 + d3;
    unsigned long long kept = (unsigned long long)dsum;

    unsigned long long total = kept;
    total += v5;
    total += v4;
    total += v3;
    total += v2;
    total += v1;
    total += v0;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
