// 24 live unsigned int values held call-off-the-path, which is what the pressure model counts
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int opaque(unsigned int v) {
    return v + 1;
}
static volatile unsigned int seed_in = 1u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int seed = seed_in;
    int flag = flag_in;

    unsigned int v0 = seed + (unsigned int)0u;
    unsigned int v1 = seed + (unsigned int)1u;
    unsigned int v2 = seed + (unsigned int)2u;
    unsigned int v3 = seed + (unsigned int)3u;
    unsigned int v4 = seed + (unsigned int)4u;
    unsigned int v5 = seed + (unsigned int)5u;
    unsigned int v6 = seed + (unsigned int)6u;
    unsigned int v7 = seed + (unsigned int)7u;
    unsigned int v8 = seed + (unsigned int)8u;
    unsigned int v9 = seed + (unsigned int)9u;
    unsigned int v10 = seed + (unsigned int)10u;
    unsigned int v11 = seed + (unsigned int)11u;
    unsigned int v12 = seed + (unsigned int)12u;
    unsigned int v13 = seed + (unsigned int)13u;
    unsigned int v14 = seed + (unsigned int)14u;
    unsigned int v15 = seed + (unsigned int)15u;
    unsigned int v16 = seed + (unsigned int)16u;
    unsigned int v17 = seed + (unsigned int)17u;
    unsigned int v18 = seed + (unsigned int)18u;
    unsigned int v19 = seed + (unsigned int)19u;
    unsigned int v20 = seed + (unsigned int)20u;
    unsigned int v21 = seed + (unsigned int)21u;
    unsigned int v22 = seed + (unsigned int)22u;
    unsigned int v23 = seed + (unsigned int)23u;

    unsigned int kept = 0;
    if (flag == 0) {
        kept = opaque(seed);
    } else {
        kept += v23;
        kept += v22;
        kept += v21;
        kept += v20;
        kept += v19;
        kept += v18;
        kept += v17;
        kept += v16;
        kept += v15;
        kept += v14;
        kept += v13;
        kept += v12;
        kept += v11;
        kept += v10;
        kept += v9;
        kept += v8;
        kept += v7;
        kept += v6;
        kept += v5;
        kept += v4;
        kept += v3;
        kept += v2;
        kept += v1;
        kept += v0;
    }

    unsigned int total = kept;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
