// macro-args after arch/x86/include/asm/asm.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

__asm__(".macro rk_mix dst, src\n"
        "\taddl \\src, \\dst\n"
        "\troll $5, \\dst\n"
        ".endm\n");

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    __asm__("rk_mix %0, %1" : "+r"(x) : "r"(i) : "cc");
    return x;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
