// the max pattern on unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 20ull;
static volatile unsigned long long b_in = 12ull;
static volatile unsigned long long c_in = 100ull;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;
    unsigned long long c = c_in;

    printf("%llu\n", (unsigned long long)(a > b ? a : b));
    return 0;
}
