// a 7 iteration long long loop written as a do-while
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long total = 0;
    int i = 0;
    if (0 < 7) {
        do {
            total += (long long)(i + 1);
            i++;
        } while (i < 7);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
