// a 16 iteration unsigned long long loop written as a goto
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned long long total = 0;
    int i = 0;
    top:
    if (i < 16) {
        total += (unsigned long long)(i + 1);
        i++;
        goto top;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
