// a 2 iteration int loop written as a do-while
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int total = 0;
    int i = 0;
    if (0 < 2) {
        do {
            total += (int)(i + 1);
            i++;
        } while (i < 2);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
