// a 2 iteration unsigned int loop written as a while
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned int total = 0;
    int i = 0;
    while (i < 2) {
        total += (unsigned int)(i + 1);
        i++;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
