// a 2 iteration long long loop written as a while
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long total = 0;
    int i = 0;
    while (i < 2) {
        total += (long long)(i + 1);
        i++;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
