// a 1 iteration unsigned long long loop written as a for
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned long long total = 0;
    int i = 0;
    for (i = 0; i < 1; i++) {
        total += (unsigned long long)(i + 1);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
