// a 16 iteration unsigned int loop written as a do-while
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned int total = 0;
    int i = 0;
    if (0 < 16) {
        do {
            total += (unsigned int)(i + 1);
            i++;
        } while (i < 16);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
