// a unsigned int load a store already answered, through-pointer
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int value_in = 41u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int value = value_in;
    int flag = flag_in;

    unsigned int slots[4];
    unsigned int *at = &slots[0];
    *at = value;
    unsigned int read = *at;

    printf("%llu\n", (unsigned long long)(read));
    return 0;
}
