// a int load and a walk that has to across-opaque-call
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int value_in = 41;
static volatile int flag_in = 1;
static int *slot;
static void bump(void) {
    *slot += 1;
}

int main(void) {
    int value = value_in;
    int flag = flag_in;

    int slots[4];
    slots[0] = value;
    slot = &slots[0];
    bump();
    int read = slots[0];

    printf("%lld\n", (long long)(read - (int)1));
    return 0;
}
