// a unsigned long long load and a walk that has to across-opaque-call
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long value_in = 41ull;
static volatile int flag_in = 1;
static unsigned long long *slot;
static void bump(void) {
    *slot += 1;
}

int main(void) {
    unsigned long long value = value_in;
    int flag = flag_in;

    unsigned long long slots[4];
    slots[0] = value;
    slot = &slots[0];
    bump();
    unsigned long long read = slots[0];

    printf("%llu\n", (unsigned long long)(read - (unsigned long long)1ull));
    return 0;
}
