// a long long load and a walk that has to volatile-store
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long value_in = 41ll;
static volatile int flag_in = 1;

int main(void) {
    long long value = value_in;
    int flag = flag_in;

    volatile long long slot;
    slot = value;
    long long read = slot;

    printf("%lld\n", (long long)(read));
    return 0;
}
