// a unsigned long long load a store already answered, through-pointer
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long value_in = 41ull;
static volatile int flag_in = 1;

int main(void) {
    unsigned long long value = value_in;
    int flag = flag_in;

    unsigned long long slots[4];
    unsigned long long *at = &slots[0];
    *at = value;
    unsigned long long read = *at;

    printf("%llu\n", (unsigned long long)(read));
    return 0;
}
