// a unsigned int load and a walk that has to long-chain
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int value_in = 41u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int value = value_in;
    int flag = flag_in;

    unsigned int slots[40];
    slots[0] = value;
    slots[1] = value + (unsigned int)1u;
    slots[2] = value + (unsigned int)2u;
    slots[3] = value + (unsigned int)3u;
    slots[4] = value + (unsigned int)4u;
    slots[5] = value + (unsigned int)5u;
    slots[6] = value + (unsigned int)6u;
    slots[7] = value + (unsigned int)7u;
    slots[8] = value + (unsigned int)8u;
    slots[9] = value + (unsigned int)9u;
    slots[10] = value + (unsigned int)10u;
    slots[11] = value + (unsigned int)11u;
    slots[12] = value + (unsigned int)12u;
    slots[13] = value + (unsigned int)13u;
    slots[14] = value + (unsigned int)14u;
    slots[15] = value + (unsigned int)15u;
    slots[16] = value + (unsigned int)16u;
    slots[17] = value + (unsigned int)17u;
    slots[18] = value + (unsigned int)18u;
    slots[19] = value + (unsigned int)19u;
    slots[20] = value + (unsigned int)20u;
    slots[21] = value + (unsigned int)21u;
    slots[22] = value + (unsigned int)22u;
    slots[23] = value + (unsigned int)23u;
    slots[24] = value + (unsigned int)24u;
    slots[25] = value + (unsigned int)25u;
    slots[26] = value + (unsigned int)26u;
    slots[27] = value + (unsigned int)27u;
    slots[28] = value + (unsigned int)28u;
    slots[29] = value + (unsigned int)29u;
    slots[30] = value + (unsigned int)30u;
    slots[31] = value + (unsigned int)31u;
    slots[32] = value + (unsigned int)32u;
    unsigned int read = slots[0];

    printf("%llu\n", (unsigned long long)(read));
    return 0;
}
