// Exports functions and data for the executable to find.
// Generated by rucc-corpus. Edit the generator, not this file.

#ifdef _WIN32
#define PGDLLIMPORT __declspec(dllimport)
#define PGDLLEXPORT __declspec(dllexport)
#else
#define PGDLLIMPORT
#define PGDLLEXPORT
#endif

extern PGDLLIMPORT long long exe_total;

static const int magic[4] = { 180000, 100, 32, 8 };

PGDLLEXPORT long long mod_total = 1000;

static long long helper(long long x)
{
    return x * 3 + exe_total;
}

long long mod_plain(long long x)
{
    return helper(x) + 1;
}

PGDLLEXPORT const int *Pg_magic_func(void)
{
    return magic;
}

PGDLLEXPORT long long mod_step(long long x)
{
    mod_total += helper(x);
    exe_total += 1;
    return mod_total;
}
