// Reads and writes data the executable exports, through imports.
// Generated by rucc-corpus. Edit the generator, not this file.

#ifdef _WIN32
#define PGDLLIMPORT __declspec(dllimport)
#define PGDLLEXPORT __declspec(dllexport)
#else
#define PGDLLIMPORT
#define PGDLLEXPORT
#endif

struct config {
    int a;
    long long b;
    unsigned char c;
    short d;
    double e;
};

extern PGDLLIMPORT int NBuffers;
extern PGDLLIMPORT long long counter;
extern PGDLLIMPORT struct config Config;
extern PGDLLIMPORT int table[4];
extern PGDLLIMPORT const char *const names[3];

PGDLLEXPORT long long mod_run(int rounds)
{
    long long acc = 0;
    for (int r = 0; r < rounds; r++) {
        acc += (long long)NBuffers * (r + 2);
        for (int i = 0; i < 4; i++) {
            acc += table[i];
            table[i] = table[i] * 2 - r;
        }
        acc += Config.a + Config.b + Config.c + Config.d + (long long)(Config.e * 4);
        Config.b += 2 * r + 1;
        Config.c = (unsigned char)(Config.c + 11);
        for (int k = 0; k < 3; k++) {
            acc += (unsigned char)names[k][r + 1];
        }
        counter += acc % 997;
    }
    NBuffers += 2;
    return acc;
}
