// one long long load, narrower-load
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 5ll;
static volatile int at_in = 3;

int main(void) {
    long long seed = seed_in;
    int at = at_in;

    unsigned char bytes[8];
    for (int i = 0; i < 8; i++) {
        bytes[i] = (unsigned char)(seed + i);
    }
    long long total = seed + bytes[at];

    printf("%lld\n", (long long)(total));
    return 0;
}
