// one unsigned int load, subtract-left
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int at_in = 3;

int main(void) {
    unsigned int seed = seed_in;
    int at = at_in;

    unsigned int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned int)i;
    }
    unsigned int total = buffer[at] - seed;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
