// one long long load, load-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long first_in = 4ll;
static volatile long long second_in = 9ll;

int main(void) {
    long long first = first_in;
    long long second = second_in;

    long long total = second - first;

    printf("%lld\n", (long long)(total));
    return 0;
}
