// one unsigned long long load, narrower-load
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int at_in = 3;

int main(void) {
    unsigned long long seed = seed_in;
    int at = at_in;

    unsigned char bytes[8];
    for (int i = 0; i < 8; i++) {
        bytes[i] = (unsigned char)(seed + i);
    }
    unsigned long long total = seed + bytes[at];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
