// one int load, call-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int at_in = 3;
static volatile int noise_count;
static void noise(void) {
    noise_count = noise_count + 1;
}
static void (*volatile jump)(void) = noise;

int main(void) {
    int seed = seed_in;
    int at = at_in;

    int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (int)i;
    }
    int value = buffer[at];
    jump();
    int total = seed + value;

    printf("%lld\n", (long long)(total));
    return 0;
}
