// a 16 statement int helper called from 1 places
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int helper(int value) {
    value = value + (int)1;
    value = value + (int)2;
    value = value + (int)3;
    value = value + (int)4;
    value = value + (int)5;
    value = value + (int)6;
    value = value + (int)7;
    value = value + (int)8;
    value = value + (int)9;
    value = value + (int)10;
    value = value + (int)11;
    value = value + (int)12;
    value = value + (int)13;
    value = value + (int)14;
    value = value + (int)15;
    value = value + (int)16;
    return value;
}
static volatile int seed_in = 0;

int main(void) {
    int seed = seed_in;

    int total = 0;
    total += helper(seed + (int)0);

    printf("%lld\n", (long long)(total));
    return 0;
}
