// a 16 statement unsigned int helper called from 1 places
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int helper(unsigned int value) {
    value = value + (unsigned int)1u;
    value = value + (unsigned int)2u;
    value = value + (unsigned int)3u;
    value = value + (unsigned int)4u;
    value = value + (unsigned int)5u;
    value = value + (unsigned int)6u;
    value = value + (unsigned int)7u;
    value = value + (unsigned int)8u;
    value = value + (unsigned int)9u;
    value = value + (unsigned int)10u;
    value = value + (unsigned int)11u;
    value = value + (unsigned int)12u;
    value = value + (unsigned int)13u;
    value = value + (unsigned int)14u;
    value = value + (unsigned int)15u;
    value = value + (unsigned int)16u;
    return value;
}
static volatile unsigned int seed_in = 0u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += helper(seed + (unsigned int)0u);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
