// an invariant multiply inside a 8 iteration unsigned long long loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 3ull;
static volatile unsigned long long b_in = 5ull;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;

    unsigned long long total = 0;
    for (int i = 0; i < 8; i++) {
        total += a * b + (unsigned long long)i;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
