// a loop that counts-down, counted by the generator
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int counted = 0;
    int total = 0;
    for (int i = 10; i > 0; i -= 3) {
        counted++;
        total += i;
    }

    printf("%lld\n", (long long)(counted));
    printf("%lld\n", (long long)(total));
    return 0;
}
