// three induction variables over 100 iterations on unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned int scaled = 0, walked = 0;
    int counted = 0;
    unsigned int buffer[100];
    for (int i = 0; i < 100; i++) {
        buffer[i] = (unsigned int)i;
        scaled += (unsigned int)(i * 4);
        walked += buffer[i];
        counted++;
    }

    printf("%llu\n", (unsigned long long)(scaled));
    printf("%llu\n", (unsigned long long)(walked));
    printf("%lld\n", (long long)(counted));
    return 0;
}
