// a loop that derived-counter, counted by the generator
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int counted = 0;
    int derived = 1;
    int total = 0;
    for (int i = 0; i < 9; i++) {
        derived = i * 3 + 1;
        total += derived;
        counted++;
    }

    printf("%lld\n", (long long)(counted));
    printf("%lld\n", (long long)(derived));
    printf("%lld\n", (long long)(total));
    return 0;
}
