// a loop that unsigned-wraps-round, counted by the generator
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int counted = 0;
    unsigned int total = 0u;
    for (unsigned int i = 4294967288u; i != 4u; i++) {
        counted++;
        total += 1u;
    }

    printf("%lld\n", (long long)(counted));
    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
