// three induction variables over 3 iterations on unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned long long scaled = 0, walked = 0;
    int counted = 0;
    unsigned long long buffer[3];
    for (int i = 0; i < 3; i++) {
        buffer[i] = (unsigned long long)i;
        scaled += (unsigned long long)(i * 4);
        walked += buffer[i];
        counted++;
    }

    printf("%llu\n", (unsigned long long)(scaled));
    printf("%llu\n", (unsigned long long)(walked));
    printf("%lld\n", (long long)(counted));
    return 0;
}
