// the kernel memory model's tearing rule on unsigned short, after include/asm-generic/rwonce.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

#define _POSIX_C_SOURCE 200809L

#include <pthread.h>

int printf(const char *, ...);

#define READ_ONCE(x) (*(const volatile __typeof__(x) *)&(x))
#define WRITE_ONCE(x, v) (*(volatile __typeof__(x) *)&(x) = (v))

static volatile unsigned short seed_in = 7u;

static unsigned short word;
static int stop;
static int started;

static void *flip(void *arg) {
    (void)arg;
    WRITE_ONCE(started, 1);
    for (int i = 0; !READ_ONCE(stop); i++) {
        WRITE_ONCE(word, (i & 1) ? (unsigned short)0 : (unsigned short)65535u);
    }
    return 0;
}

int main(void) {
    pthread_t writer;
    pthread_create(&writer, 0, flip, 0);
    while (!READ_ONCE(started)) {
    }
    long long torn = 0;
    for (int i = 0; i < 200000; i++) {
        unsigned short seen = READ_ONCE(word);
        if (seen != 0 && seen != (unsigned short)65535u) {
            torn++;
        }
    }
    WRITE_ONCE(stop, 1);
    pthread_join(writer, 0);

    printf("%lld\n", (long long)(torn));
    return 0;
}
