// the kernel memory model's guarded-loop rule on unsigned char, after tools/memory-model/Documentation/explanation.txt in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

#define _POSIX_C_SOURCE 200809L

#include <stdint.h>
#include <sys/mman.h>
#include <unistd.h>

int printf(const char *, ...);

#define READ_ONCE(x) (*(const volatile __typeof__(x) *)&(x))
#define WRITE_ONCE(x, v) (*(volatile __typeof__(x) *)&(x) = (v))

static volatile unsigned char seed_in = 7u;

struct pair {
    unsigned char field;
    unsigned char guarded;
};

static unsigned char arena[3 * 65536];

static struct pair *straddle(void) {
    uintptr_t page = (uintptr_t)sysconf(_SC_PAGESIZE);
    unsigned char *edge = (unsigned char *)(((uintptr_t)arena + 2 * page - 1) & ~(page - 1));
    return (struct pair *)(edge - 1);
}

static int seal(struct pair *p) {
    uintptr_t page = (uintptr_t)sysconf(_SC_PAGESIZE);
    return mprotect(&p->guarded, (size_t)page, PROT_READ);
}

int main(void) {
    unsigned char seed = seed_in;
    struct pair *p = straddle();
    p->guarded = (unsigned char)(seed + 3);
    p->field = (unsigned char)(seed + 1);
    int sealed = seal(p);

    unsigned char data[64];
    for (int i = 0; i < 64; i++) {
        data[i] = (unsigned char)((i * 37 + seed) & 127);
    }
    for (int i = 0; i < 64; i++) {
        if (data[i] > 127) {
            p->guarded = data[i];
        }
    }

    printf("%lld\n", (long long)(sealed));
    printf("%llu\n", (unsigned long long)(p->guarded));
    printf("%llu\n", (unsigned long long)(p->field));
    return 0;
}
