// a unsigned long long compared once for a value and once for a branch
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 40ull;
static volatile unsigned long long b_in = 15ull;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;

    int total = (a == b);
    if (a != b) {
        total = total + 7;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
