// a long long subtracted and then asked which side of zero it is on
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 15ll;
static volatile long long b_in = 40ll;

int main(void) {
    long long a = a_in;
    long long b = b_in;

    long long d = (long long)(a - b);
    int total = (d < 0) ? 4 : 8;
    total = total + (int)(d + 30);

    printf("%lld\n", (long long)(total));
    return 0;
}
