// a long long joined and then asked whether it is zero
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 40ll;
static volatile long long b_in = 3ll;

int main(void) {
    long long a = a_in;
    long long b = b_in;

    long long joined = (long long)(a | b);
    int total = (joined != 0) ? 5 : 9;
    total = total + (int)(joined & 7);

    printf("%lld\n", (long long)(total));
    return 0;
}
