// a long long compared with the same pair twice
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 40ll;
static volatile long long b_in = 15ll;

int main(void) {
    long long a = a_in;
    long long b = b_in;

    int same = (a == b);
    int differ = (a != b);
    int total = same * 4 + differ;

    printf("%lld\n", (long long)(total));
    return 0;
}
