// a long long masked and then asked whether it is zero
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 40ll;
static volatile long long mask_in = 24ll;

int main(void) {
    long long a = a_in;
    long long mask = mask_in;

    long long masked = (long long)(a & mask);
    int total = 0;
    if (masked) {
        total = total + 3;
    }
    total = total + (int)masked * 2;

    printf("%lld\n", (long long)(total));
    return 0;
}
