// a unsigned int joined and then asked whether it is zero
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int a_in = 40u;
static volatile unsigned int b_in = 3u;

int main(void) {
    unsigned int a = a_in;
    unsigned int b = b_in;

    unsigned int joined = (unsigned int)(a | b);
    int total = (joined != 0) ? 5 : 9;
    total = total + (int)(joined & 7);

    printf("%lld\n", (long long)(total));
    return 0;
}
