// a long long masked, written over, and then asked whether it is zero
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 40ll;
static volatile long long mask_in = 24ll;
static volatile long long spare_in = 0ll;

int main(void) {
    long long a = a_in;
    long long mask = mask_in;
    long long spare = spare_in;

    long long value = (long long)(a & mask);
    int first = (value != 0);
    value = spare;
    int second = (value == 0);
    int total = first * 10 + second;

    printf("%lld\n", (long long)(total));
    return 0;
}
