// a variable argument list
// Generated by rucc-corpus. Edit the generator, not this file.

#include <stdarg.h>

int printf(const char *, ...);

static long long total(int count, ...) {
    va_list rest;
    long long sum = 0;
    va_start(rest, count);
    for (int at = 0; at < count; at++) {
        sum += va_arg(rest, long long);
    }
    va_end(rest);
    return sum;
}
static volatile long long seed_in = 1ll;

int main(void) {
    long long seed = seed_in;

    printf("%lld\n", (long long)(total(6, seed, seed + 1, seed + 2, seed + 3, seed + 4, seed + 5)));
    return 0;
}
