// a struct of 16 fields passed by value
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct bag { long long f0; long long f1; long long f2; long long f3; long long f4; long long f5; long long f6; long long f7; long long f8; long long f9; long long f10; long long f11; long long f12; long long f13; long long f14; long long f15; };
static long long total(struct bag value) {
    return value.f0 + value.f1 + value.f2 + value.f3 + value.f4 + value.f5 + value.f6 + value.f7 + value.f8 + value.f9 + value.f10 + value.f11 + value.f12 + value.f13 + value.f14 + value.f15;
}
static struct bag build(long long seed) {
    struct bag out;
    out.f0 = seed + 0;
    out.f1 = seed + 1;
    out.f2 = seed + 2;
    out.f3 = seed + 3;
    out.f4 = seed + 4;
    out.f5 = seed + 5;
    out.f6 = seed + 6;
    out.f7 = seed + 7;
    out.f8 = seed + 8;
    out.f9 = seed + 9;
    out.f10 = seed + 10;
    out.f11 = seed + 11;
    out.f12 = seed + 12;
    out.f13 = seed + 13;
    out.f14 = seed + 14;
    out.f15 = seed + 15;
    return out;
}
static volatile long long seed_in = 1ll;

int main(void) {
    long long seed = seed_in;

    struct bag made = build(seed);
    printf("%lld\n", (long long)(total(made)));
    return 0;
}
