// a call with 6 integer arguments
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long total6(long long a0, long long a1, long long a2, long long a3, long long a4, long long a5) {
    return a0 + a1 + a2 + a3 + a4 + a5;
}
static volatile long long seed_in = 1ll;

int main(void) {
    long long seed = seed_in;

    printf("%lld\n", (long long)(total6(seed + 0, seed + 1, seed + 2, seed + 3, seed + 4, seed + 5)));
    return 0;
}
