// self tail recursion 1000 deep accumulating into int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int walk(int left, int total) {
    if (left == 0) {
        return total;
    }
    return walk(left - 1, total + 1);
}
static volatile int depth_in = 1000;

int main(void) {
    int depth = depth_in;

    printf("%lld\n", (long long)(walk(depth, (int)0)));
    return 0;
}
