// mutual tail recursion 1000 deep accumulating into unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int odd(int left, unsigned int total);
static unsigned int even(int left, unsigned int total) {
    if (left == 0) {
        return total;
    }
    return odd(left - 1, total + 1);
}
static unsigned int odd(int left, unsigned int total) {
    if (left == 0) {
        return total;
    }
    return even(left - 1, total + 1);
}
static unsigned int walk(int left, unsigned int total) {
    return even(left, total);
}
static volatile int depth_in = 1000;

int main(void) {
    int depth = depth_in;

    printf("%llu\n", (unsigned long long)(walk(depth, (unsigned int)0u)));
    return 0;
}
