// self tail recursion 8 deep accumulating into unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int walk(int left, unsigned int total) {
    if (left == 0) {
        return total;
    }
    return walk(left - 1, total + 1);
}
static volatile int depth_in = 8;

int main(void) {
    int depth = depth_in;

    printf("%llu\n", (unsigned long long)(walk(depth, (unsigned int)0u)));
    return 0;
}
