// mutual tail recursion 5000 deep accumulating into long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long odd(int left, long long total);
static long long even(int left, long long total) {
    if (left == 0) {
        return total;
    }
    return odd(left - 1, total + 1);
}
static long long odd(int left, long long total) {
    if (left == 0) {
        return total;
    }
    return even(left - 1, total + 1);
}
static long long walk(int left, long long total) {
    return even(left, total);
}
static volatile int depth_in = 5000;

int main(void) {
    int depth = depth_in;

    printf("%lld\n", (long long)(walk(depth, (long long)0ll)));
    return 0;
}
