// indirect-call built with the rethunk mitigation, after arch/x86/Makefile in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

__asm__(
    ".text\n"
    ".globl __x86_return_thunk\n"
    "__x86_return_thunk:\n"
    "\tret\n"
);

static volatile unsigned int seed_in = 7;

__attribute__((noinline))
static unsigned int op0(unsigned int x, unsigned int i) {
    return x + i * 3u + 1u;
}
__attribute__((noinline))
static unsigned int op1(unsigned int x, unsigned int i) {
    return x ^ (i * 0x9e3779b9u);
}
__attribute__((noinline))
static unsigned int op2(unsigned int x, unsigned int i) {
    return x * 33u + i;
}
__attribute__((noinline))
static unsigned int op3(unsigned int x, unsigned int i) {
    return x - i;
}

static unsigned int (*const table[4])(unsigned int, unsigned int) = {
    op0, op1, op2, op3,
};

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = table[(acc + i) & 3](acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
