// early-return built with the ibt mitigation, after arch/x86/Makefile in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

__attribute__((noinline))
static unsigned int settle(unsigned int x, unsigned int i) {
    if (x < 1000u) {
        return x * 3u + i;
    }
    if ((x & 15u) == 3u) {
        return x >> 2;
    }
    if (i & 1u) {
        return x - i;
    }
    return (x >> 1) + i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = settle(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
