// rem of an unknown long long by a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long x0_in = (-9223372036854775807ll - 1);
static volatile long long x1_in = (-2ll);
static volatile long long x2_in = 1ll;
static volatile long long x3_in = 7ll;
static volatile long long x4_in = 255ll;
static volatile long long x5_in = 9223372036854775807ll;

int main(void) {
    long long x0 = x0_in;
    printf("%lld\n", (long long)(x0 % ((long long)1ll)));
    printf("%lld\n", (long long)(x0 % ((long long)2ll)));
    printf("%lld\n", (long long)(x0 % ((long long)3ll)));
    printf("%lld\n", (long long)(x0 % ((long long)4ll)));
    printf("%lld\n", (long long)(x0 % ((long long)5ll)));
    printf("%lld\n", (long long)(x0 % ((long long)7ll)));
    printf("%lld\n", (long long)(x0 % ((long long)8ll)));
    printf("%lld\n", (long long)(x0 % ((long long)10ll)));
    printf("%lld\n", (long long)(x0 % ((long long)16ll)));
    printf("%lld\n", (long long)(x0 % ((long long)64ll)));
    printf("%lld\n", (long long)(x0 % ((long long)100ll)));
    printf("%lld\n", (long long)(x0 % ((long long)255ll)));
    printf("%lld\n", (long long)(x0 % ((long long)1000ll)));
    printf("%lld\n", (long long)(x0 % ((long long)1024ll)));

    long long x1 = x1_in;
    printf("%lld\n", (long long)(x1 % ((long long)1ll)));
    printf("%lld\n", (long long)(x1 % ((long long)2ll)));
    printf("%lld\n", (long long)(x1 % ((long long)3ll)));
    printf("%lld\n", (long long)(x1 % ((long long)4ll)));
    printf("%lld\n", (long long)(x1 % ((long long)5ll)));
    printf("%lld\n", (long long)(x1 % ((long long)7ll)));
    printf("%lld\n", (long long)(x1 % ((long long)8ll)));
    printf("%lld\n", (long long)(x1 % ((long long)10ll)));
    printf("%lld\n", (long long)(x1 % ((long long)16ll)));
    printf("%lld\n", (long long)(x1 % ((long long)64ll)));
    printf("%lld\n", (long long)(x1 % ((long long)100ll)));
    printf("%lld\n", (long long)(x1 % ((long long)255ll)));
    printf("%lld\n", (long long)(x1 % ((long long)1000ll)));
    printf("%lld\n", (long long)(x1 % ((long long)1024ll)));

    long long x2 = x2_in;
    printf("%lld\n", (long long)(x2 % ((long long)1ll)));
    printf("%lld\n", (long long)(x2 % ((long long)2ll)));
    printf("%lld\n", (long long)(x2 % ((long long)3ll)));
    printf("%lld\n", (long long)(x2 % ((long long)4ll)));
    printf("%lld\n", (long long)(x2 % ((long long)5ll)));
    printf("%lld\n", (long long)(x2 % ((long long)7ll)));
    printf("%lld\n", (long long)(x2 % ((long long)8ll)));
    printf("%lld\n", (long long)(x2 % ((long long)10ll)));
    printf("%lld\n", (long long)(x2 % ((long long)16ll)));
    printf("%lld\n", (long long)(x2 % ((long long)64ll)));
    printf("%lld\n", (long long)(x2 % ((long long)100ll)));
    printf("%lld\n", (long long)(x2 % ((long long)255ll)));
    printf("%lld\n", (long long)(x2 % ((long long)1000ll)));
    printf("%lld\n", (long long)(x2 % ((long long)1024ll)));

    long long x3 = x3_in;
    printf("%lld\n", (long long)(x3 % ((long long)1ll)));
    printf("%lld\n", (long long)(x3 % ((long long)2ll)));
    printf("%lld\n", (long long)(x3 % ((long long)3ll)));
    printf("%lld\n", (long long)(x3 % ((long long)4ll)));
    printf("%lld\n", (long long)(x3 % ((long long)5ll)));
    printf("%lld\n", (long long)(x3 % ((long long)7ll)));
    printf("%lld\n", (long long)(x3 % ((long long)8ll)));
    printf("%lld\n", (long long)(x3 % ((long long)10ll)));
    printf("%lld\n", (long long)(x3 % ((long long)16ll)));
    printf("%lld\n", (long long)(x3 % ((long long)64ll)));
    printf("%lld\n", (long long)(x3 % ((long long)100ll)));
    printf("%lld\n", (long long)(x3 % ((long long)255ll)));
    printf("%lld\n", (long long)(x3 % ((long long)1000ll)));
    printf("%lld\n", (long long)(x3 % ((long long)1024ll)));

    long long x4 = x4_in;
    printf("%lld\n", (long long)(x4 % ((long long)1ll)));
    printf("%lld\n", (long long)(x4 % ((long long)2ll)));
    printf("%lld\n", (long long)(x4 % ((long long)3ll)));
    printf("%lld\n", (long long)(x4 % ((long long)4ll)));
    printf("%lld\n", (long long)(x4 % ((long long)5ll)));
    printf("%lld\n", (long long)(x4 % ((long long)7ll)));
    printf("%lld\n", (long long)(x4 % ((long long)8ll)));
    printf("%lld\n", (long long)(x4 % ((long long)10ll)));
    printf("%lld\n", (long long)(x4 % ((long long)16ll)));
    printf("%lld\n", (long long)(x4 % ((long long)64ll)));
    printf("%lld\n", (long long)(x4 % ((long long)100ll)));
    printf("%lld\n", (long long)(x4 % ((long long)255ll)));
    printf("%lld\n", (long long)(x4 % ((long long)1000ll)));
    printf("%lld\n", (long long)(x4 % ((long long)1024ll)));

    long long x5 = x5_in;
    printf("%lld\n", (long long)(x5 % ((long long)1ll)));
    printf("%lld\n", (long long)(x5 % ((long long)2ll)));
    printf("%lld\n", (long long)(x5 % ((long long)3ll)));
    printf("%lld\n", (long long)(x5 % ((long long)4ll)));
    printf("%lld\n", (long long)(x5 % ((long long)5ll)));
    printf("%lld\n", (long long)(x5 % ((long long)7ll)));
    printf("%lld\n", (long long)(x5 % ((long long)8ll)));
    printf("%lld\n", (long long)(x5 % ((long long)10ll)));
    printf("%lld\n", (long long)(x5 % ((long long)16ll)));
    printf("%lld\n", (long long)(x5 % ((long long)64ll)));
    printf("%lld\n", (long long)(x5 % ((long long)100ll)));
    printf("%lld\n", (long long)(x5 % ((long long)255ll)));
    printf("%lld\n", (long long)(x5 % ((long long)1000ll)));
    printf("%lld\n", (long long)(x5 % ((long long)1024ll)));

    return 0;
}
