// div of an unknown int by a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int x0_in = (-2147483647 - 1);
static volatile int x1_in = (-2);
static volatile int x2_in = 1;
static volatile int x3_in = 7;
static volatile int x4_in = 255;
static volatile int x5_in = 2147483647;

int main(void) {
    int x0 = x0_in;
    printf("%lld\n", (long long)(x0 / ((int)(-2))));
    printf("%lld\n", (long long)(x0 / ((int)1)));
    printf("%lld\n", (long long)(x0 / ((int)2)));
    printf("%lld\n", (long long)(x0 / ((int)3)));
    printf("%lld\n", (long long)(x0 / ((int)4)));
    printf("%lld\n", (long long)(x0 / ((int)5)));
    printf("%lld\n", (long long)(x0 / ((int)7)));
    printf("%lld\n", (long long)(x0 / ((int)8)));
    printf("%lld\n", (long long)(x0 / ((int)10)));
    printf("%lld\n", (long long)(x0 / ((int)16)));
    printf("%lld\n", (long long)(x0 / ((int)64)));
    printf("%lld\n", (long long)(x0 / ((int)100)));
    printf("%lld\n", (long long)(x0 / ((int)255)));
    printf("%lld\n", (long long)(x0 / ((int)1000)));
    printf("%lld\n", (long long)(x0 / ((int)1024)));

    int x1 = x1_in;
    printf("%lld\n", (long long)(x1 / ((int)(-2))));
    printf("%lld\n", (long long)(x1 / ((int)(-1))));
    printf("%lld\n", (long long)(x1 / ((int)1)));
    printf("%lld\n", (long long)(x1 / ((int)2)));
    printf("%lld\n", (long long)(x1 / ((int)3)));
    printf("%lld\n", (long long)(x1 / ((int)4)));
    printf("%lld\n", (long long)(x1 / ((int)5)));
    printf("%lld\n", (long long)(x1 / ((int)7)));
    printf("%lld\n", (long long)(x1 / ((int)8)));
    printf("%lld\n", (long long)(x1 / ((int)10)));
    printf("%lld\n", (long long)(x1 / ((int)16)));
    printf("%lld\n", (long long)(x1 / ((int)64)));
    printf("%lld\n", (long long)(x1 / ((int)100)));
    printf("%lld\n", (long long)(x1 / ((int)255)));
    printf("%lld\n", (long long)(x1 / ((int)1000)));
    printf("%lld\n", (long long)(x1 / ((int)1024)));

    int x2 = x2_in;
    printf("%lld\n", (long long)(x2 / ((int)(-2))));
    printf("%lld\n", (long long)(x2 / ((int)(-1))));
    printf("%lld\n", (long long)(x2 / ((int)1)));
    printf("%lld\n", (long long)(x2 / ((int)2)));
    printf("%lld\n", (long long)(x2 / ((int)3)));
    printf("%lld\n", (long long)(x2 / ((int)4)));
    printf("%lld\n", (long long)(x2 / ((int)5)));
    printf("%lld\n", (long long)(x2 / ((int)7)));
    printf("%lld\n", (long long)(x2 / ((int)8)));
    printf("%lld\n", (long long)(x2 / ((int)10)));
    printf("%lld\n", (long long)(x2 / ((int)16)));
    printf("%lld\n", (long long)(x2 / ((int)64)));
    printf("%lld\n", (long long)(x2 / ((int)100)));
    printf("%lld\n", (long long)(x2 / ((int)255)));
    printf("%lld\n", (long long)(x2 / ((int)1000)));
    printf("%lld\n", (long long)(x2 / ((int)1024)));

    int x3 = x3_in;
    printf("%lld\n", (long long)(x3 / ((int)(-2))));
    printf("%lld\n", (long long)(x3 / ((int)(-1))));
    printf("%lld\n", (long long)(x3 / ((int)1)));
    printf("%lld\n", (long long)(x3 / ((int)2)));
    printf("%lld\n", (long long)(x3 / ((int)3)));
    printf("%lld\n", (long long)(x3 / ((int)4)));
    printf("%lld\n", (long long)(x3 / ((int)5)));
    printf("%lld\n", (long long)(x3 / ((int)7)));
    printf("%lld\n", (long long)(x3 / ((int)8)));
    printf("%lld\n", (long long)(x3 / ((int)10)));
    printf("%lld\n", (long long)(x3 / ((int)16)));
    printf("%lld\n", (long long)(x3 / ((int)64)));
    printf("%lld\n", (long long)(x3 / ((int)100)));
    printf("%lld\n", (long long)(x3 / ((int)255)));
    printf("%lld\n", (long long)(x3 / ((int)1000)));
    printf("%lld\n", (long long)(x3 / ((int)1024)));

    int x4 = x4_in;
    printf("%lld\n", (long long)(x4 / ((int)(-2))));
    printf("%lld\n", (long long)(x4 / ((int)(-1))));
    printf("%lld\n", (long long)(x4 / ((int)1)));
    printf("%lld\n", (long long)(x4 / ((int)2)));
    printf("%lld\n", (long long)(x4 / ((int)3)));
    printf("%lld\n", (long long)(x4 / ((int)4)));
    printf("%lld\n", (long long)(x4 / ((int)5)));
    printf("%lld\n", (long long)(x4 / ((int)7)));
    printf("%lld\n", (long long)(x4 / ((int)8)));
    printf("%lld\n", (long long)(x4 / ((int)10)));
    printf("%lld\n", (long long)(x4 / ((int)16)));
    printf("%lld\n", (long long)(x4 / ((int)64)));
    printf("%lld\n", (long long)(x4 / ((int)100)));
    printf("%lld\n", (long long)(x4 / ((int)255)));
    printf("%lld\n", (long long)(x4 / ((int)1000)));
    printf("%lld\n", (long long)(x4 / ((int)1024)));

    int x5 = x5_in;
    printf("%lld\n", (long long)(x5 / ((int)(-2))));
    printf("%lld\n", (long long)(x5 / ((int)(-1))));
    printf("%lld\n", (long long)(x5 / ((int)1)));
    printf("%lld\n", (long long)(x5 / ((int)2)));
    printf("%lld\n", (long long)(x5 / ((int)3)));
    printf("%lld\n", (long long)(x5 / ((int)4)));
    printf("%lld\n", (long long)(x5 / ((int)5)));
    printf("%lld\n", (long long)(x5 / ((int)7)));
    printf("%lld\n", (long long)(x5 / ((int)8)));
    printf("%lld\n", (long long)(x5 / ((int)10)));
    printf("%lld\n", (long long)(x5 / ((int)16)));
    printf("%lld\n", (long long)(x5 / ((int)64)));
    printf("%lld\n", (long long)(x5 / ((int)100)));
    printf("%lld\n", (long long)(x5 / ((int)255)));
    printf("%lld\n", (long long)(x5 / ((int)1000)));
    printf("%lld\n", (long long)(x5 / ((int)1024)));

    return 0;
}
