// a 8 by 8 unsigned int traversal, column-major
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static unsigned int grid[8][8];
    unsigned int total = 0;

    for (int c = 0; c < 8; c++) {
        for (int r = 0; r < 8; r++) {
            grid[r][c] = (unsigned int)(r * 8 + c);
            total += grid[r][c];
        }
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
