// a 16 by 16 int traversal, column-major
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static int grid[16][16];
    int total = 0;

    for (int c = 0; c < 16; c++) {
        for (int r = 0; r < 16; r++) {
            grid[r][c] = (int)(r * 16 + c);
            total += grid[r][c];
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
