// a 4 by 4 long long traversal, fused
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static long long grid[4][4];
    long long total = 0;

    for (int at = 0; at < 16; at++) {
        int r = at / 4;
        int c = at % 4;
        grid[r][c] = (long long)(r * 4 + c);
        total += grid[r][c];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
