// a 4 by 4 int traversal, two-loops
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static int grid[4][4];
    int total = 0;

    for (int r = 0; r < 4; r++) {
        for (int c = 0; c < 4; c++) {
            grid[r][c] = (int)(r * 4 + c);
        }
    }
    for (int r = 0; r < 4; r++) {
        for (int c = 0; c < 4; c++) {
            total += grid[r][c];
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
