// a 16 by 16 unsigned int traversal, fused
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static unsigned int grid[16][16];
    unsigned int total = 0;

    for (int at = 0; at < 256; at++) {
        int r = at / 16;
        int c = at % 16;
        grid[r][c] = (unsigned int)(r * 16 + c);
        total += grid[r][c];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
