// a 16 by 16 int traversal, fused
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static int grid[16][16];
    int total = 0;

    for (int at = 0; at < 256; at++) {
        int r = at / 16;
        int c = at % 16;
        grid[r][c] = (int)(r * 16 + c);
        total += grid[r][c];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
