// a 4 by 4 long long traversal, column-major
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static long long grid[4][4];
    long long total = 0;

    for (int c = 0; c < 4; c++) {
        for (int r = 0; r < 4; r++) {
            grid[r][c] = (long long)(r * 4 + c);
            total += grid[r][c];
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
