// a 16 by 16 unsigned long long traversal, column-major
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    static unsigned long long grid[16][16];
    unsigned long long total = 0;

    for (int c = 0; c < 16; c++) {
        for (int r = 0; r < 16; r++) {
            grid[r][c] = (unsigned long long)(r * 16 + c);
            total += grid[r][c];
        }
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
