// a non-escaping int aggregate, array-constant-index
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 8;

int main(void) {
    int seed = seed_in;

    int slots[8];
    slots[2] = seed;
    slots[5] = seed + (int)1;
    int total = slots[2] + slots[5];

    printf("%lld\n", (long long)(total));
    return 0;
}
