// a non-escaping unsigned long long aggregate, array-constant-index
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 8ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long slots[8];
    slots[2] = seed;
    slots[5] = seed + (unsigned long long)1ull;
    unsigned long long total = slots[2] + slots[5];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
