// a non-escaping unsigned int aggregate, struct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 8u;
struct pair { unsigned int first; unsigned int second; };

int main(void) {
    unsigned int seed = seed_in;

    struct pair p;
    p.first = seed;
    p.second = seed + (unsigned int)1u;
    unsigned int total = p.first + p.second;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
