// a non-escaping unsigned int aggregate, address-taken
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 8u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int one = seed;
    unsigned int two = seed + (unsigned int)1u;
    unsigned int *at = &one;
    *at = one;
    unsigned int total = *at + two;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
