// a non-escaping int aggregate, address-taken
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 8;

int main(void) {
    int seed = seed_in;

    int one = seed;
    int two = seed + (int)1;
    int *at = &one;
    *at = one;
    int total = *at + two;

    printf("%lld\n", (long long)(total));
    return 0;
}
