// a non-escaping int aggregate, struct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 8;
struct pair { int first; int second; };

int main(void) {
    int seed = seed_in;

    struct pair p;
    p.first = seed;
    p.second = seed + (int)1;
    int total = p.first + p.second;

    printf("%lld\n", (long long)(total));
    return 0;
}
