// a non-escaping unsigned long long aggregate, address-taken
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 8ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long one = seed;
    unsigned long long two = seed + (unsigned long long)1ull;
    unsigned long long *at = &one;
    *at = one;
    unsigned long long total = *at + two;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
