// a non-escaping long long aggregate, address-taken
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 8ll;

int main(void) {
    long long seed = seed_in;

    long long one = seed;
    long long two = seed + (long long)1ll;
    long long *at = &one;
    *at = one;
    long long total = *at + two;

    printf("%lld\n", (long long)(total));
    return 0;
}
