// a non-escaping unsigned int aggregate, array-constant-index
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 8u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int slots[8];
    slots[2] = seed;
    slots[5] = seed + (unsigned int)1u;
    unsigned int total = slots[2] + slots[5];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
