// long double, at least as wide as double
// Generated by rucc-corpus. Edit the generator, not this file.

#include <float.h>

int printf(const char *, ...);

int main(void) {

    printf("%lld\n", (long long)(LDBL_MANT_DIG >= DBL_MANT_DIG));
    printf("%lld\n", (long long)(LDBL_MAX_EXP >= DBL_MAX_EXP));
    printf("%lld\n", (long long)(LDBL_MIN_EXP <= DBL_MIN_EXP));
    printf("%lld\n", (long long)(LDBL_DIG >= DBL_DIG));
    printf("%lld\n", (long long)(LDBL_EPSILON <= DBL_EPSILON));
    return 0;
}
