// a unsigned long long parameter nothing reads, variadic
// Generated by rucc-corpus. Edit the generator, not this file.

#include <stdarg.h>

int printf(const char *, ...);

static unsigned long long first(unsigned long long value, ...) {
    return (unsigned long long)(value + 1);
}
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    total += first(seed, seed);
    total += first(seed, seed);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
