// a unsigned long long parameter nothing reads, argument-is-an-address
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long note(unsigned long long value, unsigned long long *ignored) {
    return (unsigned long long)(value + 1);
}
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    unsigned long long spot = (unsigned long long)(seed * 3);
    total += note(seed, &spot);

    printf("%llu\n", (unsigned long long)(spot));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
