// a int parameter nothing reads, argument-has-a-side-effect
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int keep(int value, int ignored) {
    return (int)(value + 1);
}
static int counter = (int)0;
static int bump(void) {
    counter = (int)(counter + 1);
    return counter;
}
static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;

    int total = 0;
    total += keep(seed, bump());
    total += keep(seed, bump());

    printf("%lld\n", (long long)(counter));

    printf("%lld\n", (long long)(total));
    return 0;
}
