// a long long parameter nothing reads, transitive-sum
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long keep(long long value, long long ignored) {
    return (long long)(value + 1);
}
static long long outer(long long value, long long left, long long right) {
    return keep(value, (long long)(left + right));
}
static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long total = 0;
    total += outer(seed, (long long)(seed * 2), (long long)(seed + 5));
    total += outer(seed, (long long)(seed * 2), (long long)(seed + 5));

    printf("%lld\n", (long long)(total));
    return 0;
}
