// a unsigned long long parameter nothing reads, transitive-sum
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long keep(unsigned long long value, unsigned long long ignored) {
    return (unsigned long long)(value + 1);
}
static unsigned long long outer(unsigned long long value, unsigned long long left, unsigned long long right) {
    return keep(value, (unsigned long long)(left + right));
}
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    total += outer(seed, (unsigned long long)(seed * 2), (unsigned long long)(seed + 5));
    total += outer(seed, (unsigned long long)(seed * 2), (unsigned long long)(seed + 5));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
