// a unsigned int parameter nothing reads, constant-then-unread
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int scaled(unsigned int value, unsigned int factor) {
    return (unsigned int)(value * factor);
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += scaled(seed, (unsigned int)10u);
    total += scaled(seed, (unsigned int)10u);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
