// a unsigned int parameter nothing reads, one-unread
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int keep(unsigned int value, unsigned int ignored) {
    return (unsigned int)(value + 1);
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += keep(seed, (unsigned int)(seed * 5));
    total += keep(seed, (unsigned int)(seed * 5));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
