// a unsigned int parameter nothing reads, other-objects-call-it
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

unsigned int keep(unsigned int value, unsigned int ignored) {
    return (unsigned int)(value + 1);
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += keep(seed, seed);
    total += keep(seed, seed);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
