// a int parameter nothing reads, address-escapes
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int keep(int value, int ignored) {
    return (int)(value + 1);
}
static int (*chosen)(int, int) = keep;
static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;

    int total = 0;
    total += keep(seed, seed);
    total += chosen(seed, seed);

    printf("%lld\n", (long long)(total));
    return 0;
}
