// a unsigned long long parameter nothing reads, middle-unread
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long pick(unsigned long long first, unsigned long long ignored, unsigned long long last) {
    return (unsigned long long)(first * 10 + last);
}
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    total += pick(seed, (unsigned long long)(seed + 7), (unsigned long long)(seed + 1));
    total += pick(seed, seed, (unsigned long long)(seed + 2));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
