// a unsigned int parameter nothing reads, recursive-only
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int walk(unsigned int value, unsigned int carried, unsigned int depth) {
    if (depth == (unsigned int)0u) {
        return value;
    }
    return walk((unsigned int)(value + 1), carried, (unsigned int)(depth - 1));
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += walk(seed, (unsigned int)(seed * 4), (unsigned int)3u);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
