// a double truncated into signed char, with the value read from memory
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile double double_i8_in[12] = { 0e0, -0e0, 5e-1, -5e-1, 1e0, -1e0, 1.5e0, -1.5e0, 3.75e0, -3.75e0, 1.275e2, -1.285e2 };

int main(void) {

    printf("%lld\n", (long long)((signed char)(double_i8_in[0])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[1])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[2])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[3])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[4])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[5])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[6])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[7])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[8])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[9])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[10])));
    printf("%lld\n", (long long)((signed char)(double_i8_in[11])));
    return 0;
}
