// a double truncated into unsigned char, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%llu\n", (unsigned long long)((unsigned char)(0e0)));
    printf("%llu\n", (unsigned long long)((unsigned char)(-0e0)));
    printf("%llu\n", (unsigned long long)((unsigned char)(5e-1)));
    printf("%llu\n", (unsigned long long)((unsigned char)(-5e-1)));
    printf("%llu\n", (unsigned long long)((unsigned char)(1e0)));
    printf("%llu\n", (unsigned long long)((unsigned char)(1.5e0)));
    printf("%llu\n", (unsigned long long)((unsigned char)(3.75e0)));
    printf("%llu\n", (unsigned long long)((unsigned char)(1.275e2)));
    printf("%llu\n", (unsigned long long)((unsigned char)(2.5575e2)));
    return 0;
}
