// a float truncated into signed char, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((signed char)(0e0f)));
    printf("%lld\n", (long long)((signed char)(-0e0f)));
    printf("%lld\n", (long long)((signed char)(5e-1f)));
    printf("%lld\n", (long long)((signed char)(-5e-1f)));
    printf("%lld\n", (long long)((signed char)(1e0f)));
    printf("%lld\n", (long long)((signed char)(-1e0f)));
    printf("%lld\n", (long long)((signed char)(1.5e0f)));
    printf("%lld\n", (long long)((signed char)(-1.5e0f)));
    printf("%lld\n", (long long)((signed char)(3.75e0f)));
    printf("%lld\n", (long long)((signed char)(-3.75e0f)));
    printf("%lld\n", (long long)((signed char)(1.275e2f)));
    printf("%lld\n", (long long)((signed char)(-1.285e2f)));
    return 0;
}
