// a float truncated into unsigned short, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%llu\n", (unsigned long long)((unsigned short)(0e0f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(-0e0f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(5e-1f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(-5e-1f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(1e0f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(1.5e0f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(3.75e0f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(1.275e2f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(2.5575e2f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(3.27675e4f)));
    printf("%llu\n", (unsigned long long)((unsigned short)(6.55355e4f)));
    return 0;
}
