// a float truncated into unsigned char, with the value read from memory
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile float float_u8_in[9] = { 0e0f, -0e0f, 5e-1f, -5e-1f, 1e0f, 1.5e0f, 3.75e0f, 1.275e2f, 2.5575e2f };

int main(void) {

    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[0])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[1])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[2])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[3])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[4])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[5])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[6])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[7])));
    printf("%llu\n", (unsigned long long)((unsigned char)(float_u8_in[8])));
    return 0;
}
