// a double truncated into signed char, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((signed char)(0e0)));
    printf("%lld\n", (long long)((signed char)(-0e0)));
    printf("%lld\n", (long long)((signed char)(5e-1)));
    printf("%lld\n", (long long)((signed char)(-5e-1)));
    printf("%lld\n", (long long)((signed char)(1e0)));
    printf("%lld\n", (long long)((signed char)(-1e0)));
    printf("%lld\n", (long long)((signed char)(1.5e0)));
    printf("%lld\n", (long long)((signed char)(-1.5e0)));
    printf("%lld\n", (long long)((signed char)(3.75e0)));
    printf("%lld\n", (long long)((signed char)(-3.75e0)));
    printf("%lld\n", (long long)((signed char)(1.275e2)));
    printf("%lld\n", (long long)((signed char)(-1.285e2)));
    return 0;
}
