// signed char out to a float and back, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((signed char)(float)((signed char)(-127 - 1))));
    printf("%lld\n", (long long)((signed char)(float)((signed char)(-8))));
    printf("%lld\n", (long long)((signed char)(float)((signed char)(-2))));
    printf("%lld\n", (long long)((signed char)(float)((signed char)(-1))));
    printf("%lld\n", (long long)((signed char)(float)((signed char)0)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)1)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)2)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)3)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)7)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)8)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)16)));
    printf("%lld\n", (long long)((signed char)(float)((signed char)127)));
    return 0;
}
