// a double narrowed to a float, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((long long)(float)(1.6777216e7)));
    printf("%lld\n", (long long)((long long)(double)(float)(1.6777216e7)));
    printf("%lld\n", (long long)((long long)(float)(3.3554437e7)));
    printf("%lld\n", (long long)((long long)(double)(float)(3.3554437e7)));
    printf("%lld\n", (long long)((long long)(float)(3.3554443e7)));
    printf("%lld\n", (long long)((long long)(double)(float)(3.3554443e7)));
    printf("%lld\n", (long long)((long long)(float)(1e9)));
    printf("%lld\n", (long long)((long long)(double)(float)(1e9)));
    printf("%lld\n", (long long)((long long)(float)(1.23456789e9)));
    printf("%lld\n", (long long)((long long)(double)(float)(1.23456789e9)));
    printf("%lld\n", (long long)((long long)(float)(-1.23456789e9)));
    printf("%lld\n", (long long)((long long)(double)(float)(-1.23456789e9)));
    printf("%lld\n", (long long)((long long)(float)(4.503599627370497e15)));
    printf("%lld\n", (long long)((long long)(double)(float)(4.503599627370497e15)));
    return 0;
}
