// a float truncated into short, with the value read from memory
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile float float_i16_in[15] = { 0e0f, -0e0f, 5e-1f, -5e-1f, 1e0f, -1e0f, 1.5e0f, -1.5e0f, 3.75e0f, -3.75e0f, 1.275e2f, -1.285e2f, 2.5575e2f, 3.27675e4f, -3.27685e4f };

int main(void) {

    printf("%lld\n", (long long)((short)(float_i16_in[0])));
    printf("%lld\n", (long long)((short)(float_i16_in[1])));
    printf("%lld\n", (long long)((short)(float_i16_in[2])));
    printf("%lld\n", (long long)((short)(float_i16_in[3])));
    printf("%lld\n", (long long)((short)(float_i16_in[4])));
    printf("%lld\n", (long long)((short)(float_i16_in[5])));
    printf("%lld\n", (long long)((short)(float_i16_in[6])));
    printf("%lld\n", (long long)((short)(float_i16_in[7])));
    printf("%lld\n", (long long)((short)(float_i16_in[8])));
    printf("%lld\n", (long long)((short)(float_i16_in[9])));
    printf("%lld\n", (long long)((short)(float_i16_in[10])));
    printf("%lld\n", (long long)((short)(float_i16_in[11])));
    printf("%lld\n", (long long)((short)(float_i16_in[12])));
    printf("%lld\n", (long long)((short)(float_i16_in[13])));
    printf("%lld\n", (long long)((short)(float_i16_in[14])));
    return 0;
}
