// a double truncated into unsigned int, with the value read from memory
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile double double_u32_in[13] = { 0e0, -0e0, 5e-1, -5e-1, 1e0, 1.5e0, 3.75e0, 1.275e2, 2.5575e2, 3.27675e4, 6.55355e4, 2.147483647e9, 4.294967295e9 };

int main(void) {

    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[0])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[1])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[2])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[3])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[4])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[5])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[6])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[7])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[8])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[9])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[10])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[11])));
    printf("%llu\n", (unsigned long long)((unsigned int)(double_u32_in[12])));
    return 0;
}
