// a double truncated into int, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((int)(0e0)));
    printf("%lld\n", (long long)((int)(-0e0)));
    printf("%lld\n", (long long)((int)(5e-1)));
    printf("%lld\n", (long long)((int)(-5e-1)));
    printf("%lld\n", (long long)((int)(1e0)));
    printf("%lld\n", (long long)((int)(-1e0)));
    printf("%lld\n", (long long)((int)(1.5e0)));
    printf("%lld\n", (long long)((int)(-1.5e0)));
    printf("%lld\n", (long long)((int)(3.75e0)));
    printf("%lld\n", (long long)((int)(-3.75e0)));
    printf("%lld\n", (long long)((int)(1.275e2)));
    printf("%lld\n", (long long)((int)(-1.285e2)));
    printf("%lld\n", (long long)((int)(2.5575e2)));
    printf("%lld\n", (long long)((int)(3.27675e4)));
    printf("%lld\n", (long long)((int)(-3.27685e4)));
    printf("%lld\n", (long long)((int)(6.55355e4)));
    printf("%lld\n", (long long)((int)(2.147483647e9)));
    printf("%lld\n", (long long)((int)(-2.147483648e9)));
    return 0;
}
