// short out to a float and back, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((short)(float)((short)(-32767 - 1))));
    printf("%lld\n", (long long)((short)(float)((short)(-255))));
    printf("%lld\n", (long long)((short)(float)((short)(-8))));
    printf("%lld\n", (long long)((short)(float)((short)(-2))));
    printf("%lld\n", (long long)((short)(float)((short)(-1))));
    printf("%lld\n", (long long)((short)(float)((short)0)));
    printf("%lld\n", (long long)((short)(float)((short)1)));
    printf("%lld\n", (long long)((short)(float)((short)2)));
    printf("%lld\n", (long long)((short)(float)((short)3)));
    printf("%lld\n", (long long)((short)(float)((short)7)));
    printf("%lld\n", (long long)((short)(float)((short)8)));
    printf("%lld\n", (long long)((short)(float)((short)16)));
    printf("%lld\n", (long long)((short)(float)((short)255)));
    printf("%lld\n", (long long)((short)(float)((short)256)));
    printf("%lld\n", (long long)((short)(float)((short)16383)));
    printf("%lld\n", (long long)((short)(float)((short)32767)));
    return 0;
}
