// unsigned char out to a float and back, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)0u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)1u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)2u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)3u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)7u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)8u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)16u)));
    printf("%llu\n", (unsigned long long)((unsigned char)(float)((unsigned char)255u)));
    return 0;
}
