// unsigned char out to a double and back, with the value read from memory
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char u8_double_in[8] = { 0u, 1u, 2u, 3u, 7u, 8u, 16u, 255u };

int main(void) {

    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[0])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[1])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[2])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[3])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[4])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[5])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[6])));
    printf("%llu\n", (unsigned long long)((unsigned char)(double)(u8_double_in[7])));
    return 0;
}
