// a double truncated into unsigned short, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%llu\n", (unsigned long long)((unsigned short)(0e0)));
    printf("%llu\n", (unsigned long long)((unsigned short)(-0e0)));
    printf("%llu\n", (unsigned long long)((unsigned short)(5e-1)));
    printf("%llu\n", (unsigned long long)((unsigned short)(-5e-1)));
    printf("%llu\n", (unsigned long long)((unsigned short)(1e0)));
    printf("%llu\n", (unsigned long long)((unsigned short)(1.5e0)));
    printf("%llu\n", (unsigned long long)((unsigned short)(3.75e0)));
    printf("%llu\n", (unsigned long long)((unsigned short)(1.275e2)));
    printf("%llu\n", (unsigned long long)((unsigned short)(2.5575e2)));
    printf("%llu\n", (unsigned long long)((unsigned short)(3.27675e4)));
    printf("%llu\n", (unsigned long long)((unsigned short)(6.55355e4)));
    return 0;
}
