// short out to a double and back, with the value written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)((short)(double)((short)(-32767 - 1))));
    printf("%lld\n", (long long)((short)(double)((short)(-255))));
    printf("%lld\n", (long long)((short)(double)((short)(-8))));
    printf("%lld\n", (long long)((short)(double)((short)(-2))));
    printf("%lld\n", (long long)((short)(double)((short)(-1))));
    printf("%lld\n", (long long)((short)(double)((short)0)));
    printf("%lld\n", (long long)((short)(double)((short)1)));
    printf("%lld\n", (long long)((short)(double)((short)2)));
    printf("%lld\n", (long long)((short)(double)((short)3)));
    printf("%lld\n", (long long)((short)(double)((short)7)));
    printf("%lld\n", (long long)((short)(double)((short)8)));
    printf("%lld\n", (long long)((short)(double)((short)16)));
    printf("%lld\n", (long long)((short)(double)((short)255)));
    printf("%lld\n", (long long)((short)(double)((short)256)));
    printf("%lld\n", (long long)((short)(double)((short)16383)));
    printf("%lld\n", (long long)((short)(double)((short)32767)));
    return 0;
}
