// a unsigned int loop that is already in all five shapes
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int bound_in = 8;

int main(void) {
    int bound = bound_in;

    unsigned int total = 0;
    int i = 0;
    if (0 < bound) {
        do {
            total += (unsigned int)i;
            i++;
        } while (i < bound);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
