// a int loop two blocks outside it jump into
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int which_in = 1;

int main(void) {
    int which = which_in;

    int total = 0;
    int i = 0;
    if (which) goto top;
    total += 1;
    goto top;
    top:
    while (i < 8) {
        total += (int)i;
        i++;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
