// a unsigned int loop whose header defines a value read after the loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int bound_in = 20;

int main(void) {
    int bound = bound_in;

    unsigned int total = 0;
    int i = 0;
    int last = 0;
    while ((last = i * 3) < bound) {
        total += (unsigned int)last;
        i++;
    }

    printf("%lld\n", (long long)(last));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
