// a unsigned int loop whose entry test the ranges cannot settle
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int bound_in = 9u;

int main(void) {
    unsigned int bound = bound_in;

    unsigned int total = 0;
    unsigned i = 0;
    while (i < bound) {
        total += (unsigned int)i;
        i++;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
