// a int loop whose counter is read twice afterwards
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int bound_in = 10;

int main(void) {
    int bound = bound_in;

    int total = 0;
    int i;
    for (i = 0; i < bound; i++) {
        total += (int)i;
    }

    printf("%lld\n", (long long)(i));
    printf("%lld\n", (long long)(i * 2));

    printf("%lld\n", (long long)(total));
    return 0;
}
