// a long long loop the ranges can prove never runs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 13u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned bound = seed % 4u;
    long long total = 0;
    unsigned i = 8;
    while (i < bound) {
        total += (long long)i;
        i++;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
