// a plain unsigned int `while` loop, which should end up a `do`
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int bound_in = 10;

int main(void) {
    int bound = bound_in;

    unsigned int total = 0;
    int i = 0;
    while (i < bound) {
        total += (unsigned int)i;
        i++;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
