// a unsigned long long loop the ranges can prove runs at least once
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 13u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned bound = seed % 8u + 1u;
    unsigned long long total = 0;
    unsigned i = 0;
    while (i < bound) {
        total += (unsigned long long)i;
        i++;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
