// the masked-four shape dispatched on unpredictable values
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int masked_four(int value) {
    switch (value & 3) {
    case 0: return 7;
    case 1: return 3;
    case 2: return 91;
    case 3: return 4;
    default: return 0;
    }
}
static volatile int seed_in = 7;
static volatile int count_in = 10240000;

int main(void) {
    int seed = seed_in;
    int count = count_in;

    int stream[4096];
    unsigned int state = (unsigned int)seed;
    for (int at = 0; at < 4096; at++) {
        state = state * 1103515245u + 12345u;
        stream[at] = (int)((state >> 16) % 20u);
    }

    long long total = 0;
    for (int at = 0; at < count; at++) {
        total += masked_four(stream[at & 4095]);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
