// the constant-arms shape dispatched on unpredictable values
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int constant_arms(int value) {
    switch (value) {
    case 9: return 1;
    case 10: return 1;
    case 11: return 1;
    case 12: return 1;
    case 13: return 1;
    case 14: return 1;
    case 15: return 1;
    case 16: return 1;
    default: return 0;
    }
}
static volatile int seed_in = 7;
static volatile int count_in = 10240000;

int main(void) {
    int seed = seed_in;
    int count = count_in;

    int stream[4096];
    unsigned int state = (unsigned int)seed;
    for (int at = 0; at < 4096; at++) {
        state = state * 1103515245u + 12345u;
        stream[at] = 9 + (int)((state >> 16) % 10u);
    }

    long long total = 0;
    for (int at = 0; at < count; at++) {
        total += constant_arms(stream[at & 4095]);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
