// a left half that is nearly always true, so the branch odds decide, written as a value
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    int hits = 0;
    for (int i = 0; i < 256; i++) {
        int v = data[i];
        int got = v < 250 && (v & 1) == 0;
        hits += got;
    }

    printf("%lld\n", (long long)(hits));
    return 0;
}
