// one unsigned int read and write, call-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int at_in = 3;
static volatile int back_in = 3;
static volatile int noise_count;
static void noise(void) {
    noise_count = noise_count + 1;
}
static void (*volatile jump)(void) = noise;

int main(void) {
    unsigned int seed = seed_in;
    int at = at_in;
    int back = back_in;

    unsigned int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned int)i;
    }
    unsigned int value = buffer[at];
    jump();
    buffer[at] = value + seed;
    unsigned int total = buffer[back];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
