// one int read and write, other-offset
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int at_in = 3;
static volatile int back_in = 3;

int main(void) {
    int seed = seed_in;
    int at = at_in;
    int back = back_in;

    int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (int)i;
    }
    buffer[at + 1] = buffer[at] + seed;
    int total = buffer[back] + buffer[back + 1];

    printf("%lld\n", (long long)(total));
    return 0;
}
