// one unsigned int read and write, two-readers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int at_in = 3;
static volatile int back_in = 3;

int main(void) {
    unsigned int seed = seed_in;
    int at = at_in;
    int back = back_in;

    unsigned int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned int)i;
    }
    unsigned int value = buffer[at];
    buffer[at] = value + seed;
    unsigned int total = buffer[back] + value;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
