// __builtin_clz over every bit position at 32 bits, with the argument written as a constant
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)1u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)2u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)4u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)8u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)16u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)32u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)64u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)128u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)256u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)512u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)1024u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)2048u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)4096u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)8192u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)16384u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)32768u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)65536u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)131072u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)262144u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)524288u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)1048576u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)2097152u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)4194304u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)8388608u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)16777216u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)33554432u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)67108864u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)134217728u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)268435456u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)536870912u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)1073741824u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)2147483648u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)4294967295u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)1431655765u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)2863311530u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)252645135u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)3u)));
    printf("%lld\n", (long long)(__builtin_clz((unsigned int)2147483649u)));
    return 0;
}
