// 4 independent unsigned long long chains of 8 steps
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 1ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long c0 = seed + (unsigned long long)0ull;
    unsigned long long c1 = seed + (unsigned long long)1ull;
    unsigned long long c2 = seed + (unsigned long long)2ull;
    unsigned long long c3 = seed + (unsigned long long)3ull;
    for (int i = 0; i < 4; i++) {
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
        c0 = c0 * (unsigned long long)3ull + (unsigned long long)1ull;
        c1 = c1 * (unsigned long long)3ull + (unsigned long long)1ull;
        c2 = c2 * (unsigned long long)3ull + (unsigned long long)1ull;
        c3 = c3 * (unsigned long long)3ull + (unsigned long long)1ull;
    }

    unsigned long long total = 0;
    total += c0;
    total += c1;
    total += c2;
    total += c3;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
