// a read-only memory access in a loop the compiler cannot unpick
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 1ull;
static volatile int start_in = 0;

int main(void) {
    unsigned long long seed = seed_in;
    int start = start_in;

    unsigned long long buffer[16];
    for (int i = 0; i < 16; i++) {
        buffer[i] = seed + (unsigned long long)i;
    }
    unsigned long long total = 0;
    for (int i = 0; i < 64; i++) {
        int at = (i * 7 + start) & 15;
        total = total * (unsigned long long)5ull + buffer[at] + buffer[(at + 3) & 15];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
