// 1 independent unsigned int chains of 32 steps
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 1u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int c0 = seed + (unsigned int)0u;
    for (int i = 0; i < 4; i++) {
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
        c0 = c0 * (unsigned int)3u + (unsigned int)1u;
    }

    unsigned int total = 0;
    total += c0;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
