// unsigned long long callee, writes what is read
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long table[4];
static unsigned long long watch[4];
static __attribute__((noinline)) unsigned long long scan(unsigned long long *in) {
    watch[1] = watch[1] + (unsigned long long)1ull;
    return in[0] + in[3];
}
static volatile unsigned long long seed_in = 6ull;

int main(void) {
    unsigned long long seed = seed_in;

    table[0] = seed;
    table[3] = seed + (unsigned long long)1ull;
    watch[1] = seed + (unsigned long long)2ull;
    watch[2] = seed + (unsigned long long)3ull;
    unsigned long long total = 0;
    for (int i = 0; i < 1000; i++) {
        total += scan(table);
        total += watch[1] + watch[2];
    }

    printf("%llu\n", (unsigned long long)(total));
    printf("%llu\n", (unsigned long long)(table[0]));
    printf("%llu\n", (unsigned long long)(watch[1]));
    return 0;
}
