// unsigned int callee, writes one array
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int left[4];
static unsigned int right[4];
static __attribute__((noinline)) void bump(unsigned int *out, unsigned int *in) {
    out[0] = out[0] + in[1];
    out[2] = out[2] + (unsigned int)1u;
}
static volatile unsigned int seed_in = 6u;

int main(void) {
    unsigned int seed = seed_in;

    left[0] = seed;
    right[1] = seed + (unsigned int)1u;
    right[2] = seed + (unsigned int)2u;
    right[3] = seed + (unsigned int)3u;
    unsigned int total = 0;
    for (int i = 0; i < 1000; i++) {
        bump(left, right);
        total += right[2] + right[3];
    }

    printf("%llu\n", (unsigned long long)(total));
    printf("%llu\n", (unsigned long long)(left[0]));
    printf("%llu\n", (unsigned long long)(left[2]));
    return 0;
}
