// long long callee, writes both arrays
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long left[4];
static long long right[4];
static __attribute__((noinline)) void bump(long long *out, long long *in) {
    out[0] = out[0] + in[1];
    in[2] = in[2] + (long long)1ll;
}
static volatile long long seed_in = 6ll;

int main(void) {
    long long seed = seed_in;

    left[0] = seed;
    right[1] = seed + (long long)1ll;
    right[2] = seed + (long long)2ll;
    right[3] = seed + (long long)3ll;
    long long total = 0;
    for (int i = 0; i < 1000; i++) {
        bump(left, right);
        total += right[2] + right[3];
    }

    printf("%lld\n", (long long)(total));
    printf("%lld\n", (long long)(left[0]));
    printf("%lld\n", (long long)(right[2]));
    return 0;
}
