// int callee, writes both arrays
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int left[4];
static int right[4];
static __attribute__((noinline)) void bump(int *out, int *in) {
    out[0] = out[0] + in[1];
    in[2] = in[2] + (int)1;
}
static volatile int seed_in = 6;

int main(void) {
    int seed = seed_in;

    left[0] = seed;
    right[1] = seed + (int)1;
    right[2] = seed + (int)2;
    right[3] = seed + (int)3;
    int total = 0;
    for (int i = 0; i < 1000; i++) {
        bump(left, right);
        total += right[2] + right[3];
    }

    printf("%lld\n", (long long)(total));
    printf("%lld\n", (long long)(left[0]));
    printf("%lld\n", (long long)(right[2]));
    return 0;
}
