// unsigned int callee, lends a local
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int anchor;
static __attribute__((noinline)) unsigned int sum_of(unsigned int *of) {
    return of[0] + of[1];
}
static __attribute__((noinline)) void tick(void) {
    anchor = anchor + (unsigned int)1u;
}
static volatile unsigned int seed_in = 6u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int local[3];
    local[0] = seed;
    local[1] = seed + (unsigned int)1u;
    local[2] = seed + (unsigned int)2u;
    unsigned int total = 0;
    for (int i = 0; i < 1000; i++) {
        total += sum_of(local);
        tick();
        total += local[0] + local[2];
    }

    printf("%llu\n", (unsigned long long)(total));
    printf("%llu\n", (unsigned long long)(local[0]));
    printf("%llu\n", (unsigned long long)(anchor));
    return 0;
}
