// 12 values live across setjmp in the loop shape, with a quiet first arm
// Generated by rucc-corpus. Edit the generator, not this file.

#include <setjmp.h>

int printf(const char *, ...);

static jmp_buf *exception_stack;
static volatile int depth;
static volatile long long busy_total;
static int cells[64];
static volatile long long seen[12];
static void raise_error(int code) {
    longjmp(*exception_stack, code);
}
static void work(int code) {
    depth = depth + 1;
    if (code != 0) {
        raise_error(code);
    }
}
static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;
    for (int i = 0; i < 64; i++) {
        cells[i] = i * 7 + 1;
    }

    int v0 = seed * 2 + 0;
    long v1 = seed * 1001L - 1;
    volatile double v2 = seed + 0.25 * 3;
    int *v3 = &cells[(seed + 3) % 32];
    int v4 = seed * 6 + 4;
    volatile long v5 = seed * 1005L - 5;
    double v6 = seed + 0.25 * 7;
    int *v7 = &cells[(seed + 7) % 32];
    volatile int v8 = seed * 10 + 8;
    long v9 = seed * 1009L - 9;
    double v10 = seed + 0.25 * 11;
    int *volatile v11 = &cells[(seed + 11) % 32];
    volatile int caught = 0;
    volatile int progress = 0;

    for (int round = 0; round < 4; round++) {
        jmp_buf *save_stack = exception_stack;
        jmp_buf local_buf;
        if (setjmp(local_buf) == 0) {
            exception_stack = &local_buf;
            progress = progress + 1;
            v2 = v2 + 1.5;
            v5 = v5 * 2;
            v8 = v8 + 108;
            v11 = v11 + 1;
            work(round % 2);
        } else {
            exception_stack = save_stack;
            caught = caught + 1;
            seen[0] = seen[0] + v0;
            seen[1] = seen[1] + v1;
            seen[2] = seen[2] + (long long)(v2 * 4.0);
            seen[3] = seen[3] + *v3;
            seen[4] = seen[4] + v4;
            seen[5] = seen[5] + v5;
            seen[6] = seen[6] + (long long)(v6 * 4.0);
            seen[7] = seen[7] + *v7;
            seen[8] = seen[8] + v8;
            seen[9] = seen[9] + v9;
            seen[10] = seen[10] + (long long)(v10 * 4.0);
            seen[11] = seen[11] + *v11;
        }
        exception_stack = save_stack;
    }

    printf("%lld\n", (long long)(seen[0]));
    printf("%lld\n", (long long)(seen[1]));
    printf("%lld\n", (long long)(seen[2]));
    printf("%lld\n", (long long)(seen[3]));
    printf("%lld\n", (long long)(seen[4]));
    printf("%lld\n", (long long)(seen[5]));
    printf("%lld\n", (long long)(seen[6]));
    printf("%lld\n", (long long)(seen[7]));
    printf("%lld\n", (long long)(seen[8]));
    printf("%lld\n", (long long)(seen[9]));
    printf("%lld\n", (long long)(seen[10]));
    printf("%lld\n", (long long)(seen[11]));
    printf("%lld\n", (long long)(caught));
    printf("%lld\n", (long long)(progress));
    printf("%lld\n", (long long)(depth));
    return 0;
}
