// 30 values live across sigsetjmp in the loop shape, with a quiet first arm
// Generated by rucc-corpus. Edit the generator, not this file.

#define _POSIX_C_SOURCE 200809L

#include <setjmp.h>

int printf(const char *, ...);

static sigjmp_buf *exception_stack;
static volatile int depth;
static volatile long long busy_total;
static int cells[64];
static volatile long long seen[30];
static void raise_error(int code) {
    siglongjmp(*exception_stack, code);
}
static void work(int code) {
    depth = depth + 1;
    if (code != 0) {
        raise_error(code);
    }
}
static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;
    for (int i = 0; i < 64; i++) {
        cells[i] = i * 7 + 1;
    }

    int v0 = seed * 2 + 0;
    long v1 = seed * 1001L - 1;
    volatile double v2 = seed + 0.25 * 3;
    int *v3 = &cells[(seed + 3) % 32];
    int v4 = seed * 6 + 4;
    volatile long v5 = seed * 1005L - 5;
    double v6 = seed + 0.25 * 7;
    int *v7 = &cells[(seed + 7) % 32];
    volatile int v8 = seed * 10 + 8;
    long v9 = seed * 1009L - 9;
    double v10 = seed + 0.25 * 11;
    int *volatile v11 = &cells[(seed + 11) % 32];
    int v12 = seed * 14 + 12;
    long v13 = seed * 1013L - 13;
    volatile double v14 = seed + 0.25 * 15;
    int *v15 = &cells[(seed + 15) % 32];
    int v16 = seed * 18 + 16;
    volatile long v17 = seed * 1017L - 17;
    double v18 = seed + 0.25 * 19;
    int *v19 = &cells[(seed + 19) % 32];
    volatile int v20 = seed * 22 + 20;
    long v21 = seed * 1021L - 21;
    double v22 = seed + 0.25 * 23;
    int *volatile v23 = &cells[(seed + 23) % 32];
    int v24 = seed * 26 + 24;
    long v25 = seed * 1025L - 25;
    volatile double v26 = seed + 0.25 * 27;
    int *v27 = &cells[(seed + 27) % 32];
    int v28 = seed * 30 + 28;
    volatile long v29 = seed * 1029L - 29;
    volatile int caught = 0;
    volatile int progress = 0;

    for (int round = 0; round < 4; round++) {
        sigjmp_buf *save_stack = exception_stack;
        sigjmp_buf local_buf;
        if (sigsetjmp(local_buf, 0) == 0) {
            exception_stack = &local_buf;
            progress = progress + 1;
            v2 = v2 + 1.5;
            v5 = v5 * 2;
            v8 = v8 + 108;
            v11 = v11 + 1;
            v14 = v14 + 1.5;
            v17 = v17 * 2;
            v20 = v20 + 120;
            v23 = v23 + 1;
            v26 = v26 + 1.5;
            v29 = v29 * 2;
            work(round % 2);
        } else {
            exception_stack = save_stack;
            caught = caught + 1;
            seen[0] = seen[0] + v0;
            seen[1] = seen[1] + v1;
            seen[2] = seen[2] + (long long)(v2 * 4.0);
            seen[3] = seen[3] + *v3;
            seen[4] = seen[4] + v4;
            seen[5] = seen[5] + v5;
            seen[6] = seen[6] + (long long)(v6 * 4.0);
            seen[7] = seen[7] + *v7;
            seen[8] = seen[8] + v8;
            seen[9] = seen[9] + v9;
            seen[10] = seen[10] + (long long)(v10 * 4.0);
            seen[11] = seen[11] + *v11;
            seen[12] = seen[12] + v12;
            seen[13] = seen[13] + v13;
            seen[14] = seen[14] + (long long)(v14 * 4.0);
            seen[15] = seen[15] + *v15;
            seen[16] = seen[16] + v16;
            seen[17] = seen[17] + v17;
            seen[18] = seen[18] + (long long)(v18 * 4.0);
            seen[19] = seen[19] + *v19;
            seen[20] = seen[20] + v20;
            seen[21] = seen[21] + v21;
            seen[22] = seen[22] + (long long)(v22 * 4.0);
            seen[23] = seen[23] + *v23;
            seen[24] = seen[24] + v24;
            seen[25] = seen[25] + v25;
            seen[26] = seen[26] + (long long)(v26 * 4.0);
            seen[27] = seen[27] + *v27;
            seen[28] = seen[28] + v28;
            seen[29] = seen[29] + v29;
        }
        exception_stack = save_stack;
    }

    printf("%lld\n", (long long)(seen[0]));
    printf("%lld\n", (long long)(seen[1]));
    printf("%lld\n", (long long)(seen[2]));
    printf("%lld\n", (long long)(seen[3]));
    printf("%lld\n", (long long)(seen[4]));
    printf("%lld\n", (long long)(seen[5]));
    printf("%lld\n", (long long)(seen[6]));
    printf("%lld\n", (long long)(seen[7]));
    printf("%lld\n", (long long)(seen[8]));
    printf("%lld\n", (long long)(seen[9]));
    printf("%lld\n", (long long)(seen[10]));
    printf("%lld\n", (long long)(seen[11]));
    printf("%lld\n", (long long)(seen[12]));
    printf("%lld\n", (long long)(seen[13]));
    printf("%lld\n", (long long)(seen[14]));
    printf("%lld\n", (long long)(seen[15]));
    printf("%lld\n", (long long)(seen[16]));
    printf("%lld\n", (long long)(seen[17]));
    printf("%lld\n", (long long)(seen[18]));
    printf("%lld\n", (long long)(seen[19]));
    printf("%lld\n", (long long)(seen[20]));
    printf("%lld\n", (long long)(seen[21]));
    printf("%lld\n", (long long)(seen[22]));
    printf("%lld\n", (long long)(seen[23]));
    printf("%lld\n", (long long)(seen[24]));
    printf("%lld\n", (long long)(seen[25]));
    printf("%lld\n", (long long)(seen[26]));
    printf("%lld\n", (long long)(seen[27]));
    printf("%lld\n", (long long)(seen[28]));
    printf("%lld\n", (long long)(seen[29]));
    printf("%lld\n", (long long)(caught));
    printf("%lld\n", (long long)(progress));
    printf("%lld\n", (long long)(depth));
    return 0;
}
