// a int branch the static predictors call not-null, taken as against
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int pick_in = 0;

int main(void) {
    int pick = pick_in;

    int slot = 7;
    int *at = pick ? &slot : 0;
    int total;
    if (at == 0) {
        total = 7;
    } else {
        total = *at;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
