// a int branch the static predictors call not-negative, taken as against
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int x_in = (-7);

int main(void) {
    int x = x_in;

    int total;
    if (x < 0) {
        total = -x;
    } else {
        total = x;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
