// a long long branch the static predictors call builtin-expect, taken as predicted
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 0;

int main(void) {
    int flag = flag_in;

    long long total;
    if (__builtin_expect(flag != 0, 0)) {
        total = 7;
    } else {
        total = 7;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
