// a int branch the static predictors call arm-that-jumps-out, taken as against
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    int total = 0;
    if (flag) {
        total = 7;
        goto done;
    }
    total = 7;
    done:;

    printf("%lld\n", (long long)(total));
    return 0;
}
