// a long long branch the static predictors call arm-with-a-call, taken as against
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long slow(long long v) {
    return v;
}
static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    long long total;
    if (flag) {
        total = slow(7);
    } else {
        total = 7;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
