// a int branch the static predictors call loop-back-edge, taken as against
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int rounds_in = 1;

int main(void) {
    int rounds = rounds_in;

    int total = 0;
    for (int i = 0; i < rounds; i++) {
        total = total + 1;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
