//! Optimizations that cannot happen until the compiler has been given more than one file.
//!
//! Every other facet in the corpus is a single translation unit, and that is deliberate. A
//! program the compiler saw all of at once is a program where a wrong answer is about code
//! generation and nothing else, and keeping the corpus that way is most of what makes a failing
//! case worth reading. This facet is the exception, because there is a whole class of
//! transformations that only exist at the boundary between two files. A compiler can inline
//! across one, propagate a constant across one, devirtualize across one and drop a function
//! nothing calls across one, and it can only do any of it once somebody has handed it both
//! files at the same time. That is what `-flto` is.
//!
//! # Why every shape is generated twice
//!
//! Each shape here is emitted as a pair. One is compiled and linked the ordinary way, one file
//! at a time, and one is built with `-flto`. Both are the same program and both have to print
//! the same answer.
//!
//! The pair is the point. A single `-flto` case that passes says the compiler accepted a flag
//! and produced a working program, which is worth knowing and is not what the facet is about.
//! The pair says that turning whole program optimization on did not change the meaning of the
//! program, which is the property that actually breaks in practice, and the two rows sit next
//! to each other in the report so the reader can see which half moved. The same pair carries
//! the size numbers, so what LTO bought on a shape written to reward it is a subtraction the
//! report can do rather than a claim anybody has to take on trust.
//!
//! # How these cases stay target independent
//!
//! The same way the rest of the corpus does. Nothing prints a pointer, nothing prints a size,
//! every value is small enough to be exact in an `int` on any target C allows, and the answer
//! is worked out here in Rust before any compiler sees the program. Linking does not change any
//! of that. What it changes is how many files the compiler was holding when it decided.

use crate::Sink;
use crate::emit::Program;
use crate::lang::Ty;
use corpus_model::{Axes, Case, Dialect, Expect, Facet, Unit};

/// The two ways each shape is built.
///
/// The name on the left is the axis point, so a report row says which of the pair it is, and the
/// flag on the right is what the case is compiled with over and above the optimization level.
const LINKING: &[(&str, &str)] = &[("separate", ""), ("lto", "-flto")];

/// Emits every shape, twice each.
pub(crate) fn generate(sink: &mut Sink<'_>) {
    if !sink.wants(Facet::LinkTimeOptimization) {
        return;
    }
    a_call_crosses(sink);
    inlining_crosses(sink);
    a_constant_crosses(sink);
    a_global_crosses(sink);
    const_data_crosses(sink);
    nothing_calls_it(sink);
    a_chain_of_three_units(sink);
    a_static_in_each_unit(sink);
    a_function_pointer_crosses(sink);
    a_side_effect_must_survive(sink);
}

/// One translation unit with no `main` in it, written the way the generated ones are.
fn unit(name: &str, purpose: &str, body: &str) -> Unit {
    Unit::new(
        name,
        format!(
            "// {purpose}\n// Generated by rucc-corpus. Edit the generator, not this file.\n\n{body}"
        ),
    )
}

/// Emits one shape as a pair of cases, one linked the ordinary way and one with `-flto`.
fn pair(sink: &mut Sink<'_>, shape: &str, program: &Program, units: &[Unit]) {
    for (point, flag) in LINKING {
        let (source, expected) = program.clone().finish();
        let flags = if flag.is_empty() { Vec::new() } else { vec![(*flag).to_owned()] };
        sink.push_case(Case::linked(
            Facet::LinkTimeOptimization,
            Axes::of([("shape", shape), ("linking", *point)]),
            Dialect::C17,
            source,
            units.to_vec(),
            flags,
            Expect::Output(expected),
        ));
    }
}

/// A call that lands in the other file.
///
/// The floor of the facet. Nothing here can be optimized in an interesting way and that is why
/// it is first: a compiler that fails this one has not got a linking problem in one of the
/// shapes below, it has a linking problem, and the report should say which of the two it is.
fn a_call_crosses(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "The function the main unit calls but cannot see the body of.",
        "int corpus_add(int a, int b)\n{\n    return a + b;\n}\n",
    );

    let mut program = Program::new("A call whose callee is defined in another translation unit.");
    program.top("int corpus_add(int, int);");
    program.input(Ty::I32, "a", 17);
    program.input(Ty::I32, "b", 25);
    program.check(Ty::I32, "corpus_add(a, b)", 42);
    program.check(Ty::I32, "corpus_add(3, 4)", 7);

    pair(sink, "a-call-crosses", &program, &[helper]);
}

/// A body small enough to be worth pulling across the boundary.
///
/// The one call in the loop is the whole cost of the program, so a compiler that can see the
/// body has something to do with it and a compiler that cannot has a call per iteration. Both
/// have to print ninety.
fn inlining_crosses(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "A body small enough that seeing it across the file boundary is worth something.",
        "int corpus_double(int x)\n{\n    return x + x;\n}\n",
    );

    let mut program = Program::new("A tiny callee in another unit, called in a loop.");
    program.top("int corpus_double(int);");
    program.input(Ty::I32, "trips", 10);
    program.line("int total = 0;");
    program.line("for (int i = 0; i < trips; i++) {");
    program.line_at(1, "total += corpus_double(i);");
    program.line("}");
    program.check(Ty::I32, "total", 90);

    pair(sink, "inlining-crosses", &program, &[helper]);
}

/// A constant argument that only becomes a constant once both files are in hand.
///
/// The callee branches on its first argument and every call site passes a literal, so a
/// compiler holding both files can drop the branch and a compiler holding one cannot.
fn a_constant_crosses(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "A callee that branches on an argument every call site passes a literal for.",
        "int corpus_pick(int which, int a, int b)\n{\n    if (which) {\n        return a;\n    }\n    return b;\n}\n",
    );

    let mut program = Program::new("A literal argument that has to cross a file to be one.");
    program.top("int corpus_pick(int, int, int);");
    program.check(Ty::I32, "corpus_pick(1, 6, 9)", 6);
    program.check(Ty::I32, "corpus_pick(0, 6, 9)", 9);
    program.input(Ty::I32, "which", 1);
    program.check(Ty::I32, "corpus_pick(which, 6, 9)", 6);

    pair(sink, "a-constant-crosses", &program, &[helper]);
}

/// A variable one file defines and the other one writes to.
///
/// The order the two files see the writes in is the answer, so a pass that reordered them across
/// the boundary would be caught here rather than in whatever program it was eventually noticed
/// in.
fn a_global_crosses(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "A variable defined here, written from both files.",
        "int corpus_base = 100;\n\nint corpus_bump(void)\n{\n    corpus_base += 5;\n    return corpus_base;\n}\n",
    );

    let mut program = Program::new("A global defined in one unit and written from the other.");
    program.top("extern int corpus_base;");
    program.top("int corpus_bump(void);");
    program.check(Ty::I32, "corpus_bump()", 105);
    program.check(Ty::I32, "corpus_base", 105);
    program.line("corpus_base = 1;");
    program.check(Ty::I32, "corpus_bump()", 6);
    program.check(Ty::I32, "corpus_base", 6);

    pair(sink, "a-global-crosses", &program, &[helper]);
}

/// A table of constants in one file, read in the other.
///
/// Reading a value out of it is the sort of thing a compiler folds the moment it can see the
/// initializer, and it can only see the initializer with both files in hand.
fn const_data_crosses(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "A table of constants, defined here and read from the main unit.",
        "const int corpus_table[6] = { 2, 3, 5, 7, 11, 13 };\n",
    );

    let mut program = Program::new("A constant table defined in another unit.");
    program.top("extern const int corpus_table[6];");
    program.check(Ty::I32, "corpus_table[3]", 7);
    program.input(Ty::I32, "at", 5);
    program.check(Ty::I32, "corpus_table[at]", 13);
    program.line("int total = 0;");
    program.line("for (int i = 0; i < 6; i++) {");
    program.line_at(1, "total += corpus_table[i];");
    program.line("}");
    program.check(Ty::I32, "total", 41);

    pair(sink, "const-data-crosses", &program, &[helper]);
}

/// A function in the other file that nothing ever calls.
///
/// This one is not about the answer, which is the same either way. It is about the size, which
/// is the number the report keeps beside it. A compiler holding both files can see that nothing
/// reaches the second function and leave it out, and a compiler holding one file at a time has
/// to emit it in case the other file wanted it.
fn nothing_calls_it(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "One function the main unit calls and one it does not.",
        "int corpus_wanted(int x)\n{\n    return x + 8;\n}\n\nint corpus_unwanted(int x)\n{\n    int total = 0;\n    for (int i = 0; i < x; i++) {\n        total += i * i;\n    }\n    return total;\n}\n",
    );

    let mut program = Program::new("A function in the other unit that nothing reaches.");
    program.top("int corpus_wanted(int);");
    program.input(Ty::I32, "x", 34);
    program.check(Ty::I32, "corpus_wanted(x)", 42);

    pair(sink, "nothing-calls-it", &program, &[helper]);
}

/// Three files, and the answer only exists once all three are in hand.
///
/// A boundary a compiler crosses once is a different thing from a boundary it crosses twice,
/// because the second one is the one where the result of the first has to be carried across.
fn a_chain_of_three_units(sink: &mut Sink<'_>) {
    let bottom = unit(
        "bottom",
        "The end of the chain. It calls nothing.",
        "int corpus_bottom(int x)\n{\n    return x + 1;\n}\n",
    );
    let middle = unit(
        "middle",
        "The middle of the chain. It is called from the main unit and calls the bottom one.",
        "int corpus_bottom(int);\n\nint corpus_middle(int x)\n{\n    return corpus_bottom(x) * 2;\n}\n",
    );

    let mut program = Program::new("A call chain that runs through three translation units.");
    program.top("int corpus_middle(int);");
    program.input(Ty::I32, "x", 20);
    program.check(Ty::I32, "corpus_middle(x)", 42);
    program.check(Ty::I32, "corpus_middle(0)", 2);

    pair(sink, "a-chain-of-three-units", &program, &[bottom, middle]);
}

/// The same name in two files, and it is two objects.
///
/// A `static` at file scope has internal linkage, so these are two counters that happen to be
/// spelled the same and a compiler that merged them would be wrong. That is a mistake only a
/// compiler that has both files in front of it is in a position to make, which is exactly why
/// the case is here and not in a facet about storage.
fn a_static_in_each_unit(sink: &mut Sink<'_>) {
    let first = unit(
        "first",
        "A counter with internal linkage. The other unit has one spelled the same.",
        "static int corpus_count;\n\nint corpus_first_bump(void)\n{\n    corpus_count += 1;\n    return corpus_count;\n}\n",
    );
    let second = unit(
        "second",
        "A counter with internal linkage. The other unit has one spelled the same.",
        "static int corpus_count;\n\nint corpus_second_bump(void)\n{\n    corpus_count += 10;\n    return corpus_count;\n}\n",
    );

    let mut program =
        Program::new("Two units with a static of the same name, which is two objects.");
    program.top("int corpus_first_bump(void);");
    program.top("int corpus_second_bump(void);");
    program.check(Ty::I32, "corpus_first_bump()", 1);
    program.check(Ty::I32, "corpus_second_bump()", 10);
    program.check(Ty::I32, "corpus_first_bump()", 2);
    program.check(Ty::I32, "corpus_second_bump()", 20);
    program.check(Ty::I32, "corpus_first_bump()", 3);

    pair(sink, "a-static-in-each-unit", &program, &[first, second]);
}

/// A call through a pointer whose target is in the other file.
///
/// The pointer has exactly one value the whole time it exists, so a compiler that can see across
/// the boundary can turn the indirect call into a direct one and then into no call at all. It
/// still has to arrive at the same number.
fn a_function_pointer_crosses(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "The two functions the main unit takes the address of.",
        "int corpus_triple(int x)\n{\n    return x * 3;\n}\n\nint corpus_negate(int x)\n{\n    return -x;\n}\n",
    );

    let mut program = Program::new("An indirect call whose target lives in another unit.");
    program.top("int corpus_triple(int);");
    program.top("int corpus_negate(int);");
    program.input(Ty::I32, "x", 14);
    program.line("int (*call)(int) = corpus_triple;");
    program.check(Ty::I32, "call(x)", 42);
    program.line("call = corpus_negate;");
    program.check(Ty::I32, "call(x)", -14);

    pair(sink, "a-function-pointer-crosses", &program, &[helper]);
}

/// A store the other file made that nothing here may throw away.
///
/// The object is `volatile` and it is written once per turn of the loop, so every one of those
/// writes has to happen and in that order. Whole program optimization is the setting under which
/// a compiler has the most reason to think it can see all the readers of an object, and this is
/// the case that says it still may not act on that.
fn a_side_effect_must_survive(sink: &mut Sink<'_>) {
    let helper = unit(
        "helper",
        "A volatile object written from one function here and read by another.",
        "static volatile int corpus_seen;\n\nvoid corpus_touch(int x)\n{\n    corpus_seen = x;\n}\n\nint corpus_read(void)\n{\n    return corpus_seen;\n}\n",
    );

    let mut program = Program::new("A volatile store in another unit, which has to survive.");
    program.top("void corpus_touch(int);");
    program.top("int corpus_read(void);");
    program.input(Ty::I32, "trips", 7);
    program.line("for (int i = 0; i < trips; i++) {");
    program.line_at(1, "corpus_touch(i * 6);");
    program.line("}");
    program.check(Ty::I32, "corpus_read()", 36);
    program.line("corpus_touch(42);");
    program.check(Ty::I32, "corpus_read()", 42);

    pair(sink, "a-side-effect-must-survive", &program, &[helper]);
}

#[cfg(test)]
mod tests {
    use crate::{Options, generate};
    use corpus_model::{Case, Facet};
    use std::collections::BTreeSet;

    fn cases() -> Vec<Case> {
        generate(&Options::all().only(&[Facet::LinkTimeOptimization])).unwrap().cases
    }

    #[test]
    fn every_case_here_is_more_than_one_file() {
        for case in cases() {
            assert!(!case.units.is_empty(), "{} is a single file", case.id);
        }
    }

    #[test]
    fn no_unit_beside_the_main_one_has_a_main_in_it() {
        for case in cases() {
            for unit in &case.units {
                assert!(
                    !unit.source.contains("main("),
                    "{} has a second main in {}",
                    case.id,
                    unit.name
                );
                assert!(
                    unit.source.ends_with('\n'),
                    "{} has no final newline in {}",
                    case.id,
                    unit.name
                );
            }
        }
    }

    #[test]
    fn every_shape_is_generated_both_ways_and_the_pair_expects_the_same_answer() {
        let mut by_shape: std::collections::BTreeMap<String, Vec<Case>> =
            std::collections::BTreeMap::new();
        for case in cases() {
            let shape = case.axes.get("shape").unwrap_or_default().to_owned();
            by_shape.entry(shape).or_default().push(case);
        }
        assert!(by_shape.len() >= 10, "only {} shapes", by_shape.len());
        for (shape, pair) in by_shape {
            assert_eq!(pair.len(), 2, "{shape} was not generated twice");
            let points: BTreeSet<&str> =
                pair.iter().filter_map(|case| case.axes.get("linking")).collect();
            assert_eq!(points, ["lto", "separate"].into_iter().collect::<BTreeSet<&str>>());
            assert_eq!(pair[0].expect, pair[1].expect, "{shape} expects two different answers");
            assert_eq!(pair[0].source, pair[1].source, "{shape} is two different programs");
        }
    }

    #[test]
    fn only_the_lto_half_of_each_pair_carries_the_flag() {
        for case in cases() {
            match case.axes.get("linking") {
                Some("lto") => assert_eq!(case.flags, ["-flto"], "{} is missing the flag", case.id),
                _ => assert!(case.flags.is_empty(), "{} carries a flag it should not", case.id),
            }
        }
    }

    #[test]
    fn the_two_halves_of_a_pair_hash_differently() {
        // The two are the same source built two ways, so the only thing keeping them apart in the
        // record cache is that the flag is part of what a case digests to. Without that the second
        // build would be handed the first one's record and the facet would pass by never running.
        let all = cases();
        let digests: BTreeSet<String> = all.iter().map(Case::digest).collect();
        assert_eq!(digests.len(), all.len());
        let ids: BTreeSet<&str> = all.iter().map(|case| case.id.as_str()).collect();
        assert_eq!(ids.len(), all.len());
    }
}
