// a switch-constant whose dead arm must not run
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 10;

int main(void) {
    int seed = seed_in;

    int answer = 0;
    switch (2) {
        case 1: answer = seed * 100; break;
        case 2: answer = seed + 1; break;
        default: answer = seed * 200; break;
    }

    printf("%lld\n", (long long)(answer));
    return 0;
}
