// a if-false whose dead arm must not run
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 10;

int main(void) {
    int seed = seed_in;

    int answer = 0;
    if (0) {
        answer = seed * 100;
    } else {
        answer = seed + 1;
    }

    printf("%lld\n", (long long)(answer));
    return 0;
}
