// a unsigned int return value no call reads, returns-a-pointer
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int table[4] = { 0, 0, 0, 0 };
static unsigned int *slot(unsigned int at) {
    table[at] = (unsigned int)(table[at] + 1);
    return &table[at];
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    slot((unsigned int)(seed - 2));
    slot((unsigned int)(seed - 2));

    printf("%llu\n", (unsigned long long)(table[1]));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
