// a long long return value no call reads, one-call-reads
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long seen = (long long)0ll;
static long long note(long long value) {
    seen = (long long)(seen + value);
    return (long long)(value * value);
}
static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long total = 0;
    total += note(seed);
    note((long long)(seed + 1));

    printf("%lld\n", (long long)(seen));

    printf("%lld\n", (long long)(total));
    return 0;
}
