// a unsigned int return value no call reads, through-a-helper
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int seen = (unsigned int)0u;
static unsigned int note(unsigned int value) {
    seen = (unsigned int)(seen + value);
    return (unsigned int)(value * value);
}
static unsigned int outer(unsigned int value) {
    return note(value);
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    outer(seed);
    outer((unsigned int)(seed + 1));

    printf("%llu\n", (unsigned long long)(seen));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
