// a unsigned int return value no call reads, read-in-a-condition
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int seen = (unsigned int)0u;
static unsigned int note(unsigned int value) {
    seen = (unsigned int)(seen + value);
    return (unsigned int)(value * value);
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    if (note(seed)) {
        total += (unsigned int)5u;
    }
    note((unsigned int)(seed + 1));

    printf("%llu\n", (unsigned long long)(seen));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
