// a int return value no call reads, read-in-a-condition
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int seen = (int)0;
static int note(int value) {
    seen = (int)(seen + value);
    return (int)(value * value);
}
static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;

    int total = 0;
    if (note(seed)) {
        total += (int)5;
    }
    note((int)(seed + 1));

    printf("%lld\n", (long long)(seen));

    printf("%lld\n", (long long)(total));
    return 0;
}
