// a unsigned long long return value no call reads, one-call-reads
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long seen = (unsigned long long)0ull;
static unsigned long long note(unsigned long long value) {
    seen = (unsigned long long)(seen + value);
    return (unsigned long long)(value * value);
}
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    total += note(seed);
    note((unsigned long long)(seed + 1));

    printf("%llu\n", (unsigned long long)(seen));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
