// a chain of 32 int copies
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int start_in = 12;

int main(void) {
    int start = start_in;

    int c0 = start;
    int c1 = c0;
    int c2 = c1;
    int c3 = c2;
    int c4 = c3;
    int c5 = c4;
    int c6 = c5;
    int c7 = c6;
    int c8 = c7;
    int c9 = c8;
    int c10 = c9;
    int c11 = c10;
    int c12 = c11;
    int c13 = c12;
    int c14 = c13;
    int c15 = c14;
    int c16 = c15;
    int c17 = c16;
    int c18 = c17;
    int c19 = c18;
    int c20 = c19;
    int c21 = c20;
    int c22 = c21;
    int c23 = c22;
    int c24 = c23;
    int c25 = c24;
    int c26 = c25;
    int c27 = c26;
    int c28 = c27;
    int c29 = c28;
    int c30 = c29;
    int c31 = c30;

    printf("%lld\n", (long long)(c31));
    return 0;
}
