// a chain of 32 unsigned int copies
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int start_in = 12u;

int main(void) {
    unsigned int start = start_in;

    unsigned int c0 = start;
    unsigned int c1 = c0;
    unsigned int c2 = c1;
    unsigned int c3 = c2;
    unsigned int c4 = c3;
    unsigned int c5 = c4;
    unsigned int c6 = c5;
    unsigned int c7 = c6;
    unsigned int c8 = c7;
    unsigned int c9 = c8;
    unsigned int c10 = c9;
    unsigned int c11 = c10;
    unsigned int c12 = c11;
    unsigned int c13 = c12;
    unsigned int c14 = c13;
    unsigned int c15 = c14;
    unsigned int c16 = c15;
    unsigned int c17 = c16;
    unsigned int c18 = c17;
    unsigned int c19 = c18;
    unsigned int c20 = c19;
    unsigned int c21 = c20;
    unsigned int c22 = c21;
    unsigned int c23 = c22;
    unsigned int c24 = c23;
    unsigned int c25 = c24;
    unsigned int c26 = c25;
    unsigned int c27 = c26;
    unsigned int c28 = c27;
    unsigned int c29 = c28;
    unsigned int c30 = c29;
    unsigned int c31 = c30;

    printf("%llu\n", (unsigned long long)(c31));
    return 0;
}
