// a chain of 8 unsigned int copies
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int start_in = 12u;

int main(void) {
    unsigned int start = start_in;

    unsigned int c0 = start;
    unsigned int c1 = c0;
    unsigned int c2 = c1;
    unsigned int c3 = c2;
    unsigned int c4 = c3;
    unsigned int c5 = c4;
    unsigned int c6 = c5;
    unsigned int c7 = c6;

    printf("%llu\n", (unsigned long long)(c7));
    return 0;
}
