// a long long loop whose counter something reads afterwards
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long a[20];
    for (int i = 0; i < 20; i++) a[i] = (long long)(i * 1);
    long long total = 0;
    int i;
    for (i = 0; i < 16; i++) {
        total += a[i];
    }

    printf("%lld\n", (long long)(total));
    printf("%lld\n", (long long)(i));
    return 0;
}
