// a unsigned int walk whose stride no addressing mode holds
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned int a[20];
    for (int i = 0; i < 20; i++) a[i] = (unsigned int)(i * 1);
    unsigned int total = 0;
    for (int i = 0; i < 16; i += 3) {
        total += a[i];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
