// six long long walks at once, which is more than the registers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long a1[20];
    for (int i = 0; i < 20; i++) a1[i] = (long long)(i * 1);
    long long a2[20];
    for (int i = 0; i < 20; i++) a2[i] = (long long)(i * 2);
    long long a3[20];
    for (int i = 0; i < 20; i++) a3[i] = (long long)(i * 3);
    long long a4[20];
    for (int i = 0; i < 20; i++) a4[i] = (long long)(i * 4);
    long long a5[20];
    for (int i = 0; i < 20; i++) a5[i] = (long long)(i * 5);
    long long a6[20];
    for (int i = 0; i < 20; i++) a6[i] = (long long)(i * 6);
    long long total = 0;
    for (int i = 0; i < 16; i++) {
        total += a1[i] + a2[i] + a3[i] + a4[i] + a5[i] + a6[i];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
