// two int arrays walked at once, which want one each
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int a[20], b[20];
    for (int i = 0; i < 20; i++) a[i] = (int)(i * 1);
    for (int i = 0; i < 20; i++) b[i] = (int)(i * 2);
    int total = 0;
    for (int i = 0; i < 16; i++) {
        total += a[i] + b[i];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
