// a long long walk whose stride an addressing mode holds
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int n_in = 16;

int main(void) {
    int n = n_in;
    long long a[20];
    for (int i = 0; i < 20; i++) a[i] = (long long)(i * 1);
    long long total = 0;
    for (int i = 0; i < n; i += 4) {
        total += a[i];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
