// three unsigned int reads a constant apart, which want one variable between them
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int n_in = 16;

int main(void) {
    int n = n_in;
    unsigned int a[20];
    for (int i = 0; i < 20; i++) a[i] = (unsigned int)(i * 1);
    unsigned int total = 0;
    for (int i = 0; i < n; i++) {
        total += a[i] + a[i + 1] + a[i + 2];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
