// three long long reads a constant apart, which want one variable between them
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long a[20];
    for (int i = 0; i < 20; i++) a[i] = (long long)(i * 1);
    long long total = 0;
    for (int i = 0; i < 16; i++) {
        total += a[i] + a[i + 1] + a[i + 2];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
