// is-constexpr after include/linux/const.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

#define __is_constexpr(x) \
    (sizeof(int) == sizeof(*(8 ? ((void *)((long)(x) * 0l)) : (int *)8)))

#define RK_LIMIT 24

struct rk_pair {
    unsigned int a;
    unsigned char b[6];
};

enum {
    rk_found = (__is_constexpr(7) << 0)
        | (__is_constexpr(RK_LIMIT * 3 - 1) << 1)
        | (__is_constexpr((unsigned char)300) << 2)
        | (__is_constexpr('a' - 'A') << 3)
        | (__is_constexpr(sizeof(struct rk_pair)) << 4)
        | (__is_constexpr(__builtin_offsetof(struct rk_pair, b)) << 5)
        | (__is_constexpr((int)2.5) << 6)
        | (__is_constexpr(1 ? 3 : 4) << 7)
        | (__is_constexpr(seed_in) << 8)
        | (__is_constexpr(seed_in * 0) << 9)
        | (__is_constexpr(0 && seed_in) << 10)
};

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    unsigned int seen = (__is_constexpr(x) << 0)
        | (__is_constexpr(i * 0u) << 1)
        | (__is_constexpr(RK_LIMIT + 1) << 2);
    return (x ^ rk_found) * 33u + seen + i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
