// is-const after include/linux/compiler.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

#define __is_const_zero(x) \
    _Generic(0 ? (void *)(long)(x) : (char *)0, char *: 1, void *: 0)
#define is_const(x) __is_const_zero(0 * (x))
#define is_const_true(x) __is_const_zero(!(x))
#define is_const_false(x) __is_const_zero(x)

#define RK_LIMIT 24

struct rk_pair {
    unsigned int a;
    unsigned char b[6];
};

enum {
    rk_found = (is_const(7) << 0)
        | (is_const(RK_LIMIT * 3 - 1) << 1)
        | (is_const(sizeof(struct rk_pair)) << 2)
        | (is_const(__builtin_offsetof(struct rk_pair, b)) << 3)
        | (is_const(seed_in) << 4)
        | (is_const_true(RK_LIMIT > 3) << 5)
        | (is_const_true(RK_LIMIT < 3) << 6)
        | (is_const_false(RK_LIMIT < 3) << 7)
        | (is_const_false(RK_LIMIT > 3) << 8)
        | (is_const_false(seed_in) << 9)
};

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    unsigned int seen = (is_const(x) << 0)
        | (is_const(i) << 1)
        | (is_const_true(i < 64u) << 2)
        | (is_const(RK_LIMIT) << 3);
    return (x + rk_found) * 17u + (seen ^ i);
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
