// one unsigned long long load compared, call-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int at_in = 3;
static volatile int noise_count;
static void noise(void) {
    noise_count = noise_count + 1;
}
static void (*volatile jump)(void) = noise;

int main(void) {
    unsigned long long seed = seed_in;
    int at = at_in;

    unsigned long long buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned long long)i;
    }
    unsigned long long value = buffer[at];
    jump();
    int total = (seed < value) ? 4 : 7;

    printf("%lld\n", (long long)(total));
    return 0;
}
