// one short load compared, two-readers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short seed_in = 5;
static volatile int at_in = 3;

int main(void) {
    short seed = seed_in;
    int at = at_in;

    short buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (short)i;
    }
    short value = buffer[at];
    int total = (seed < value) ? 4 : 7;
    total = total + (int)value;

    printf("%lld\n", (long long)(total));
    return 0;
}
