// one unsigned long long load compared, store-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int at_in = 3;
static volatile int other_in = 6;

int main(void) {
    unsigned long long seed = seed_in;
    int at = at_in;
    int other = other_in;

    unsigned long long buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned long long)i;
    }
    unsigned long long value = buffer[at];
    buffer[other] = seed;
    int total = (seed < value) ? 4 : 7;
    total = total + (int)buffer[other];

    printf("%lld\n", (long long)(total));
    return 0;
}
