// one short load compared, store-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short seed_in = 5;
static volatile int at_in = 3;
static volatile int other_in = 6;

int main(void) {
    short seed = seed_in;
    int at = at_in;
    int other = other_in;

    short buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (short)i;
    }
    short value = buffer[at];
    buffer[other] = seed;
    int total = (seed < value) ? 4 : 7;
    total = total + (int)buffer[other];

    printf("%lld\n", (long long)(total));
    return 0;
}
