// one signed char load compared, index-written-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile signed char seed_in = 5;
static volatile int at_in = 3;
static volatile int other_in = 6;

int main(void) {
    signed char seed = seed_in;
    int at = at_in;
    int other = other_in;

    signed char buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (signed char)i;
    }
    signed char value = buffer[at];
    at = other;
    int total = (value < 10) ? 4 : 7;
    total = total + (int)buffer[at];

    printf("%lld\n", (long long)(total));
    return 0;
}
