// one unsigned long long load compared, branch
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int at_in = 3;

int main(void) {
    unsigned long long seed = seed_in;
    int at = at_in;

    unsigned long long buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned long long)i;
    }
    int total = 0;
    if (buffer[at] > seed) {
        total = total + 9;
    }
    total = total + 3;

    printf("%lld\n", (long long)(total));
    return 0;
}
