// one unsigned int load compared, less-right
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int at_in = 3;

int main(void) {
    unsigned int seed = seed_in;
    int at = at_in;

    unsigned int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned int)i;
    }
    int total = (seed < buffer[at]) ? 4 : 7;

    printf("%lld\n", (long long)(total));
    return 0;
}
