// one int load compared, two-readers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int at_in = 3;

int main(void) {
    int seed = seed_in;
    int at = at_in;

    int buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (int)i;
    }
    int value = buffer[at];
    int total = (seed < value) ? 4 : 7;
    total = total + (int)value;

    printf("%lld\n", (long long)(total));
    return 0;
}
