// a repeated unsigned long long expression, chained
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 6ull;
static volatile unsigned long long b_in = 7ull;
static volatile int flag_in = 1;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;
    int flag = flag_in;

    unsigned long long first = a * b + a;
    unsigned long long second = a * b + a;
    unsigned long long total = first + second;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
