// a repeated unsigned long long expression, across-if
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 6ull;
static volatile unsigned long long b_in = 7ull;
static volatile int flag_in = 1;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;
    int flag = flag_in;

    unsigned long long total = 0;
    if (flag) {
        total = a * b;
    } else {
        total = a * b;
    }
    total = total + a * b;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
