// a repeated int expression, straight
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 6;
static volatile int b_in = 7;
static volatile int flag_in = 1;

int main(void) {
    int a = a_in;
    int b = b_in;
    int flag = flag_in;

    int first = a * b;
    int second = a * b;
    int total = first + second;

    printf("%lld\n", (long long)(total));
    return 0;
}
