// a repeated unsigned int expression, across-if
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int a_in = 6u;
static volatile unsigned int b_in = 7u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int a = a_in;
    unsigned int b = b_in;
    int flag = flag_in;

    unsigned int total = 0;
    if (flag) {
        total = a * b;
    } else {
        total = a * b;
    }
    total = total + a * b;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
