// a repeated int expression, partial
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 6;
static volatile int b_in = 7;
static volatile int flag_in = 1;

int main(void) {
    int a = a_in;
    int b = b_in;
    int flag = flag_in;

    int total = a * b;
    if (flag) {
        total = total + a * b;
    } else {
        total = total + (int)0;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
