// a repeated int expression, across-call
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 6;
static volatile int b_in = 7;
static volatile int flag_in = 1;
static int identity(int value) {
    return value;
}

int main(void) {
    int a = a_in;
    int b = b_in;
    int flag = flag_in;

    int first = a * b;
    int kept = identity(first);
    int total = kept + a * b;

    printf("%lld\n", (long long)(total));
    return 0;
}
