// a repeated unsigned int expression, across-store
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long corpus_sink;

static volatile unsigned int a_in = 6u;
static volatile unsigned int b_in = 7u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int a = a_in;
    unsigned int b = b_in;
    int flag = flag_in;

    unsigned int slots[2];
    unsigned int first = a * b;
    slots[0] = a;
    slots[1] = b;
    unsigned int second = a * b;
    unsigned int total = first + second;
    corpus_sink = (long long)(slots[0] + slots[1]);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
