// a repeated unsigned int expression, subscript
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int a_in = 6u;
static volatile unsigned int b_in = 7u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int a = a_in;
    unsigned int b = b_in;
    int flag = flag_in;

    unsigned int slots[4];
    int k = flag + 1;
    slots[k] = a * b;
    unsigned int total = slots[k] + slots[k];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
