// a 8 arm dispatch loop, with the dispatch inside a for loop the arms continue
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char stream[24] = { 3, 2, 1, 0, 7, 6, 5, 4, 3, 2, 1, 0, 7, 6, 5, 4, 3, 2, 1, 0, 7, 6, 5, 4 };

int main(void) {

    void *table[8] = { &&arm0, &&arm1, &&arm2, &&arm3, &&arm4, &&arm5, &&arm6, &&arm7 };
    unsigned long long acc = 1ull;
    unsigned int at = 0u;

    for (at = 0u; at < 24u; at = at + 1u) {
        goto *table[stream[at]];
    arm0:
        acc = acc * 31ull + 0ull;
        continue;
    arm1:
        acc = acc * 31ull + 1ull;
        continue;
    arm2:
        acc = acc * 31ull + 2ull;
        continue;
    arm3:
        acc = acc * 31ull + 3ull;
        continue;
    arm4:
        acc = acc * 31ull + 4ull;
        continue;
    arm5:
        acc = acc * 31ull + 5ull;
        continue;
    arm6:
        acc = acc * 31ull + 6ull;
        continue;
    arm7:
        acc = acc * 31ull + 7ull;
        continue;
    }

    printf("%llu\n", (unsigned long long)(acc));
    printf("%llu\n", (unsigned long long)(at));
    return 0;
}
