// a 8 arm dispatch loop, with every arm dispatching the next one itself
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char stream[24] = { 3, 2, 1, 0, 7, 6, 5, 4, 3, 2, 1, 0, 7, 6, 5, 4, 3, 2, 1, 0, 7, 6, 5, 4 };

int main(void) {

    void *table[8] = { &&arm0, &&arm1, &&arm2, &&arm3, &&arm4, &&arm5, &&arm6, &&arm7 };
    unsigned long long acc = 1ull;
    unsigned int at = 0u;

    goto *table[stream[at]];
    arm0:
        acc = acc * 31ull + 0ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm1:
        acc = acc * 31ull + 1ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm2:
        acc = acc * 31ull + 2ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm3:
        acc = acc * 31ull + 3ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm4:
        acc = acc * 31ull + 4ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm5:
        acc = acc * 31ull + 5ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm6:
        acc = acc * 31ull + 6ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    arm7:
        acc = acc * 31ull + 7ull;
        at = at + 1u;
        if (at >= 24u) goto done;
        goto *table[stream[at]];
    done:
        ;

    printf("%llu\n", (unsigned long long)(acc));
    printf("%llu\n", (unsigned long long)(at));
    return 0;
}
