// a 2 arm dispatch loop, with every arm dispatching the next one itself
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char stream[6] = { 1, 0, 1, 0, 1, 0 };

int main(void) {

    void *table[2] = { &&arm0, &&arm1 };
    unsigned long long acc = 1ull;
    unsigned int at = 0u;

    goto *table[stream[at]];
    arm0:
        acc = acc * 31ull + 0ull;
        at = at + 1u;
        if (at >= 6u) goto done;
        goto *table[stream[at]];
    arm1:
        acc = acc * 31ull + 1ull;
        at = at + 1u;
        if (at >= 6u) goto done;
        goto *table[stream[at]];
    done:
        ;

    printf("%llu\n", (unsigned long long)(acc));
    printf("%llu\n", (unsigned long long)(at));
    return 0;
}
