// a 32 arm dispatch loop, with the table of label addresses at static storage
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char stream[96] = { 3, 10, 17, 24, 31, 6, 13, 20, 27, 2, 9, 16, 23, 30, 5, 12, 19, 26, 1, 8, 15, 22, 29, 4, 11, 18, 25, 0, 7, 14, 21, 28, 3, 10, 17, 24, 31, 6, 13, 20, 27, 2, 9, 16, 23, 30, 5, 12, 19, 26, 1, 8, 15, 22, 29, 4, 11, 18, 25, 0, 7, 14, 21, 28, 3, 10, 17, 24, 31, 6, 13, 20, 27, 2, 9, 16, 23, 30, 5, 12, 19, 26, 1, 8, 15, 22, 29, 4, 11, 18, 25, 0, 7, 14, 21, 28 };

int main(void) {

    static void *table[32] = { &&arm0, &&arm1, &&arm2, &&arm3, &&arm4, &&arm5, &&arm6, &&arm7, &&arm8, &&arm9, &&arm10, &&arm11, &&arm12, &&arm13, &&arm14, &&arm15, &&arm16, &&arm17, &&arm18, &&arm19, &&arm20, &&arm21, &&arm22, &&arm23, &&arm24, &&arm25, &&arm26, &&arm27, &&arm28, &&arm29, &&arm30, &&arm31 };
    unsigned long long acc = 1ull;
    unsigned int at = 0u;

    goto *table[stream[at]];
    arm0:
        acc = acc * 31ull + 0ull;
        goto next;
    arm1:
        acc = acc * 31ull + 1ull;
        goto next;
    arm2:
        acc = acc * 31ull + 2ull;
        goto next;
    arm3:
        acc = acc * 31ull + 3ull;
        goto next;
    arm4:
        acc = acc * 31ull + 4ull;
        goto next;
    arm5:
        acc = acc * 31ull + 5ull;
        goto next;
    arm6:
        acc = acc * 31ull + 6ull;
        goto next;
    arm7:
        acc = acc * 31ull + 7ull;
        goto next;
    arm8:
        acc = acc * 31ull + 8ull;
        goto next;
    arm9:
        acc = acc * 31ull + 9ull;
        goto next;
    arm10:
        acc = acc * 31ull + 10ull;
        goto next;
    arm11:
        acc = acc * 31ull + 11ull;
        goto next;
    arm12:
        acc = acc * 31ull + 12ull;
        goto next;
    arm13:
        acc = acc * 31ull + 13ull;
        goto next;
    arm14:
        acc = acc * 31ull + 14ull;
        goto next;
    arm15:
        acc = acc * 31ull + 15ull;
        goto next;
    arm16:
        acc = acc * 31ull + 16ull;
        goto next;
    arm17:
        acc = acc * 31ull + 17ull;
        goto next;
    arm18:
        acc = acc * 31ull + 18ull;
        goto next;
    arm19:
        acc = acc * 31ull + 19ull;
        goto next;
    arm20:
        acc = acc * 31ull + 20ull;
        goto next;
    arm21:
        acc = acc * 31ull + 21ull;
        goto next;
    arm22:
        acc = acc * 31ull + 22ull;
        goto next;
    arm23:
        acc = acc * 31ull + 23ull;
        goto next;
    arm24:
        acc = acc * 31ull + 24ull;
        goto next;
    arm25:
        acc = acc * 31ull + 25ull;
        goto next;
    arm26:
        acc = acc * 31ull + 26ull;
        goto next;
    arm27:
        acc = acc * 31ull + 27ull;
        goto next;
    arm28:
        acc = acc * 31ull + 28ull;
        goto next;
    arm29:
        acc = acc * 31ull + 29ull;
        goto next;
    arm30:
        acc = acc * 31ull + 30ull;
        goto next;
    arm31:
        acc = acc * 31ull + 31ull;
        goto next;
    next:
        at = at + 1u;
        if (at < 96u) goto *table[stream[at]];

    printf("%llu\n", (unsigned long long)(acc));
    printf("%llu\n", (unsigned long long)(at));
    return 0;
}
