// a 4 arm dispatch loop, with the address in a variable before the jump uses it
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char stream[12] = { 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0 };

int main(void) {

    void *table[4] = { &&arm0, &&arm1, &&arm2, &&arm3 };
    unsigned long long acc = 1ull;
    unsigned int at = 0u;

    void *target = table[stream[at]];
    goto *target;
    arm0:
        acc = acc * 31ull + 0ull;
        goto next;
    arm1:
        acc = acc * 31ull + 1ull;
        goto next;
    arm2:
        acc = acc * 31ull + 2ull;
        goto next;
    arm3:
        acc = acc * 31ull + 3ull;
        goto next;
    next:
        at = at + 1u;
        if (at < 12u) {
            target = table[stream[at]];
            goto *target;
        }

    printf("%llu\n", (unsigned long long)(acc));
    printf("%llu\n", (unsigned long long)(at));
    return 0;
}
