// a 16 arm dispatch loop, with every arm dispatching the next one itself
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char stream[48] = { 3, 10, 1, 8, 15, 6, 13, 4, 11, 2, 9, 0, 7, 14, 5, 12, 3, 10, 1, 8, 15, 6, 13, 4, 11, 2, 9, 0, 7, 14, 5, 12, 3, 10, 1, 8, 15, 6, 13, 4, 11, 2, 9, 0, 7, 14, 5, 12 };

int main(void) {

    void *table[16] = { &&arm0, &&arm1, &&arm2, &&arm3, &&arm4, &&arm5, &&arm6, &&arm7, &&arm8, &&arm9, &&arm10, &&arm11, &&arm12, &&arm13, &&arm14, &&arm15 };
    unsigned long long acc = 1ull;
    unsigned int at = 0u;

    goto *table[stream[at]];
    arm0:
        acc = acc * 31ull + 0ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm1:
        acc = acc * 31ull + 1ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm2:
        acc = acc * 31ull + 2ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm3:
        acc = acc * 31ull + 3ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm4:
        acc = acc * 31ull + 4ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm5:
        acc = acc * 31ull + 5ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm6:
        acc = acc * 31ull + 6ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm7:
        acc = acc * 31ull + 7ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm8:
        acc = acc * 31ull + 8ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm9:
        acc = acc * 31ull + 9ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm10:
        acc = acc * 31ull + 10ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm11:
        acc = acc * 31ull + 11ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm12:
        acc = acc * 31ull + 12ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm13:
        acc = acc * 31ull + 13ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm14:
        acc = acc * 31ull + 14ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    arm15:
        acc = acc * 31ull + 15ull;
        at = at + 1u;
        if (at >= 48u) goto done;
        goto *table[stream[at]];
    done:
        ;

    printf("%llu\n", (unsigned long long)(acc));
    printf("%llu\n", (unsigned long long)(at));
    return 0;
}
