// a long long argument that is constant, one-site
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long scale(long long value, long long factor) {
    return value * factor;
}
static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long total = 0;
    total += scale(seed, (long long)10ll);

    printf("%lld\n", (long long)(total));
    return 0;
}
