// a unsigned int argument that is constant, recursive
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int down(unsigned int value, unsigned int factor, unsigned int depth) {
    if (depth == (unsigned int)0u) {
        return value * factor;
    }
    return down(value, factor, (unsigned int)(depth - 1));
}
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += down(seed, (unsigned int)10u, (unsigned int)2u);
    total += down(seed, (unsigned int)10u, (unsigned int)2u);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
