// a unsigned long long argument that is constant, all-sites-agree
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long scale(unsigned long long value, unsigned long long factor) {
    return value * factor;
}
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    total += scale(seed, (unsigned long long)10ull);
    total += scale(seed, (unsigned long long)10ull);
    total += scale(seed, (unsigned long long)10ull);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
