// a long long argument that is constant, one-more-level
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long scale(long long value, long long factor) {
    return value * factor;
}
static long long outer(long long value, long long factor) {
    return scale(value, (long long)(factor + 1));
}
static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long total = 0;
    total += outer(seed, (long long)9ll);
    total += outer(seed, (long long)9ll);

    printf("%lld\n", (long long)(total));
    return 0;
}
