// a long long argument that is constant, recursive
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long down(long long value, long long factor, long long depth) {
    if (depth == (long long)0ll) {
        return value * factor;
    }
    return down(value, factor, (long long)(depth - 1));
}
static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long total = 0;
    total += down(seed, (long long)10ll, (long long)2ll);
    total += down(seed, (long long)10ll, (long long)2ll);

    printf("%lld\n", (long long)(total));
    return 0;
}
