// a int argument that is constant, through-varargs
// Generated by rucc-corpus. Edit the generator, not this file.

#include <stdarg.h>

int printf(const char *, ...);

static int pick(int value, ...) {
    va_list rest;
    int factor;
    va_start(rest, value);
    factor = va_arg(rest, int);
    va_end(rest);
    return value * factor;
}
static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;

    int total = 0;
    total += pick(seed, (int)10);
    total += pick(seed, (int)10);

    printf("%lld\n", (long long)(total));
    return 0;
}
