// a long long argument that is constant, address-escapes
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static long long scale(long long value, long long factor) {
    return value * factor;
}
static long long (*chosen)(long long, long long) = scale;
static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long total = 0;
    total += scale(seed, (long long)10ll);
    total += chosen(seed, (long long)4ll);

    printf("%lld\n", (long long)(total));
    return 0;
}
