// a unsigned int argument that is constant, address-escapes
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int scale(unsigned int value, unsigned int factor) {
    return value * factor;
}
static unsigned int (*chosen)(unsigned int, unsigned int) = scale;
static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int total = 0;
    total += scale(seed, (unsigned int)10u);
    total += chosen(seed, (unsigned int)4u);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
