// an add on the side where it adds zero
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    unsigned acc = 0;
    for (int round = 0; round < 4096; round++) {
        for (int i = 0; i < 256; i++) {
            unsigned v = data[i];
            unsigned x = v & 7;
            acc += x == 0 ? v + x : v;
        }
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
