// a inferred-pure unsigned long long function called five times
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long table[4] = { 1, 2, 3, 4 };
static unsigned long long helper(unsigned long long value) {
    return table[1] * value;
}
static volatile unsigned long long seed_in = 6ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    for (int i = 0; i < 5; i++) {
        total += helper(seed);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
