// a looping-const int function called five times
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int helper(int value) {
    int sum = 0;
    for (int i = 0; i < value; i++) {
        sum += (int)2;
    }
    return sum;
}
static volatile int seed_in = 6;

int main(void) {
    int seed = seed_in;

    int total = 0;
    for (int i = 0; i < 5; i++) {
        helper(seed);
        total += helper(seed);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
