// a function built with target("sse4.2"), called after a builtin check through a chosen pointer with the loop inside it
// Generated by rucc-corpus. Edit the generator, not this file.

#include <nmmintrin.h>

int printf(const char *, ...);

static unsigned int data[256];
static int cpu_has_feature(void) {
    __builtin_cpu_init();
    return __builtin_cpu_supports("sse4.2") != 0;
}
__attribute__((target("sse4.2"))) static unsigned long long run_fast(const unsigned int *base, int chunks) {
    unsigned long long acc = 0;
    for (int i = 0; i < chunks; i++) {
        const unsigned int *d = base + 4 * i;
        unsigned long long r;
        __m128i a = _mm_loadu_si128((const __m128i *)d);
        __m128i gt = _mm_cmpgt_epi64(a, _mm_shuffle_epi32(a, 0x4e));
        unsigned int mask = (unsigned int)_mm_movemask_epi8(gt);
        r = ((unsigned long long)mask << 32) | _mm_crc32_u32(0xffffffffu, d[0] ^ d[3]);
        acc = acc * 31 + r;
    }
    return acc;
}
static unsigned long long run_slow(const unsigned int *base, int chunks) {
    unsigned long long acc = 0;
    for (int i = 0; i < chunks; i++) {
        const unsigned int *d = base + 4 * i;
        unsigned long long r;
        unsigned long long lo = d[0] | ((unsigned long long)d[1] << 32);
        unsigned long long hi = d[2] | ((unsigned long long)d[3] << 32);
        unsigned long long flip = 0x8000000000000000ull;
        unsigned int mask = 0;
        if ((lo ^ flip) > (hi ^ flip)) {
            mask = mask | 0xffu;
        }
        if ((hi ^ flip) > (lo ^ flip)) {
            mask = mask | 0xff00u;
        }
        unsigned int c = 0xffffffffu ^ d[0] ^ d[3];
        for (int k = 0; k < 32; k++) {
            c = (c & 1u) != 0 ? (c >> 1) ^ 0x82f63b78u : c >> 1;
        }
        r = ((unsigned long long)mask << 32) | c;
        acc = acc * 31 + r;
    }
    return acc;
}
static unsigned long long run_choose(const unsigned int *base, int chunks);
static unsigned long long (*run)(const unsigned int *, int) = run_choose;
static unsigned long long run_choose(const unsigned int *base, int chunks) {
    run = cpu_has_feature() ? run_fast : run_slow;
    return run(base, chunks);
}
static volatile unsigned int seed_in = 20250928u;

int main(void) {
    unsigned int seed = seed_in;
    unsigned int x = seed;
    for (int i = 0; i < 256; i++) {
        x = x * 1103515245u + 12345u;
        data[i] = x ^ (x >> 11);
    }
    data[5] = 0x80000000u;
    data[10] = 0;
    data[15] = 0xffffffffu;
    data[22] = 0x7fffffffu;
    int mismatches = 0;
    unsigned long long got = 0;

    got = run(data, 1);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 1)) {
        mismatches = mismatches + 1;
    }

    got = run(data, 5);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 5)) {
        mismatches = mismatches + 1;
    }

    got = run(data, 16);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 16)) {
        mismatches = mismatches + 1;
    }

    got = run(data, 64);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 64)) {
        mismatches = mismatches + 1;
    }

    printf("%lld\n", (long long)(mismatches));
    return 0;
}
