// a function built with target("ssse3"), called after a builtin check through an if once per chunk
// Generated by rucc-corpus. Edit the generator, not this file.

#include <tmmintrin.h>

int printf(const char *, ...);

static unsigned int data[256];
static int cpu_has_feature(void) {
    __builtin_cpu_init();
    return __builtin_cpu_supports("ssse3") != 0;
}
__attribute__((target("ssse3"))) static unsigned long long one_fast(const unsigned int *d) {
    unsigned long long r;
    __m128i v = _mm_loadu_si128((const __m128i *)d);
    __m128i order = _mm_set_epi8(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
    __m128i a = _mm_abs_epi32(_mm_shuffle_epi8(v, order));
    unsigned int out[4];
    _mm_storeu_si128((__m128i *)out, a);
    r = out[0] + 3ull * out[1] + 5ull * out[2] + 7ull * out[3];
    return r;
}
static unsigned long long run_fast(const unsigned int *base, int chunks) {
    unsigned long long acc = 0;
    for (int i = 0; i < chunks; i++) {
        acc = acc * 31 + one_fast(base + 4 * i);
    }
    return acc;
}
static unsigned long long run_slow(const unsigned int *base, int chunks) {
    unsigned long long acc = 0;
    for (int i = 0; i < chunks; i++) {
        const unsigned int *d = base + 4 * i;
        unsigned long long r;
        unsigned int out[4];
        for (int k = 0; k < 4; k++) {
            unsigned int x = d[3 - k];
            x = (x >> 24) | ((x >> 8) & 0xff00u) | ((x << 8) & 0xff0000u) | (x << 24);
            out[k] = (x & 0x80000000u) != 0 ? 0u - x : x;
        }
        r = out[0] + 3ull * out[1] + 5ull * out[2] + 7ull * out[3];
        acc = acc * 31 + r;
    }
    return acc;
}
static unsigned long long run(const unsigned int *base, int chunks) {
    if (cpu_has_feature()) {
        return run_fast(base, chunks);
    }
    return run_slow(base, chunks);
}
static volatile unsigned int seed_in = 20250928u;

int main(void) {
    unsigned int seed = seed_in;
    unsigned int x = seed;
    for (int i = 0; i < 256; i++) {
        x = x * 1103515245u + 12345u;
        data[i] = x ^ (x >> 11);
    }
    data[5] = 0x80000000u;
    data[10] = 0;
    data[15] = 0xffffffffu;
    data[22] = 0x7fffffffu;
    int mismatches = 0;
    unsigned long long got = 0;

    got = run(data, 1);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 1)) {
        mismatches = mismatches + 1;
    }

    got = run(data, 5);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 5)) {
        mismatches = mismatches + 1;
    }

    got = run(data, 16);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 16)) {
        mismatches = mismatches + 1;
    }

    got = run(data, 64);
    printf("%llu\n", (unsigned long long)(got));
    if (got != run_slow(data, 64)) {
        mismatches = mismatches + 1;
    }

    printf("%lld\n", (long long)(mismatches));
    return 0;
}
