// a 7 element copy over long long, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long source[7];
    long long target[7];
    for (int i = 0; i < 7; i++) {
        source[i] = (long long)(i + 1);
    }

    for (int i = 0; i < 7; i++) {
        target[i] = source[i];
    }

    printf("%lld\n", (long long)(target[0]));
    printf("%lld\n", (long long)(target[6]));
    return 0;
}
