// a 16 element fill over long long, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long source[16];
    long long target[16];
    for (int i = 0; i < 16; i++) {
        source[i] = (long long)(i + 1);
    }

    for (int i = 0; i < 16; i++) {
        target[i] = (long long)0ll;
    }

    printf("%lld\n", (long long)(target[0]));
    printf("%lld\n", (long long)(target[15]));
    return 0;
}
