// a 100 element count over int, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int source[100];
    int target[100];
    for (int i = 0; i < 100; i++) {
        source[i] = (int)(i + 1);
    }

    int matches = 0;
    for (int i = 0; i < 100; i++) {
        if (source[i] % (int)3 == 0) {
            matches++;
        }
    }

    printf("%lld\n", (long long)(matches));
    return 0;
}
