// a 4 element sum over long long, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long source[4];
    long long target[4];
    for (int i = 0; i < 4; i++) {
        source[i] = (long long)(i + 1);
    }

    long long total = 0;
    for (int i = 0; i < 4; i++) {
        total += source[i];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
