// a 4 element sum over unsigned long long, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned long long source[4];
    unsigned long long target[4];
    for (int i = 0; i < 4; i++) {
        source[i] = (unsigned long long)(i + 1);
    }

    unsigned long long total = 0;
    for (int i = 0; i < 4; i++) {
        total += source[i];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
