// a 16 element count over long long, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    long long source[16];
    long long target[16];
    for (int i = 0; i < 16; i++) {
        source[i] = (long long)(i + 1);
    }

    int matches = 0;
    for (int i = 0; i < 16; i++) {
        if (source[i] % (long long)3ll == 0) {
            matches++;
        }
    }

    printf("%lld\n", (long long)(matches));
    return 0;
}
