// a 7 element copy over unsigned int, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned int source[7];
    unsigned int target[7];
    for (int i = 0; i < 7; i++) {
        source[i] = (unsigned int)(i + 1);
    }

    for (int i = 0; i < 7; i++) {
        target[i] = source[i];
    }

    printf("%llu\n", (unsigned long long)(target[0]));
    printf("%llu\n", (unsigned long long)(target[6]));
    return 0;
}
