// a 100 element fill over unsigned long long, which is a library call in disguise
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    unsigned long long source[100];
    unsigned long long target[100];
    for (int i = 0; i < 100; i++) {
        source[i] = (unsigned long long)(i + 1);
    }

    for (int i = 0; i < 100; i++) {
        target[i] = (unsigned long long)0ull;
    }

    printf("%llu\n", (unsigned long long)(target[0]));
    printf("%llu\n", (unsigned long long)(target[99]));
    return 0;
}
