// one arm storing to a local slot whose address was handed out
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int *volatile shown;
static volatile int seed_in = 7;

int main(void) {
    int slot[8] = {0};
    shown = slot;
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }
    long long seen = 0;

    for (int i = 0; i < 256; i++) {
        int v = data[i];
        int k = (v >> 2) & 7;
        seen += slot[k];
        if (v & 1) {
            slot[k] = v;
        }
    }

    long long total = 0;
    for (int k = 0; k < 8; k++) {
        total += (long long)slot[k] * (k + 1);
    }

    printf("%lld\n", (long long)(seen));
    printf("%lld\n", (long long)(total));
    return 0;
}
