// both arms storing atomically to the same place
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }
    int out[256];

    for (int i = 0; i < 256; i++) {
        int v = data[i];
        int *q = &out[i];
        if (v & 1) {
            __atomic_store_n(q, v, __ATOMIC_RELAXED);
        } else {
            __atomic_store_n(q, v + 1, __ATOMIC_RELAXED);
        }
    }

    long long total = 0;
    for (int i = 0; i < 256; i++) {
        total += out[i];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
