// both arms storing through a volatile pointer
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int cell[256];
static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    for (int i = 0; i < 256; i++) {
        int v = data[i];
        volatile int *q = &cell[i];
        if (v & 1) {
            *q = v;
        } else {
            *q = v + 1;
        }
    }

    long long total = 0;
    for (int i = 0; i < 256; i++) {
        total += cell[i];
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
