// a sparse switch on a value that is one case 95 times in a hundred, with wrong hint
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int classify(int value) {
    switch (__builtin_expect(value, 85)) {
    case 0: return 1;
    case 17: return 920;
    case 34: return 839;
    case 51: return 758;
    case 68: return 677;
    case 85: return 596;
    case 102: return 515;
    case 119: return 434;
    case 136: return 353;
    case 153: return 272;
    case 170: return 191;
    case 187: return 110;
    case 204: return 29;
    case 221: return 948;
    case 238: return 867;
    case 255: return 786;
    case 272: return 705;
    case 289: return 624;
    case 306: return 543;
    case 323: return 462;
    case 340: return 381;
    case 357: return 300;
    case 374: return 219;
    case 391: return 138;
    case 408: return 57;
    case 425: return 976;
    case 442: return 895;
    case 459: return 814;
    case 476: return 733;
    case 493: return 652;
    case 510: return 571;
    case 527: return 490;
    case 544: return 409;
    case 561: return 328;
    case 578: return 247;
    case 595: return 166;
    case 612: return 85;
    case 629: return 4;
    case 646: return 923;
    case 663: return 842;
    default: return 0;
    }
}
static volatile unsigned int seed_in = 7u;
static volatile int step_in = 17;

int main(void) {
    unsigned int seed = seed_in;
    int step = step_in;

    unsigned state = seed;
    unsigned long long total = 0;
    for (int i = 0; i < 20000000; i++) {
        state = state * 1103515245u + 12345u;
        int label = ((state >> 16) & 127u) < 122u ? 23 : (int)(((state >> 24) * 40u) >> 8);
        total += (unsigned long long)classify(label * step);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
