// a dense switch with 3 labels
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int classify(int value) {
    switch (value) {
    case 0: return 1;
    case 1: return 2;
    case 2: return 3;
    default: return 0;
    }
}
static volatile int step_in = 1;

int main(void) {
    int step = step_in;

    long long total = 0;
    for (int label = 0; label < 3; label++) {
        total += classify(label * step);
    }
    total += classify(-1);

    printf("%lld\n", (long long)(total));
    return 0;
}
