// 1 unreferenced variables
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int unused0 = 0;
static volatile int seed_in = 4;

int main(void) {
    int seed = seed_in;

    printf("%lld\n", (long long)(seed + 1));
    return 0;
}
