// 5 unreferenced functions
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int unused0(int value) {
    return value * 1 + 0;
}
static int unused1(int value) {
    return value * 2 + 1;
}
static int unused2(int value) {
    return value * 3 + 2;
}
static int unused3(int value) {
    return value * 4 + 3;
}
static int unused4(int value) {
    return value * 5 + 4;
}
static volatile int seed_in = 4;

int main(void) {
    int seed = seed_in;

    printf("%lld\n", (long long)(seed + 1));
    return 0;
}
