// 1 unreferenced chain
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int link0(int value) { return value + 1; }
static volatile int seed_in = 4;

int main(void) {
    int seed = seed_in;

    printf("%lld\n", (long long)(seed + 1));
    return 0;
}
