// mixed-sign arithmetic on unsigned short
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned short a0_in = 0u;
static volatile short b0_in = 3;
static volatile unsigned short a1_in = 2u;
static volatile short b1_in = 3;
static volatile unsigned short a2_in = 8u;
static volatile short b2_in = 3;
static volatile unsigned short a3_in = 255u;
static volatile short b3_in = 3;
static volatile unsigned short a4_in = 65535u;
static volatile short b4_in = 3;

int main(void) {
    unsigned short a0 = a0_in;
    short b0 = b0_in;
    unsigned short sum0 = (unsigned short)(a0 + b0);
    printf("%lld\n", (long long)(sum0));
    unsigned short a1 = a1_in;
    short b1 = b1_in;
    unsigned short sum1 = (unsigned short)(a1 + b1);
    printf("%lld\n", (long long)(sum1));
    unsigned short a2 = a2_in;
    short b2 = b2_in;
    unsigned short sum2 = (unsigned short)(a2 + b2);
    printf("%lld\n", (long long)(sum2));
    unsigned short a3 = a3_in;
    short b3 = b3_in;
    unsigned short sum3 = (unsigned short)(a3 + b3);
    printf("%lld\n", (long long)(sum3));
    unsigned short a4 = a4_in;
    short b4 = b4_in;
    unsigned short sum4 = (unsigned short)(a4 + b4);
    printf("%lld\n", (long long)(sum4));
    return 0;
}
