// narrow-twice cast chains from unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a0_in = 0ull;
static volatile unsigned long long a1_in = 2ull;
static volatile unsigned long long a2_in = 8ull;
static volatile unsigned long long a3_in = 255ull;
static volatile unsigned long long a4_in = 18446744073709551615ull;

int main(void) {
    unsigned long long a0 = a0_in;
    unsigned short c0_32_16 = (unsigned short)(unsigned int)a0;
    printf("%lld\n", (long long)(c0_32_16));
    unsigned char c0_32_8 = (unsigned char)(unsigned int)a0;
    printf("%lld\n", (long long)(c0_32_8));
    unsigned char c0_16_8 = (unsigned char)(unsigned short)a0;
    printf("%lld\n", (long long)(c0_16_8));

    unsigned long long a1 = a1_in;
    unsigned short c1_32_16 = (unsigned short)(unsigned int)a1;
    printf("%lld\n", (long long)(c1_32_16));
    unsigned char c1_32_8 = (unsigned char)(unsigned int)a1;
    printf("%lld\n", (long long)(c1_32_8));
    unsigned char c1_16_8 = (unsigned char)(unsigned short)a1;
    printf("%lld\n", (long long)(c1_16_8));

    unsigned long long a2 = a2_in;
    unsigned short c2_32_16 = (unsigned short)(unsigned int)a2;
    printf("%lld\n", (long long)(c2_32_16));
    unsigned char c2_32_8 = (unsigned char)(unsigned int)a2;
    printf("%lld\n", (long long)(c2_32_8));
    unsigned char c2_16_8 = (unsigned char)(unsigned short)a2;
    printf("%lld\n", (long long)(c2_16_8));

    unsigned long long a3 = a3_in;
    unsigned short c3_32_16 = (unsigned short)(unsigned int)a3;
    printf("%lld\n", (long long)(c3_32_16));
    unsigned char c3_32_8 = (unsigned char)(unsigned int)a3;
    printf("%lld\n", (long long)(c3_32_8));
    unsigned char c3_16_8 = (unsigned char)(unsigned short)a3;
    printf("%lld\n", (long long)(c3_16_8));

    unsigned long long a4 = a4_in;
    unsigned short c4_32_16 = (unsigned short)(unsigned int)a4;
    printf("%lld\n", (long long)(c4_32_16));
    unsigned char c4_32_8 = (unsigned char)(unsigned int)a4;
    printf("%lld\n", (long long)(c4_32_8));
    unsigned char c4_16_8 = (unsigned char)(unsigned short)a4;
    printf("%lld\n", (long long)(c4_16_8));

    return 0;
}
