// stop-early cast chains from unsigned char
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned char a0_in = 0u;
static volatile unsigned char a1_in = 1u;
static volatile unsigned char a2_in = 3u;
static volatile unsigned char a3_in = 8u;
static volatile unsigned char a4_in = 255u;

int main(void) {
    unsigned char a0 = a0_in;
    unsigned short c0_32_16 = (unsigned short)(unsigned int)a0;
    printf("%lld\n", (long long)(c0_32_16));
    unsigned short c0_64_16 = (unsigned short)(unsigned long long)a0;
    printf("%lld\n", (long long)(c0_64_16));
    unsigned int c0_64_32 = (unsigned int)(unsigned long long)a0;
    printf("%llu\n", (unsigned long long)(c0_64_32));

    unsigned char a1 = a1_in;
    unsigned short c1_32_16 = (unsigned short)(unsigned int)a1;
    printf("%lld\n", (long long)(c1_32_16));
    unsigned short c1_64_16 = (unsigned short)(unsigned long long)a1;
    printf("%lld\n", (long long)(c1_64_16));
    unsigned int c1_64_32 = (unsigned int)(unsigned long long)a1;
    printf("%llu\n", (unsigned long long)(c1_64_32));

    unsigned char a2 = a2_in;
    unsigned short c2_32_16 = (unsigned short)(unsigned int)a2;
    printf("%lld\n", (long long)(c2_32_16));
    unsigned short c2_64_16 = (unsigned short)(unsigned long long)a2;
    printf("%lld\n", (long long)(c2_64_16));
    unsigned int c2_64_32 = (unsigned int)(unsigned long long)a2;
    printf("%llu\n", (unsigned long long)(c2_64_32));

    unsigned char a3 = a3_in;
    unsigned short c3_32_16 = (unsigned short)(unsigned int)a3;
    printf("%lld\n", (long long)(c3_32_16));
    unsigned short c3_64_16 = (unsigned short)(unsigned long long)a3;
    printf("%lld\n", (long long)(c3_64_16));
    unsigned int c3_64_32 = (unsigned int)(unsigned long long)a3;
    printf("%llu\n", (unsigned long long)(c3_64_32));

    unsigned char a4 = a4_in;
    unsigned short c4_32_16 = (unsigned short)(unsigned int)a4;
    printf("%lld\n", (long long)(c4_32_16));
    unsigned short c4_64_16 = (unsigned short)(unsigned long long)a4;
    printf("%lld\n", (long long)(c4_64_16));
    unsigned int c4_64_32 = (unsigned int)(unsigned long long)a4;
    printf("%llu\n", (unsigned long long)(c4_64_32));

    return 0;
}
