// shift arithmetic on signed char
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile signed char a0_in = (-127 - 1);
static volatile signed char a1_in = (-2);
static volatile signed char a2_in = 1;
static volatile signed char a3_in = 7;
static volatile signed char a4_in = 127;

int main(void) {
    signed char a0 = a0_in;
    signed char a1 = a1_in;
    signed char a2 = a2_in;
    signed char s2_3 = (signed char)(a2 << 3);
    printf("%lld\n", (long long)(s2_3));
    signed char s2_9 = (signed char)(a2 << 9);
    printf("%lld\n", (long long)(s2_9));
    signed char a3 = a3_in;
    signed char s3_3 = (signed char)(a3 << 3);
    printf("%lld\n", (long long)(s3_3));
    signed char s3_9 = (signed char)(a3 << 9);
    printf("%lld\n", (long long)(s3_9));
    signed char a4 = a4_in;
    signed char s4_3 = (signed char)(a4 << 3);
    printf("%lld\n", (long long)(s4_3));
    signed char s4_9 = (signed char)(a4 << 9);
    printf("%lld\n", (long long)(s4_9));
    return 0;
}
