// narrow-twice cast chains from int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a0_in = (-2147483647 - 1);
static volatile int a1_in = (-2);
static volatile int a2_in = 2;
static volatile int a3_in = 16;
static volatile int a4_in = 2147483647;

int main(void) {
    int a0 = a0_in;
    signed char c0_16_8 = (signed char)(short)a0;
    printf("%lld\n", (long long)(c0_16_8));

    int a1 = a1_in;
    signed char c1_16_8 = (signed char)(short)a1;
    printf("%lld\n", (long long)(c1_16_8));

    int a2 = a2_in;
    signed char c2_16_8 = (signed char)(short)a2;
    printf("%lld\n", (long long)(c2_16_8));

    int a3 = a3_in;
    signed char c3_16_8 = (signed char)(short)a3;
    printf("%lld\n", (long long)(c3_16_8));

    int a4 = a4_in;
    signed char c4_16_8 = (signed char)(short)a4;
    printf("%lld\n", (long long)(c4_16_8));

    return 0;
}
