// stored-back arithmetic on short
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short a0_in = (-32767 - 1);
static volatile short a1_in = (-2);
static volatile short a2_in = 2;
static volatile short a3_in = 16;
static volatile short a4_in = 32767;

int main(void) {
    short a0 = a0_in;
    short v0_add = (short)(a0 + (short)5);
    printf("%lld\n", (long long)(v0_add));
    short v0_sub = (short)(a0 - (short)5);
    printf("%lld\n", (long long)(v0_sub));
    short v0_mul = (short)(a0 * (short)5);
    printf("%lld\n", (long long)(v0_mul));
    short v0_and = (short)(a0 & (short)5);
    printf("%lld\n", (long long)(v0_and));
    short v0_or = (short)(a0 | (short)5);
    printf("%lld\n", (long long)(v0_or));
    short v0_xor = (short)(a0 ^ (short)5);
    printf("%lld\n", (long long)(v0_xor));

    short a1 = a1_in;
    short v1_add = (short)(a1 + (short)5);
    printf("%lld\n", (long long)(v1_add));
    short v1_sub = (short)(a1 - (short)5);
    printf("%lld\n", (long long)(v1_sub));
    short v1_mul = (short)(a1 * (short)5);
    printf("%lld\n", (long long)(v1_mul));
    short v1_and = (short)(a1 & (short)5);
    printf("%lld\n", (long long)(v1_and));
    short v1_or = (short)(a1 | (short)5);
    printf("%lld\n", (long long)(v1_or));
    short v1_xor = (short)(a1 ^ (short)5);
    printf("%lld\n", (long long)(v1_xor));

    short a2 = a2_in;
    short v2_add = (short)(a2 + (short)5);
    printf("%lld\n", (long long)(v2_add));
    short v2_sub = (short)(a2 - (short)5);
    printf("%lld\n", (long long)(v2_sub));
    short v2_mul = (short)(a2 * (short)5);
    printf("%lld\n", (long long)(v2_mul));
    short v2_and = (short)(a2 & (short)5);
    printf("%lld\n", (long long)(v2_and));
    short v2_or = (short)(a2 | (short)5);
    printf("%lld\n", (long long)(v2_or));
    short v2_xor = (short)(a2 ^ (short)5);
    printf("%lld\n", (long long)(v2_xor));

    short a3 = a3_in;
    short v3_add = (short)(a3 + (short)5);
    printf("%lld\n", (long long)(v3_add));
    short v3_sub = (short)(a3 - (short)5);
    printf("%lld\n", (long long)(v3_sub));
    short v3_mul = (short)(a3 * (short)5);
    printf("%lld\n", (long long)(v3_mul));
    short v3_and = (short)(a3 & (short)5);
    printf("%lld\n", (long long)(v3_and));
    short v3_or = (short)(a3 | (short)5);
    printf("%lld\n", (long long)(v3_or));
    short v3_xor = (short)(a3 ^ (short)5);
    printf("%lld\n", (long long)(v3_xor));

    short a4 = a4_in;
    short v4_add = (short)(a4 + (short)5);
    printf("%lld\n", (long long)(v4_add));
    short v4_sub = (short)(a4 - (short)5);
    printf("%lld\n", (long long)(v4_sub));
    short v4_mul = (short)(a4 * (short)5);
    printf("%lld\n", (long long)(v4_mul));
    short v4_and = (short)(a4 & (short)5);
    printf("%lld\n", (long long)(v4_and));
    short v4_or = (short)(a4 | (short)5);
    printf("%lld\n", (long long)(v4_or));
    short v4_xor = (short)(a4 ^ (short)5);
    printf("%lld\n", (long long)(v4_xor));

    return 0;
}
