// widen-twice cast chains from short
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short a0_in = (-32767 - 1);
static volatile short a1_in = (-2);
static volatile short a2_in = 2;
static volatile short a3_in = 16;
static volatile short a4_in = 32767;

int main(void) {
    short a0 = a0_in;
    long long c0_32_64 = (long long)(int)a0;
    printf("%lld\n", (long long)(c0_32_64));

    short a1 = a1_in;
    long long c1_32_64 = (long long)(int)a1;
    printf("%lld\n", (long long)(c1_32_64));

    short a2 = a2_in;
    long long c2_32_64 = (long long)(int)a2;
    printf("%lld\n", (long long)(c2_32_64));

    short a3 = a3_in;
    long long c3_32_64 = (long long)(int)a3;
    printf("%lld\n", (long long)(c3_32_64));

    short a4 = a4_in;
    long long c4_32_64 = (long long)(int)a4;
    printf("%lld\n", (long long)(c4_32_64));

    return 0;
}
