// stop-early cast chains from short
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short a0_in = (-32767 - 1);
static volatile short a1_in = (-2);
static volatile short a2_in = 2;
static volatile short a3_in = 16;
static volatile short a4_in = 32767;

int main(void) {
    short a0 = a0_in;
    int c0_64_32 = (int)(long long)a0;
    printf("%lld\n", (long long)(c0_64_32));

    short a1 = a1_in;
    int c1_64_32 = (int)(long long)a1;
    printf("%lld\n", (long long)(c1_64_32));

    short a2 = a2_in;
    int c2_64_32 = (int)(long long)a2;
    printf("%lld\n", (long long)(c2_64_32));

    short a3 = a3_in;
    int c3_64_32 = (int)(long long)a3;
    printf("%lld\n", (long long)(c3_64_32));

    short a4 = a4_in;
    int c4_64_32 = (int)(long long)a4;
    printf("%lld\n", (long long)(c4_64_32));

    return 0;
}
