// a flag set in two arms and tested straight after the join
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    int hist[8] = { 0 };
    int above = 0;
    int below = 0;
    for (int i = 0; i < 256; i++) {
        int x = data[i];
        int flag;
        if (x > 100) {
            flag = 1;
            hist[x & 3] += 1;
        } else {
            flag = 0;
            hist[4 + (x & 3)] += 2;
        }
        if (flag) {
            above += x;
            hist[x & 3] += 4;
        } else {
            below += x;
            hist[4 + (x & 3)] += 8;
        }
    }

    printf("%lld\n", (long long)(above));
    printf("%lld\n", (long long)(below));
    printf("%lld\n", (long long)(hist[0] + hist[1] + hist[2] + hist[3]));
    printf("%lld\n", (long long)(hist[4] + hist[5] + hist[6] + hist[7]));
    return 0;
}
