// a chain of 4 dead int computations beside one live one
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 3;

int main(void) {
    int seed = seed_in;

    int dead = seed;
    dead = dead * (int)3 + (int)0;
    dead = dead * (int)3 + (int)1;
    dead = dead * (int)3 + (int)2;
    dead = dead * (int)3 + (int)3;

    printf("%lld\n", (long long)(seed + (int)1));
    return 0;
}
