// a chain of 1 dead long long computations beside one live one
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 3ll;

int main(void) {
    long long seed = seed_in;

    long long dead = seed;
    dead = dead * (long long)3ll + (long long)0ll;

    printf("%lld\n", (long long)(seed + (long long)1ll));
    return 0;
}
