// a chain of 16 dead unsigned int computations beside one live one
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int dead = seed;
    dead = dead * (unsigned int)3u + (unsigned int)0u;
    dead = dead * (unsigned int)3u + (unsigned int)1u;
    dead = dead * (unsigned int)3u + (unsigned int)2u;
    dead = dead * (unsigned int)3u + (unsigned int)3u;
    dead = dead * (unsigned int)3u + (unsigned int)4u;
    dead = dead * (unsigned int)3u + (unsigned int)5u;
    dead = dead * (unsigned int)3u + (unsigned int)6u;
    dead = dead * (unsigned int)3u + (unsigned int)7u;
    dead = dead * (unsigned int)3u + (unsigned int)8u;
    dead = dead * (unsigned int)3u + (unsigned int)9u;
    dead = dead * (unsigned int)3u + (unsigned int)10u;
    dead = dead * (unsigned int)3u + (unsigned int)11u;
    dead = dead * (unsigned int)3u + (unsigned int)12u;
    dead = dead * (unsigned int)3u + (unsigned int)13u;
    dead = dead * (unsigned int)3u + (unsigned int)14u;
    dead = dead * (unsigned int)3u + (unsigned int)15u;

    printf("%llu\n", (unsigned long long)(seed + (unsigned int)1u));
    return 0;
}
