// a chain of 1 dead unsigned int computations beside one live one
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 3u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int dead = seed;
    dead = dead * (unsigned int)3u + (unsigned int)0u;

    printf("%llu\n", (unsigned long long)(seed + (unsigned int)1u));
    return 0;
}
