// alternate dispatch between 2 functions in tail position, done many times
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static __attribute__((noinline)) unsigned long long s0(const unsigned char *p, const unsigned char *end, unsigned long long acc);
static __attribute__((noinline)) unsigned long long s1(const unsigned char *p, const unsigned char *end, unsigned long long acc);
static __attribute__((noinline)) unsigned long long s0(const unsigned char *p, const unsigned char *end, unsigned long long acc) {
    if (p == end) {
        return acc;
    }
    return s1(p + 1, end, acc * 31 + *p);
}
static __attribute__((noinline)) unsigned long long s1(const unsigned char *p, const unsigned char *end, unsigned long long acc) {
    if (p == end) {
        return acc;
    }
    return s0(p + 1, end, acc ^ ((unsigned long long)*p << 3));
}
static volatile unsigned long long seed_in = 7ull;

int main(void) {
    unsigned long long total = 0;
    unsigned long long seed = seed_in;

    static unsigned char text[2048];
    unsigned long long drawn = seed;
    for (int i = 0; i < 2048; i++) {
        drawn = drawn * 6364136223846793005ull + 1442695040888963407ull;
        text[i] = (unsigned char)(drawn >> 33);
    }
    for (int round = 0; round < 1024; round++) {
        total += s0(text, text + 2048, (unsigned long long)round);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
