// one run of 26 labels sharing an arm
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int in_run(int value) {
    switch (value) {
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
        return 1;
    default:
        return 0;
    }
}
static volatile int first_in = 7;
static volatile int count_in = 32;

int main(void) {
    int first = first_in;
    int count = count_in;

    long long total = 0;
    for (int step = 0; step < count; step++) {
        total += in_run(first + step);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
