// a run of 3 labels reaching the bottom of int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int at_edge(int value) {
    switch (value) {
    case (-2147483647 - 1):
    case (-2147483647):
    case (-2147483646):
        return 1;
    default:
        return 0;
    }
}
static volatile int first_in = (-2147483647 - 1);
static volatile int count_in = 6;

int main(void) {
    int first = first_in;
    int count = count_in;

    long long total = 0;
    for (int step = 0; step < count; step++) {
        total += at_edge(first + (int)step);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
