// lfind8-le-subs over high values starting 1 elements in, against a scalar loop
// Generated by rucc-corpus. Edit the generator, not this file.

#include <emmintrin.h>

int printf(const char *, ...);

static unsigned char elems[1040];
static int search_simd(unsigned char key, const unsigned char *base, unsigned int nelem) {
    unsigned int i = 0;
    const __m128i keys = _mm_set1_epi8((char)key);
    const unsigned int tail_idx = nelem & ~(16u - 1);
    for (i = 0; i < tail_idx; i += 16) {
        const __m128i chunk = _mm_loadu_si128((const __m128i *)&base[i]);
        if (_mm_movemask_epi8(_mm_cmpeq_epi8(_mm_subs_epu8(chunk, keys), _mm_setzero_si128())) != 0) {
            return 1;
        }
    }
    for (; i < nelem; i++) {
        if (base[i] <= key) {
            return 1;
        }
    }
    return 0;
}
static int search_scalar(unsigned char key, const unsigned char *base, unsigned int nelem) {
    for (unsigned int i = 0; i < nelem; i++) {
        if (base[i] <= key) {
            return 1;
        }
    }
    return 0;
}
static const unsigned int lengths[54] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 47, 48, 49, 63, 64, 65, 100, 127, 128, 129, 255, 256, 1000 };
static volatile unsigned int seed_in = 20250928u;

int main(void) {
    unsigned int seed = seed_in;
    unsigned int x = seed;
    for (int i = 0; i < 1024; i++) {
        x = x * 1103515245u + 12345u;
        elems[i] = (unsigned char)(0x80 + (x >> 16) % 127);
    }
    const unsigned char *base = elems + 1;
    int found[4] = { 0, 0, 0, 0 };
    unsigned long long pattern = 0;
    int mismatches = 0;
    for (int n = 0; n < 54; n++) {
        unsigned int len = lengths[n];
        unsigned char keys[4];
        keys[0] = (unsigned char)(base[0] - 1);
        keys[1] = (unsigned char)(base[len / 2] - 1);
        keys[2] = (unsigned char)(base[len > 0 ? len - 1 : 0] - 1);
        keys[3] = 0x7f;
        for (int k = 0; k < 4; k++) {
            int got = search_simd(keys[k], base, len);
            found[k] = found[k] + got;
            pattern = pattern * 3 + (unsigned long long)got;
            if (got != search_scalar(keys[k], base, len)) {
                mismatches = mismatches + 1;
            }
        }
    }

    printf("%lld\n", (long long)(found[0]));
    printf("%lld\n", (long long)(found[1]));
    printf("%lld\n", (long long)(found[2]));
    printf("%lld\n", (long long)(found[3]));
    printf("%llu\n", (unsigned long long)(pattern));
    printf("%lld\n", (long long)(mismatches));
    return 0;
}
