// lfind32-x4 over low values starting 3 elements in, against a scalar loop
// Generated by rucc-corpus. Edit the generator, not this file.

#include <emmintrin.h>

int printf(const char *, ...);

static unsigned int elems[1040];
static int search_simd(unsigned int key, const unsigned int *base, unsigned int nelem) {
    unsigned int i = 0;
    const unsigned int nelem_per_vector = 4;
    const unsigned int nelem_per_iteration = 4 * nelem_per_vector;
    const unsigned int tail_idx = nelem & ~(nelem_per_iteration - 1);
    const __m128i keys = _mm_set1_epi32((int)key);
    for (i = 0; i < tail_idx; i += nelem_per_iteration) {
        const __m128i vals1 = _mm_loadu_si128((const __m128i *)&base[i + 0]);
        const __m128i vals2 = _mm_loadu_si128((const __m128i *)&base[i + 4]);
        const __m128i vals3 = _mm_loadu_si128((const __m128i *)&base[i + 8]);
        const __m128i vals4 = _mm_loadu_si128((const __m128i *)&base[i + 12]);
        const __m128i result1 = _mm_cmpeq_epi32(keys, vals1);
        const __m128i result2 = _mm_cmpeq_epi32(keys, vals2);
        const __m128i result3 = _mm_cmpeq_epi32(keys, vals3);
        const __m128i result4 = _mm_cmpeq_epi32(keys, vals4);
        const __m128i tmp1 = _mm_or_si128(result1, result2);
        const __m128i tmp2 = _mm_or_si128(result3, result4);
        const __m128i result = _mm_or_si128(tmp1, tmp2);
        if (_mm_movemask_epi8(result) != 0) {
            return 1;
        }
    }
    for (; i < nelem; i++) {
        if (base[i] == key) {
            return 1;
        }
    }
    return 0;
}
static int search_scalar(unsigned int key, const unsigned int *base, unsigned int nelem) {
    for (unsigned int i = 0; i < nelem; i++) {
        if (base[i] == key) {
            return 1;
        }
    }
    return 0;
}
static const unsigned int lengths[54] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 47, 48, 49, 63, 64, 65, 100, 127, 128, 129, 255, 256, 1000 };
static volatile unsigned int seed_in = 20250928u;

int main(void) {
    unsigned int seed = seed_in;
    unsigned int x = seed;
    for (int i = 0; i < 1024; i++) {
        x = x * 1103515245u + 12345u;
        elems[i] = 1 + (x >> 8) % 1000000;
    }
    const unsigned int *base = elems + 3;
    int found[4] = { 0, 0, 0, 0 };
    unsigned long long pattern = 0;
    int mismatches = 0;
    for (int n = 0; n < 54; n++) {
        unsigned int len = lengths[n];
        unsigned int keys[4];
        keys[0] = (unsigned int)(base[0]);
        keys[1] = (unsigned int)(base[len / 2]);
        keys[2] = (unsigned int)(base[len > 0 ? len - 1 : 0]);
        keys[3] = 0x80000001;
        for (int k = 0; k < 4; k++) {
            int got = search_simd(keys[k], base, len);
            found[k] = found[k] + got;
            pattern = pattern * 3 + (unsigned long long)got;
            if (got != search_scalar(keys[k], base, len)) {
                mismatches = mismatches + 1;
            }
        }
    }

    printf("%lld\n", (long long)(found[0]));
    printf("%lld\n", (long long)(found[1]));
    printf("%lld\n", (long long)(found[2]));
    printf("%lld\n", (long long)(found[3]));
    printf("%llu\n", (unsigned long long)(pattern));
    printf("%lld\n", (long long)(mismatches));
    return 0;
}
