// a range that comes from inverted-condition
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int x_in = 20;
static volatile int y_in = 2;

int main(void) {
    int x = x_in;
    int y = y_in;

    int both = (x > 10) & (y < 5);
    int deeper = both & (x < 100);
    int settled = 1;
    if (deeper) {
        settled = (x > 5) && (y < 10) && (x < 1000);
    }

    printf("%lld\n", (long long)(settled));
    return 0;
}
