// a range that comes from switch-arms
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int pick_in = 9;

int main(void) {
    int pick = pick_in;

    int settled = 0;
    switch (pick) {
        case 1: settled = (pick == 1) && (pick < 2); break;
        case 2: settled = (pick == 2) && (pick > 1); break;
        case 3: settled = (pick == 3) && (pick > 2); break;
        default: settled = (pick != 1) && (pick != 2) && (pick != 3);
            break;
    }

    printf("%lld\n", (long long)(settled));
    return 0;
}
