// a range that comes from guard-keeps-the-divide
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int divisor_in = 0;
static volatile int numerator_in = 84;

int main(void) {
    int divisor = divisor_in;
    int numerator = numerator_in;

    int quotient;
    if (divisor != 0) {
        quotient = numerator / divisor;
    } else {
        quotient = 7;
    }

    printf("%lld\n", (long long)(quotient == 7));
    return 0;
}
