// questions a guard on a unsigned int already answered
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int raw_in = 40u;

int main(void) {
    unsigned int raw = raw_in;

    unsigned int bounded = raw % (unsigned int)100u;
    unsigned int masked = raw & (unsigned int)63u;

    printf("%lld\n", (long long)(bounded < (unsigned int)100u));
    printf("%lld\n", (long long)(masked < (unsigned int)64u));
    printf("%lld\n", (long long)(masked >= (unsigned int)0u));

    int guarded;
    if (raw > (unsigned int)10u) {
        guarded = raw > (unsigned int)5u;
    } else {
        guarded = raw <= (unsigned int)10u;
    }
    printf("%lld\n", (long long)(guarded));
    return 0;
}
