// a range that comes from guard-keeps-the-shift
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int count_in = 32;
static volatile int x_in = 1;

int main(void) {
    int count = count_in;
    int x = x_in;

    int shifted;
    if (count < 32) {
        shifted = x << count;
    } else {
        shifted = 0;
    }

    printf("%lld\n", (long long)(shifted == 0));
    return 0;
}
