// the redundant-move peephole on unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 40ull;
static volatile unsigned long long b_in = 15ull;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;

    unsigned long long copy = a;
    unsigned long long again = copy;
    unsigned long long total = again - b;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
