// the compare-after-subtract peephole on int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 40;
static volatile int b_in = 15;

int main(void) {
    int a = a_in;
    int b = b_in;

    int difference = a - b;
    int positive = difference > (int)0;
    int total = difference + (int)positive;

    printf("%lld\n", (long long)(total));
    return 0;
}
