// the compare-after-subtract peephole on long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 40ll;
static volatile long long b_in = 15ll;

int main(void) {
    long long a = a_in;
    long long b = b_in;

    long long difference = a - b;
    int positive = difference > (long long)0ll;
    long long total = difference + (long long)positive;

    printf("%lld\n", (long long)(total));
    return 0;
}
