// the test-against-zero peephole on long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 40ll;
static volatile long long b_in = 15ll;

int main(void) {
    long long a = a_in;
    long long b = b_in;

    long long masked = a & (long long)7ll;
    int zero = masked == (long long)0ll;
    long long total = masked + (long long)zero;

    printf("%lld\n", (long long)(total));
    return 0;
}
