// the test-against-zero peephole on unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int a_in = 40u;
static volatile unsigned int b_in = 15u;

int main(void) {
    unsigned int a = a_in;
    unsigned int b = b_in;

    unsigned int masked = a & (unsigned int)7u;
    int zero = masked == (unsigned int)0u;
    unsigned int total = masked + (unsigned int)zero;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
