// a run time sized object, alloca
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int count_in = 8;

int main(void) {
    int count = count_in;

    unsigned char *room = (unsigned char *)__builtin_alloca(count);
    for (int i = 0; i < count; i++) {
        room[i] = (unsigned char)(i * 3);
    }
    int total = 0;
    for (int i = 0; i < count; i++) {
        total = total + room[i];
    }

    printf("%lld\n", (long long)(total));
    printf("%lld\n", (long long)(room[count - 1]));
    return 0;
}
