// a run time sized object, jumping-out-of-the-scope
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int count_in = 4;

int main(void) {
    int count = count_in;

    int total = 0;
    for (int round = 0; round < 3; round++) {
        int values[count + round];
        for (int j = 0; j < count + round; j++) {
            values[j] = 1;
        }
        total = total + values[0] + values[count + round - 1];
        if (round == 1) {
            goto done;
        }
    }
    done:

    printf("%lld\n", (long long)(total));
    return 0;
}
