// two pointers compared, which is the case a width refusal used to lose
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;
static int cells[16] = {
    1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46,
};

int main(void) {
    int seed = seed_in;

    int data[256];
    int mate[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
        mate[i] = (i % 4) == 0 ? data[i] : ((data[i] + 1) & 255);
    }

    long long total = 0;
    for (int i = 0; i < 256; i++) {
        int a = data[i];
        int b = mate[i];
        int *p = &cells[a & 15];
        int *q = &cells[b & 15];
        total += *(p == q ? q : p);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
