// The two functions the main unit takes the address of.
// Generated by rucc-corpus. Edit the generator, not this file.

int corpus_triple(int x)
{
    return x * 3;
}

int corpus_negate(int x)
{
    return -x;
}
