// One function the main unit calls and one it does not.
// Generated by rucc-corpus. Edit the generator, not this file.

int corpus_wanted(int x)
{
    return x + 8;
}

int corpus_unwanted(int x)
{
    int total = 0;
    for (int i = 0; i < x; i++) {
        total += i * i;
    }
    return total;
}
