// A tiny callee in another unit, called in a loop.
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int corpus_double(int);
static volatile int trips_in = 10;

int main(void) {
    int trips = trips_in;
    int total = 0;
    for (int i = 0; i < trips; i++) {
        total += corpus_double(i);
    }
    printf("%lld\n", (long long)(total));
    return 0;
}
