// A callee that counts its own calls, so the caller can say how many there were.
// Generated by rucc-corpus. Edit the generator, not this file.

static unsigned long long made = (unsigned long long)0ull;

unsigned long long corpus_step(unsigned long long of)
{
    made = (unsigned long long)(made + 1);
    return (unsigned long long)(of * 2);
}

unsigned long long corpus_calls(void)
{
    return made;
}
