// unsigned long long call, writes through an argument
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long counter[2];
static __attribute__((noinline)) unsigned long long bump(unsigned long long *out) {
    out[0] = out[0] + (unsigned long long)1ull;
    return out[1];
}
static volatile unsigned long long seed_in = 6ull;

int main(void) {
    unsigned long long seed = seed_in;

    counter[1] = seed;
    unsigned long long total = 0;
    for (int i = 0; i < 1000; i++) {
        total += bump(counter);
    }

    printf("%llu\n", (unsigned long long)(total));
    printf("%llu\n", (unsigned long long)(counter[0]));
    printf("%llu\n", (unsigned long long)(counter[1]));
    return 0;
}
