// int call in a loop, another unit promises const
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

__attribute__((const)) int corpus_weigh(int of);
static int scratch[4];
static volatile int seed_in = 6;

int main(void) {
    int seed = seed_in;

    int total = 0;
    for (int i = 0; i < 1000; i++) {
        total += corpus_weigh(seed);
        scratch[i & 3] = scratch[i & 3] + (int)1;
    }

    printf("%lld\n", (long long)(total));
    printf("%lld\n", (long long)(scratch[3]));
    return 0;
}
