// A callee that counts its own calls, so the caller can say how many there were.
// Generated by rucc-corpus. Edit the generator, not this file.

static long long made = (long long)0ll;

long long corpus_step(long long of)
{
    made = (long long)(made + 1);
    return (long long)(of * 2);
}

long long corpus_calls(void)
{
    return made;
}
