// A callee that counts its own calls, so the caller can say how many there were.
// Generated by rucc-corpus. Edit the generator, not this file.

static int made = (int)0;

int corpus_step(int of)
{
    made = (int)(made + 1);
    return (int)(of * 2);
}

int corpus_calls(void)
{
    return made;
}
