// setjmp and longjmp, a retry loop
// Generated by rucc-corpus. Edit the generator, not this file.

#include <setjmp.h>

int printf(const char *, ...);

static jmp_buf home;
static void fail_at(int step) { longjmp(home, step); }

int main(void) {

    volatile int attempts = 0;
    volatile int recoveries = 0;
    if (setjmp(home) != 0) {
        recoveries = recoveries + 1;
    }
    attempts = attempts + 1;
    if (attempts < 4) {
        fail_at(attempts);
    }

    printf("%lld\n", (long long)(attempts));
    printf("%lld\n", (long long)(recoveries));
    return 0;
}
