// setjmp and longjmp, unchanged locals survive
// Generated by rucc-corpus. Edit the generator, not this file.

#include <setjmp.h>

int printf(const char *, ...);

static jmp_buf home;
static volatile int noise = 2;

int main(void) {

    int fixed = 40;
    volatile int answer = 0;
    if (setjmp(home) == 0) {
        longjmp(home, 1);
    }
    answer = fixed + noise;

    printf("%lld\n", (long long)(answer));
    printf("%lld\n", (long long)(fixed));
    return 0;
}
