// the static-assert corner of C17
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

_Static_assert(1 + 1 == 2, "arithmetic is broken");
_Static_assert(-1 < 0, "signed is not signed");
enum widths { small = 1, large = 1000 };
_Static_assert(large - small == 999, "enum arithmetic is broken");

int main(void) {

    printf("%lld\n", (long long)((int)large));
    return 0;
}
