// the C23 bool-keyword construct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 1;

int main(void) {
    int seed = seed_in;

    bool yes = true;
    bool no = false;
    bool from_int = seed;

    printf("%lld\n", (long long)((int)yes));
    printf("%lld\n", (long long)((int)no));
    printf("%lld\n", (long long)((int)from_int));
    printf("%lld\n", (long long)((int)(bool)2));
    return 0;
}
