// the compound-literal corner of C17
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct pair { int first; int second; };
static int total(struct pair value) { return value.first + value.second; }

int main(void) {

    int *slice = (int[]){ 4, 5, 6 };

    printf("%lld\n", (long long)(total((struct pair){ 20, 22 })));
    printf("%lld\n", (long long)(slice[0] + slice[1] + slice[2]));
    return 0;
}
