// the C23 typeof construct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 20;

int main(void) {
    int seed = seed_in;

    typeof(seed) same = seed;
    typeof_unqual(seed) also = same + 2;

    printf("%lld\n", (long long)(same + also));
    return 0;
}
