// the bit-fields corner of C17
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct packed { unsigned int low : 3; unsigned int mid : 5; signed int high : 4; };

int main(void) {

    struct packed held;
    held.low = 7;
    held.mid = 31;
    held.high = -8;

    printf("%lld\n", (long long)((int)held.low));
    printf("%lld\n", (long long)((int)held.mid));
    printf("%lld\n", (long long)((int)held.high));
    return 0;
}
