// the generic-selection corner of C17
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

#define name(x) _Generic((x), int: 1, long long: 2, unsigned int: 3, default: 0)

int main(void) {

    int as_int = 0;
    long long as_long = 0;
    unsigned int as_unsigned = 0;
    char as_char = 0;

    printf("%lld\n", (long long)(name(as_int)));
    printf("%lld\n", (long long)(name(as_long)));
    printf("%lld\n", (long long)(name(as_unsigned)));
    printf("%lld\n", (long long)(name(as_char)));
    return 0;
}
