// the flexible-array corner of C17
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct message { int count; int values[]; };
static struct message *storage(void) {
    static union { struct message head; unsigned char space[64]; } backing;
    return &backing.head;
}

int main(void) {

    struct message *held = storage();
    held->count = 3;
    for (int i = 0; i < 3; i++) {
        held->values[i] = i + 1;
    }

    printf("%lld\n", (long long)(held->count));
    printf("%lld\n", (long long)(held->values[0] + held->values[1] + held->values[2]));
    return 0;
}
