// the walk back from a unsigned int load, over-a-loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int value_in = 41u;
static volatile int flag_in = 1;

int main(void) {
    unsigned int value = value_in;
    int flag = flag_in;

    unsigned int one[2];
    unsigned int two[2];
    one[0] = value;
    for (int i = 0; i < 4; i++) {
        two[i & 1] = (unsigned int)i;
    }
    unsigned int read = one[0];

    printf("%llu\n", (unsigned long long)(read));
    return 0;
}
