// the walk back from a int load, merge-at-join
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int value_in = 41;
static volatile int flag_in = 1;

int main(void) {
    int value = value_in;
    int flag = flag_in;

    int one[2];
    if (flag) {
        one[0] = value + (int)1;
    } else {
        one[0] = value;
    }
    int read = one[0];

    printf("%lld\n", (long long)(read));
    return 0;
}
