// the walk back from a long long load, stopped-by-may-alias
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long value_in = 41ll;
static volatile int flag_in = 1;

int main(void) {
    long long value = value_in;
    int flag = flag_in;

    long long one[2];
    long long two[2];
    one[0] = value;
    two[0] = value;
    long long *at = flag ? &one[0] : &two[0];
    *at = value + (long long)1ll;
    long long read = one[0];

    printf("%lld\n", (long long)(read));
    return 0;
}
