// the walk back from a unsigned long long load, merge-at-join
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long value_in = 41ull;
static volatile int flag_in = 1;

int main(void) {
    unsigned long long value = value_in;
    int flag = flag_in;

    unsigned long long one[2];
    if (flag) {
        one[0] = value + (unsigned long long)1ull;
    } else {
        one[0] = value;
    }
    unsigned long long read = one[0];

    printf("%llu\n", (unsigned long long)(read));
    return 0;
}
