// one short read and written against a constant, call-between
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short seed_in = 5;
static volatile int at_in = 3;
static volatile int back_in = 3;
static volatile int noise_count;
static void noise(void) {
    noise_count = noise_count + 1;
}
static void (*volatile jump)(void) = noise;

int main(void) {
    short seed = seed_in;
    int at = at_in;
    int back = back_in;

    short buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (short)i;
    }
    short value = buffer[at];
    jump();
    buffer[at] = value + 5;
    short total = buffer[back];

    printf("%lld\n", (long long)(total));
    return 0;
}
