// one long long read and written against a constant, two-readers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 5ll;
static volatile int at_in = 3;
static volatile int back_in = 3;

int main(void) {
    long long seed = seed_in;
    int at = at_in;
    int back = back_in;

    long long buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (long long)i;
    }
    long long value = buffer[at];
    buffer[at] = value + 5;
    long long total = buffer[back] + value;

    printf("%lld\n", (long long)(total));
    return 0;
}
