// one unsigned short read and written against a constant, other-place
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned short seed_in = 5u;
static volatile int at_in = 3;
static volatile int back_in = 3;
static volatile int other_in = 6;

int main(void) {
    unsigned short seed = seed_in;
    int at = at_in;
    int back = back_in;
    int other = other_in;

    unsigned short buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (unsigned short)i;
    }
    buffer[other] = buffer[at] + 5;
    unsigned short total = buffer[back] + buffer[other];

    printf("%lld\n", (long long)(total));
    return 0;
}
