// one signed char read and written against a constant, two-readers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile signed char seed_in = 5;
static volatile int at_in = 3;
static volatile int back_in = 3;

int main(void) {
    signed char seed = seed_in;
    int at = at_in;
    int back = back_in;

    signed char buffer[8];
    for (int i = 0; i < 8; i++) {
        buffer[i] = seed + (signed char)i;
    }
    signed char value = buffer[at];
    buffer[at] = value + 5;
    signed char total = buffer[back] + value;

    printf("%lld\n", (long long)(total));
    return 0;
}
