// a 1000000 iteration unsigned int loop with a known bound whose total nothing reads
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned int total = 0;
    for (int i = 0; i < 1000000; i++) {
        total += (unsigned int)3u;
    }

    unsigned int aside = 0;
    for (int i = 0; i < 8; i++) {
        aside += (unsigned int)i;
    }

    printf("%llu\n", (unsigned long long)(aside));
    return 0;
}
