// a 100 iteration unsigned int loop with an unknown bound whose total nothing reads
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int limit_in = 100;

int main(void) {
    int limit = limit_in;

    unsigned int total = 0;
    for (int i = 0; i < limit; i++) {
        total += (unsigned int)3u;
    }

    unsigned int aside = 0;
    for (int i = 0; i < 8; i++) {
        aside += (unsigned int)i;
    }

    printf("%llu\n", (unsigned long long)(aside));
    return 0;
}
