// a 100 iteration unsigned long long loop with an unknown bound whose total nothing reads
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int limit_in = 100;

int main(void) {
    int limit = limit_in;

    unsigned long long total = 0;
    for (int i = 0; i < limit; i++) {
        total += (unsigned long long)3ull;
    }

    unsigned long long aside = 0;
    for (int i = 0; i < 8; i++) {
        aside += (unsigned long long)i;
    }

    printf("%llu\n", (unsigned long long)(aside));
    return 0;
}
