// a 16 iteration int loop with an unknown bound whose total nothing reads
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int limit_in = 16;

int main(void) {
    int limit = limit_in;

    int total = 0;
    for (int i = 0; i < limit; i++) {
        total += (int)3;
    }

    int aside = 0;
    for (int i = 0; i < 8; i++) {
        aside += (int)i;
    }

    printf("%lld\n", (long long)(aside));
    return 0;
}
