// one unsigned long long address, computed-index
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int at_in = 3;

int main(void) {
    unsigned long long seed = seed_in;
    int at = at_in;

    unsigned long long buffer[8] = { 0 };
    buffer[at] = seed;
    buffer[at + 1] = seed + (unsigned long long)1ull;
    unsigned long long total = buffer[at] + buffer[at + 1];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
