// one unsigned int address, filled-then-read
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int grid[8];
    for (int i = 0; i < 8; i++) {
        grid[i] = seed + (unsigned int)i;
    }
    unsigned int total = 0;
    for (int i = 0; i < 8; i++) {
        total += grid[i];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
