// one int address, several-offsets
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;

int main(void) {
    int seed = seed_in;

    int buffer[8] = { 0 };
    int *q = &buffer[0];
    q[0] = seed;
    q[3] = seed + (int)1;
    q[7] = seed + (int)2;
    int total = q[0] + q[3] + q[7];

    printf("%lld\n", (long long)(total));
    return 0;
}
