// one unsigned int address, reader-in-another-block
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int at_in = 3;
static volatile int flag_in = 1;

int main(void) {
    unsigned int seed = seed_in;
    int at = at_in;
    int flag = flag_in;

    unsigned int buffer[8] = { 0 };
    unsigned int *q = &buffer[at];
    q[0] = seed;
    if (flag) {
        q[1] = seed + (unsigned int)1u;
    }
    unsigned int total = buffer[3] + buffer[4];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
