// overwritten array stores of unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int buffer[4];
    buffer[0] = seed;
    buffer[0] = seed + (unsigned int)1u;
    buffer[0] = seed + (unsigned int)3u;
    unsigned int slot = buffer[0];

    printf("%llu\n", (unsigned long long)(slot));
    return 0;
}
