// overwritten local stores of unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int slot = seed;
    slot = seed + (unsigned int)1u;
    slot = seed + (unsigned int)2u;
    slot = seed + (unsigned int)3u;

    printf("%llu\n", (unsigned long long)(slot));
    return 0;
}
