// atomic load and store of short at every ordering
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static short cell = 0;

int main(void) {

    short held;
    short want;

    __atomic_store_n(&cell, (short)3, __ATOMIC_RELAXED);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));
    __atomic_store_n(&cell, (short)10, __ATOMIC_RELEASE);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));
    __atomic_store_n(&cell, (short)31, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));

    __atomic_load(&cell, &held, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(held));
    want = (short)9;
    __atomic_store(&cell, &want, __ATOMIC_RELEASE);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    return 0;
}
