// atomic_uint through the header rather than the builtins
// Generated by rucc-corpus. Edit the generator, not this file.

#include <stdatomic.h>

int printf(const char *, ...);

static atomic_uint counter;

int main(void) {

    unsigned int expected;

    atomic_init(&counter, (unsigned int)5u);
    printf("%llu\n", (unsigned long long)(atomic_load_explicit(&counter, memory_order_relaxed)));
    atomic_store_explicit(&counter, (unsigned int)9u, memory_order_release);
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));
    printf("%llu\n", (unsigned long long)(atomic_fetch_add_explicit(&counter, (unsigned int)3u, memory_order_acq_rel)));
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));
    printf("%llu\n", (unsigned long long)(atomic_fetch_sub(&counter, (unsigned int)4u)));
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));

    expected = (unsigned int)8u;
    printf("%lld\n", (long long)(atomic_compare_exchange_strong(&counter, &expected, 20)));
    printf("%llu\n", (unsigned long long)(expected));
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));
    expected = (unsigned int)3u;
    printf("%lld\n", (long long)(atomic_compare_exchange_strong(&counter, &expected, 99)));
    printf("%llu\n", (unsigned long long)(expected));
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));

    while (!atomic_compare_exchange_weak(&counter, &expected, 41)) {
        ;
    }
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));
    printf("%llu\n", (unsigned long long)(atomic_exchange(&counter, (unsigned int)7u)));
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));
    atomic_thread_fence(memory_order_seq_cst);
    atomic_signal_fence(memory_order_acq_rel);
    printf("%llu\n", (unsigned long long)(atomic_load(&counter)));
    return 0;
}
