// atomic exchange and compare exchange of signed char at every ordering
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static signed char cell = 1;

int main(void) {

    signed char expected;
    signed char want;
    signed char got;

    printf("%lld\n", (long long)(__atomic_exchange_n(&cell, (signed char)10, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_exchange_n(&cell, (signed char)11, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_exchange_n(&cell, (signed char)12, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_exchange_n(&cell, (signed char)13, __ATOMIC_RELEASE)));
    printf("%lld\n", (long long)(__atomic_exchange_n(&cell, (signed char)14, __ATOMIC_ACQ_REL)));
    printf("%lld\n", (long long)(__atomic_exchange_n(&cell, (signed char)15, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));

    want = (signed char)7;
    __atomic_exchange(&cell, &want, &got, __ATOMIC_ACQ_REL);
    printf("%lld\n", (long long)(got));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));

    expected = (signed char)7;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (signed char)12, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(expected));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    expected = (signed char)12;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (signed char)17, 0, __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(expected));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    expected = (signed char)17;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (signed char)22, 0, __ATOMIC_RELEASE, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(expected));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));

    expected = (signed char)23;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (signed char)0, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(expected));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    return 0;
}
