// atomic exchange and compare exchange of unsigned long long at every ordering
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned long long cell = 1ull;

int main(void) {

    unsigned long long expected;
    unsigned long long want;
    unsigned long long got;

    printf("%llu\n", (unsigned long long)(__atomic_exchange_n(&cell, (unsigned long long)10ull, __ATOMIC_RELAXED)));
    printf("%llu\n", (unsigned long long)(__atomic_exchange_n(&cell, (unsigned long long)11ull, __ATOMIC_CONSUME)));
    printf("%llu\n", (unsigned long long)(__atomic_exchange_n(&cell, (unsigned long long)12ull, __ATOMIC_ACQUIRE)));
    printf("%llu\n", (unsigned long long)(__atomic_exchange_n(&cell, (unsigned long long)13ull, __ATOMIC_RELEASE)));
    printf("%llu\n", (unsigned long long)(__atomic_exchange_n(&cell, (unsigned long long)14ull, __ATOMIC_ACQ_REL)));
    printf("%llu\n", (unsigned long long)(__atomic_exchange_n(&cell, (unsigned long long)15ull, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));

    want = (unsigned long long)7ull;
    __atomic_exchange(&cell, &want, &got, __ATOMIC_ACQ_REL);
    printf("%llu\n", (unsigned long long)(got));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));

    expected = (unsigned long long)7ull;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (unsigned long long)12ull, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(expected));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    expected = (unsigned long long)12ull;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (unsigned long long)17ull, 0, __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE)));
    printf("%llu\n", (unsigned long long)(expected));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    expected = (unsigned long long)17ull;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (unsigned long long)22ull, 0, __ATOMIC_RELEASE, __ATOMIC_RELAXED)));
    printf("%llu\n", (unsigned long long)(expected));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));

    expected = (unsigned long long)23ull;
    printf("%lld\n", (long long)(__atomic_compare_exchange_n(&cell, &expected, (unsigned long long)0ull, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(expected));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    return 0;
}
