// atomic load and store of int at every ordering
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int cell = 0;

int main(void) {

    int held;
    int want;

    __atomic_store_n(&cell, (int)3, __ATOMIC_RELAXED);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));
    __atomic_store_n(&cell, (int)10, __ATOMIC_RELEASE);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));
    __atomic_store_n(&cell, (int)31, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_SEQ_CST)));

    __atomic_load(&cell, &held, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(held));
    want = (int)9;
    __atomic_store(&cell, &want, __ATOMIC_RELEASE);
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_ACQUIRE)));
    return 0;
}
