// the atomic read modify write family on signed char, both ways round
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static signed char cell = 0;

int main(void) {

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_fetch_add(&cell, (signed char)25, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)25, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_fetch_sub(&cell, (signed char)25, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_sub_fetch(&cell, (signed char)25, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_fetch_and(&cell, (signed char)25, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_and_fetch(&cell, (signed char)25, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_fetch_or(&cell, (signed char)25, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_or_fetch(&cell, (signed char)25, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_fetch_xor(&cell, (signed char)25, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_xor_fetch(&cell, (signed char)25, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_fetch_nand(&cell, (signed char)25, __ATOMIC_SEQ_CST)));
    printf("%lld\n", (long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_nand_fetch(&cell, (signed char)25, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)0, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)1, __ATOMIC_RELAXED)));
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)1, __ATOMIC_CONSUME)));
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)1, __ATOMIC_ACQUIRE)));
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)1, __ATOMIC_RELEASE)));
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)1, __ATOMIC_ACQ_REL)));
    printf("%lld\n", (long long)(__atomic_add_fetch(&cell, (signed char)1, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (signed char)50, __ATOMIC_SEQ_CST);
    printf("%lld\n", (long long)(__atomic_xor_fetch(&cell, (signed char)(-1), __ATOMIC_SEQ_CST)));
    return 0;
}
