// the atomic read modify write family on unsigned short, both ways round
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned short cell = 0u;

int main(void) {

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_fetch_add(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_fetch_sub(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_sub_fetch(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_fetch_and(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_and_fetch(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_fetch_or(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_or_fetch(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_fetch_xor(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_xor_fetch(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_fetch_nand(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));
    printf("%llu\n", (unsigned long long)(__atomic_load_n(&cell, __ATOMIC_RELAXED)));
    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_nand_fetch(&cell, (unsigned short)25u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)0u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)1u, __ATOMIC_RELAXED)));
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)1u, __ATOMIC_CONSUME)));
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)1u, __ATOMIC_ACQUIRE)));
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)1u, __ATOMIC_RELEASE)));
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)1u, __ATOMIC_ACQ_REL)));
    printf("%llu\n", (unsigned long long)(__atomic_add_fetch(&cell, (unsigned short)1u, __ATOMIC_SEQ_CST)));

    __atomic_store_n(&cell, (unsigned short)50u, __ATOMIC_SEQ_CST);
    printf("%llu\n", (unsigned long long)(__atomic_xor_fetch(&cell, (unsigned short)65535u, __ATOMIC_SEQ_CST)));
    return 0;
}
