// an invariant index into a global array, int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int table[8] = {0, 1, 4, 9, 16, 25, 36, 49};
static volatile int which_in = 3;

int main(void) {
    int which = which_in;

    int total = 0;
    for (int i = 0; i < 8; i++) {
        total += (int)(table[which & 7] + i);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
