// a unsigned long long loop reading a global the body writes
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int seed;

static void bump(void) {
    seed++;
}
static volatile int start_in = 3;

int main(void) {
    int start = start_in;

    seed = start;
    unsigned long long total = 0;
    for (int i = 0; i < 8; i++) {
        total += (unsigned long long)seed;
        bump();
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
