// an invariant divide in a unsigned long long loop that always runs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long top_in = 84ull;
static volatile unsigned long long bottom_in = 4ull;
static volatile int bound_in = 8;

int main(void) {
    unsigned long long top = top_in;
    unsigned long long bottom = bottom_in;
    int bound = bound_in;

    unsigned long long total = 0;
    int i = 0;
    do {
        total += top / bottom + (unsigned long long)i;
        i++;
    } while (i < bound);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
