// a cheap invariant in a unsigned int loop with no registers spare
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int a_in = 1u;
static volatile unsigned int b_in = 2u;
static volatile unsigned int c_in = 3u;
static volatile unsigned int d_in = 4u;
static volatile unsigned int e_in = 5u;
static volatile unsigned int f_in = 6u;
static volatile unsigned int g_in = 7u;
static volatile unsigned int h_in = 8u;

int main(void) {
    unsigned int a = a_in;
    unsigned int b = b_in;
    unsigned int c = c_in;
    unsigned int d = d_in;
    unsigned int e = e_in;
    unsigned int f = f_in;
    unsigned int g = g_in;
    unsigned int h = h_in;

    unsigned int total = 0;
    unsigned int v0 = 0;
    unsigned int v1 = 0;
    unsigned int v2 = 0;
    unsigned int v3 = 0;
    unsigned int v4 = 0;
    unsigned int v5 = 0;
    unsigned int v6 = 0;
    unsigned int v7 = 0;
    for (int i = 0; i < 8; i++) {
        v0 += a + (unsigned int)i;
        v1 += b + (unsigned int)i;
        v2 += c + (unsigned int)i;
        v3 += d + (unsigned int)i;
        v4 += e + (unsigned int)i;
        v5 += f + (unsigned int)i;
        v6 += g + (unsigned int)i;
        v7 += h + (unsigned int)i;
        total += a + b;
    }

    total += v0 + v1 + v2 + v3 + v4 + v5 + v6 + v7;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
