// a volatile read a unsigned long long loop must do every iteration
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int watched = 5;

int main(void) {

    unsigned long long total = 0;
    for (int i = 0; i < 8; i++) {
        total += (unsigned long long)(watched + i);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
