// an invariant divide in a long long loop that always runs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long top_in = 84ll;
static volatile long long bottom_in = 4ll;
static volatile int bound_in = 8;

int main(void) {
    long long top = top_in;
    long long bottom = bottom_in;
    int bound = bound_in;

    long long total = 0;
    int i = 0;
    do {
        total += top / bottom + (long long)i;
        i++;
    } while (i < bound);

    printf("%lld\n", (long long)(total));
    return 0;
}
