// an invariant divide in a unsigned int loop that always runs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int top_in = 84u;
static volatile unsigned int bottom_in = 4u;
static volatile int bound_in = 8;

int main(void) {
    unsigned int top = top_in;
    unsigned int bottom = bottom_in;
    int bound = bound_in;

    unsigned int total = 0;
    int i = 0;
    do {
        total += top / bottom + (unsigned int)i;
        i++;
    } while (i < bound);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
