// a int loop that always runs, over a valid pointer
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int bound_in = 8;

int main(void) {
    int bound = bound_in;

    static int cell = 41;
    int *at = bound ? &cell : (int *)0;
    int total = 0;
    int i = 0;
    do {
        total += (int)(*at + i);
        i++;
    } while (i < bound);

    printf("%lld\n", (long long)(total));
    return 0;
}
