// a cheap invariant in a long long loop with no registers spare
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a_in = 1ll;
static volatile long long b_in = 2ll;
static volatile long long c_in = 3ll;
static volatile long long d_in = 4ll;
static volatile long long e_in = 5ll;
static volatile long long f_in = 6ll;
static volatile long long g_in = 7ll;
static volatile long long h_in = 8ll;

int main(void) {
    long long a = a_in;
    long long b = b_in;
    long long c = c_in;
    long long d = d_in;
    long long e = e_in;
    long long f = f_in;
    long long g = g_in;
    long long h = h_in;

    long long total = 0;
    long long v0 = 0;
    long long v1 = 0;
    long long v2 = 0;
    long long v3 = 0;
    long long v4 = 0;
    long long v5 = 0;
    long long v6 = 0;
    long long v7 = 0;
    for (int i = 0; i < 8; i++) {
        v0 += a + (long long)i;
        v1 += b + (long long)i;
        v2 += c + (long long)i;
        v3 += d + (long long)i;
        v4 += e + (long long)i;
        v5 += f + (long long)i;
        v6 += g + (long long)i;
        v7 += h + (long long)i;
        total += a + b;
    }

    total += v0 + v1 + v2 + v3 + v4 + v5 + v6 + v7;

    printf("%lld\n", (long long)(total));
    return 0;
}
