// an invariant call to a pure function, unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int square(int of) {
    return of * of;
}
static volatile int a_in = 3;

int main(void) {
    int a = a_in;

    unsigned long long total = 0;
    for (int i = 0; i < 8; i++) {
        total += (unsigned long long)(square(a) + i);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
