// an invariant value a int loop stores every iteration
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int written;
static volatile int a_in = 3;
static volatile int b_in = 5;

int main(void) {
    int a = a_in;
    int b = b_in;

    int total = 0;
    for (int i = 0; i < 8; i++) {
        written = (int)(a + b);
        total += (int)i;
    }

    printf("%lld\n", (long long)(written));

    printf("%lld\n", (long long)(total));
    return 0;
}
