// fold shr on short operands
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)(((short)1) >> 0));
    printf("%lld\n", (long long)(((short)1) >> 1));
    printf("%lld\n", (long long)(((short)1) >> 3));
    printf("%lld\n", (long long)(((short)1) >> 16));
    printf("%lld\n", (long long)(((short)1) >> 31));
    printf("%lld\n", (long long)(((short)3) >> 0));
    printf("%lld\n", (long long)(((short)3) >> 1));
    printf("%lld\n", (long long)(((short)3) >> 3));
    printf("%lld\n", (long long)(((short)3) >> 16));
    printf("%lld\n", (long long)(((short)3) >> 31));
    printf("%lld\n", (long long)(((short)8) >> 0));
    printf("%lld\n", (long long)(((short)8) >> 1));
    printf("%lld\n", (long long)(((short)8) >> 3));
    printf("%lld\n", (long long)(((short)8) >> 16));
    printf("%lld\n", (long long)(((short)8) >> 31));
    printf("%lld\n", (long long)(((short)255) >> 0));
    printf("%lld\n", (long long)(((short)255) >> 1));
    printf("%lld\n", (long long)(((short)255) >> 3));
    printf("%lld\n", (long long)(((short)255) >> 16));
    printf("%lld\n", (long long)(((short)255) >> 31));
    printf("%lld\n", (long long)(((short)32767) >> 0));
    printf("%lld\n", (long long)(((short)32767) >> 1));
    printf("%lld\n", (long long)(((short)32767) >> 3));
    printf("%lld\n", (long long)(((short)32767) >> 16));
    printf("%lld\n", (long long)(((short)32767) >> 31));
    return 0;
}
