// fold neg on unsigned short operands
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)(-((unsigned short)0u)));
    printf("%lld\n", (long long)(-((unsigned short)1u)));
    printf("%lld\n", (long long)(-((unsigned short)2u)));
    printf("%lld\n", (long long)(-((unsigned short)7u)));
    printf("%lld\n", (long long)(-((unsigned short)8u)));
    printf("%lld\n", (long long)(-((unsigned short)255u)));
    printf("%lld\n", (long long)(-((unsigned short)256u)));
    printf("%lld\n", (long long)(-((unsigned short)65535u)));
    return 0;
}
