// fold shr on unsigned int operands
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%llu\n", (unsigned long long)(((unsigned int)0u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)0u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)0u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)0u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)0u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)1u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)1u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)1u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)1u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)1u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)2u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)2u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)2u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)2u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)2u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)7u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)7u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)7u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)7u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)7u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)8u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)8u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)8u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)8u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)8u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)255u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)255u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)255u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)255u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)255u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)65536u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)65536u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)65536u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)65536u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)65536u) >> 31));
    printf("%llu\n", (unsigned long long)(((unsigned int)4294967295u) >> 0));
    printf("%llu\n", (unsigned long long)(((unsigned int)4294967295u) >> 1));
    printf("%llu\n", (unsigned long long)(((unsigned int)4294967295u) >> 3));
    printf("%llu\n", (unsigned long long)(((unsigned int)4294967295u) >> 16));
    printf("%llu\n", (unsigned long long)(((unsigned int)4294967295u) >> 31));
    return 0;
}
