// fold neg on int operands
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    printf("%lld\n", (long long)(-((int)(-8))));
    printf("%lld\n", (long long)(-((int)(-1))));
    printf("%lld\n", (long long)(-((int)1)));
    printf("%lld\n", (long long)(-((int)3)));
    printf("%lld\n", (long long)(-((int)8)));
    printf("%lld\n", (long long)(-((int)255)));
    printf("%lld\n", (long long)(-((int)2147483647)));
    return 0;
}
