// a function that calls itself
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int factorial(int value) {
    if (value <= 1) {
        return 1;
    }
    return value * factorial(value - 1);
}
static int fibonacci(int value) {
    if (value < 2) {
        return value;
    }
    return fibonacci(value - 1) + fibonacci(value - 2);
}
static volatile int seed_in = 10;

int main(void) {
    int seed = seed_in;

    printf("%lld\n", (long long)(factorial(seed)));
    printf("%lld\n", (long long)(fibonacci(seed)));
    return 0;
}
