// the four operations on ordinary numbers
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 37;
static volatile int b_in = 5;

int main(void) {
    int a = a_in;
    int b = b_in;

    printf("%lld\n", (long long)(a + b));
    printf("%lld\n", (long long)(a - b));
    printf("%lld\n", (long long)(a * b));
    printf("%lld\n", (long long)(a / b));
    printf("%lld\n", (long long)(a % b));
    return 0;
}
