// members, nesting and assignment of a whole struct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct point { int x; int y; };
struct line { struct point from; struct point to; };
static volatile int seed_in = 2;

int main(void) {
    int seed = seed_in;

    struct line edge;
    edge.from.x = seed;
    edge.from.y = seed * 2;
    edge.to.x = seed * 3;
    edge.to.y = seed * 4;
    struct point copied = edge.to;

    printf("%lld\n", (long long)(edge.from.x + edge.from.y));
    printf("%lld\n", (long long)(copied.x + copied.y));
    return 0;
}
