// a unsigned long long callee in another file, the same argument twice, promise silent
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

unsigned long long corpus_weigh(unsigned long long of);
static volatile unsigned long long seed_in = 3ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long total = 0;
    total += corpus_weigh(seed);
    total += corpus_weigh(seed);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
