// __builtin_sub_overflow of __int128 and unsigned short into signed char
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile __int128 lhs[5] = { (-(__int128)(((unsigned __int128)9223372036854775807ull << 64) | 18446744073709551615ull) - 1), (-1ll), 0ull, 1ull, (((unsigned __int128)9223372036854775807ull << 64) | 18446744073709551615ull) };
static volatile unsigned short rhs[5] = { 0ull, 1ull, 32768ull, 65534ull, 65535ull };

int main(void) {
    signed char result;
    int flag;

    flag = __builtin_sub_overflow(lhs[0], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[1], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[2], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[3], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[4], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    return 0;
}
