// __builtin_add_overflow of long long and unsigned char into unsigned __int128
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long lhs[5] = { (-9223372036854775807ll - 1), (-1ll), 0ull, 1ull, 9223372036854775807ull };
static volatile unsigned char rhs[5] = { 0ull, 1ull, 128ull, 254ull, 255ull };

int main(void) {
    unsigned __int128 result;
    int flag;

    flag = __builtin_add_overflow(lhs[0], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[1], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[2], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[3], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[4], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)((unsigned __int128)result >> 64));
    printf("%llu\n", (unsigned long long)(result));
    return 0;
}
