// __builtin_sub_overflow of signed char and signed char into signed char
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile signed char lhs[5] = { (-128ll), (-1ll), 0ull, 1ull, 127ull };
static volatile signed char rhs[5] = { (-128ll), (-1ll), 0ull, 1ull, 127ull };

int main(void) {
    signed char result;
    int flag;

    flag = __builtin_sub_overflow(lhs[0], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[1], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[2], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[3], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[4], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    return 0;
}
