// __builtin_sub_overflow of short and unsigned long into int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short lhs[5] = { (-32768ll), (-1ll), 0ull, 1ull, 32767ull };
static volatile unsigned long rhs[5] = { 0ull, 1ull, 9223372036854775808ull, 18446744073709551614ull, 18446744073709551615ull };

int main(void) {
    int result;
    int flag;

    flag = __builtin_sub_overflow(lhs[0], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[0], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[1], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[1], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[2], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[2], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[3], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[3], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_sub_overflow(lhs[4], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_sub_overflow(lhs[4], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    return 0;
}
