// __builtin_mul_overflow of int and unsigned int into int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int lhs[5] = { (-2147483648ll), (-65536ll), (-1ll), 32768ull, 65536ull };
static volatile unsigned int rhs[5] = { 1ull, 65535ull, 65536ull, 65537ull, 4294967295ull };

int main(void) {
    int result;
    int flag;

    flag = __builtin_mul_overflow(lhs[0], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[0], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[0], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[0], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[0], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_mul_overflow(lhs[1], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[1], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[1], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[1], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[1], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_mul_overflow(lhs[2], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[2], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[2], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[2], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[2], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_mul_overflow(lhs[3], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[3], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[3], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[3], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[3], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));

    flag = __builtin_mul_overflow(lhs[4], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[4], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[4], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[4], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    flag = __builtin_mul_overflow(lhs[4], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%lld\n", (long long)(result));
    return 0;
}
