// __builtin_add_overflow of unsigned long long and unsigned long long into unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long lhs[5] = { 0ull, 1ull, 9223372036854775808ull, 18446744073709551614ull, 18446744073709551615ull };
static volatile unsigned long long rhs[5] = { 0ull, 1ull, 9223372036854775808ull, 18446744073709551614ull, 18446744073709551615ull };

int main(void) {
    unsigned long long result;
    int flag;

    flag = __builtin_add_overflow(lhs[0], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[0], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[1], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[1], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[2], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[2], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[3], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[3], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));

    flag = __builtin_add_overflow(lhs[4], rhs[0], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[1], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[2], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[3], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    flag = __builtin_add_overflow(lhs[4], rhs[4], &result);
    printf("%lld\n", (long long)(flag));
    printf("%llu\n", (unsigned long long)(result));
    return 0;
}
