// a loop-with-no-exit shape, which the analyses have to fit
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static void spin(void) {
    for (;;) {
    }
}
static volatile int never_in = 0;

int main(void) {
    int never = never_in;

    int total = 1;
    if (never) {
        spin();
        total = 100;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
