// a computed-goto shape, which the analyses have to fit
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int pick_in = 2;

int main(void) {
    int pick = pick_in;

    void *targets[4];
    targets[0] = &&zero;
    targets[1] = &&one;
    targets[2] = &&two;
    targets[3] = &&three;
    int total = 0;
    goto *targets[pick & 3];
    zero:
        total += 1;
        goto done;
    one:
        total += 2;
        goto done;
    two:
        total += 4;
        goto done;
    three:
        total += 8;
    done:
        total += 100;

    printf("%lld\n", (long long)(total));
    return 0;
}
