// a nested-five-deep shape, which the analyses have to fit
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {
    int total = 0;
    for (int i0 = 0; i0 < 3; i0++) {
        for (int i1 = 0; i1 < 3; i1++) {
            for (int i2 = 0; i2 < 3; i2++) {
                for (int i3 = 0; i3 < 3; i3++) {
                    for (int i4 = 0; i4 < 3; i4++) {
                        total += i0 + i1 + i2 + i3 + i4;
                    }
                }
            }
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
