// a switch-shared-arms shape, which the analyses have to fit
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int pick_in = 3;

int main(void) {
    int pick = pick_in;

    int total = 0;
    switch (pick) {
        case 0:
        case 1:
            total = 10;
            break;
        case 2:
        case 3:
        default:
            total = 20;
            break;
    }
    switch (pick) {
        case 3:
            total += 1;
            /* falls through */
        case 4:
            total += 2;
            break;
        default:
            total += 100;
            break;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
