// a many-returns shape, which the analyses have to fit
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static int classify(int value) {
    if (value < 0) return 1;
    if (value == 0) return 2;
    if (value < 10) return 3;
    if (value < 100) return 4;
    return 5;
}
static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    printf("%lld\n", (long long)(classify(-seed)));
    printf("%lld\n", (long long)(classify(0)));
    printf("%lld\n", (long long)(classify(seed)));
    printf("%lld\n", (long long)(classify(seed * 7)));
    printf("%lld\n", (long long)(classify(seed * 100)));
    return 0;
}
