// hoist-past-store for unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a_in = 4ull;
static volatile unsigned long long b_in = 9ull;
static volatile int flag_in = 0;

int main(void) {
    unsigned long long a = a_in;
    unsigned long long b = b_in;
    int flag = flag_in;

    unsigned long long scratch[2];
    scratch[0] = a;
    unsigned long long product = a * b;
    scratch[1] = b;
    unsigned long long total = product + (unsigned long long)1ull;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
