// hoist-from-both-arms for int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 4;
static volatile int b_in = 9;
static volatile int flag_in = 0;

int main(void) {
    int a = a_in;
    int b = b_in;
    int flag = flag_in;

    int total;
    if (flag) {
        total = a * b + (int)1;
    } else {
        total = a * b + (int)1;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
