// a calls function with 8 locals, an array of 256 and 4 structs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct record {
    unsigned long long key;
    unsigned int vals[6];
    unsigned short tag;
    unsigned char name[21];
};
__attribute__((noinline))
static unsigned long long sum_words(const unsigned int *p, int n) {
    unsigned long long s = 0;
    for (int i = 0; i < n; i++) {
        s = s * 33 + p[i];
    }
    return s;
}
__attribute__((noinline))
static unsigned long long mix_record(struct record *r) {
    r->tag = (unsigned short)(r->tag + 1);
    unsigned long long s = r->key;
    for (int i = 0; i < 6; i++) {
        s = s * 7 + r->vals[i];
    }
    for (int i = 0; i < 21; i++) {
        s = s + r->name[i];
    }
    return s + r->tag;
}
__attribute__((noinline))
static unsigned long long touch(unsigned long long a, unsigned long long b) {
    return a * 3 + b;
}
__attribute__((noinline))
static unsigned long long frame_fn(unsigned long long seed, int depth) {
    unsigned long long l0 = seed * 3 + 1;
    unsigned long long l1 = l0 * 5 + 1;
    unsigned long long l2 = l1 * 7 + 2;
    unsigned long long l3 = l2 * 9 + 3;
    unsigned long long l4 = l3 * 11 + 4;
    unsigned long long l5 = l4 * 13 + 5;
    unsigned long long l6 = l5 * 15 + 6;
    unsigned long long l7 = l6 * 17 + 7;
    unsigned int arr[256];
    for (int i = 0; i < 256; i++) {
        arr[i] = (unsigned int)(seed + (unsigned long long)i * 2654435761u);
    }
    struct record r0;
    r0.key = l0 + 0;
    for (int i = 0; i < 6; i++) {
        r0.vals[i] = (unsigned int)(l1 + 7 * (unsigned long long)i);
    }
    r0.tag = 1;
    for (int i = 0; i < 21; i++) {
        r0.name[i] = (unsigned char)(seed + i * 3);
    }
    struct record r1;
    r1.key = l1 + 1;
    for (int i = 0; i < 6; i++) {
        r1.vals[i] = (unsigned int)(l2 + 7 * (unsigned long long)i);
    }
    r1.tag = 2;
    for (int i = 0; i < 21; i++) {
        r1.name[i] = (unsigned char)(seed + i * 4);
    }
    struct record r2;
    r2.key = l2 + 2;
    for (int i = 0; i < 6; i++) {
        r2.vals[i] = (unsigned int)(l3 + 7 * (unsigned long long)i);
    }
    r2.tag = 3;
    for (int i = 0; i < 21; i++) {
        r2.name[i] = (unsigned char)(seed + i * 5);
    }
    struct record r3;
    r3.key = l3 + 3;
    for (int i = 0; i < 6; i++) {
        r3.vals[i] = (unsigned int)(l4 + 7 * (unsigned long long)i);
    }
    r3.tag = 4;
    for (int i = 0; i < 21; i++) {
        r3.name[i] = (unsigned char)(seed + i * 6);
    }
    unsigned long long acc = 0;
    acc = acc + sum_words(arr, 256);
    acc = acc + mix_record(&r0);
    acc = acc + mix_record(&r1);
    acc = acc + mix_record(&r2);
    acc = acc + mix_record(&r3);
    acc = touch(acc, l0);
    (void)depth;
    acc = acc * 31 + l7;
    acc = acc * 31 + l6;
    acc = acc * 31 + l5;
    acc = acc * 31 + l4;
    acc = acc * 31 + l3;
    acc = acc * 31 + l2;
    acc = acc * 31 + l1;
    acc = acc * 31 + l0;
    acc = acc + arr[255] + arr[128];
    acc = acc * 31 + r0.key + r0.tag + r0.vals[5] + r0.name[20];
    acc = acc * 31 + r1.key + r1.tag + r1.vals[5] + r1.name[20];
    acc = acc * 31 + r2.key + r2.tag + r2.vals[5] + r2.name[20];
    acc = acc * 31 + r3.key + r3.tag + r3.vals[5] + r3.name[20];
    return acc;
}
static volatile unsigned long long seed_in = 20250928ull;

int main(void) {
    unsigned long long seed = seed_in;
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 0, 0)));
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 1, 0)));
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 2, 0)));
    return 0;
}
