// a recursive function with 32 locals, an array of 256 and 0 structs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

__attribute__((noinline))
static unsigned long long sum_words(const unsigned int *p, int n) {
    unsigned long long s = 0;
    for (int i = 0; i < n; i++) {
        s = s * 33 + p[i];
    }
    return s;
}
__attribute__((noinline))
static unsigned long long touch(unsigned long long a, unsigned long long b) {
    return a * 3 + b;
}
__attribute__((noinline))
static unsigned long long frame_fn(unsigned long long seed, int depth) {
    unsigned long long l0 = seed * 3 + 1;
    unsigned long long l1 = l0 * 5 + 1;
    unsigned long long l2 = l1 * 7 + 2;
    unsigned long long l3 = l2 * 9 + 3;
    unsigned long long l4 = l3 * 11 + 4;
    unsigned long long l5 = l4 * 13 + 5;
    unsigned long long l6 = l5 * 15 + 6;
    unsigned long long l7 = l6 * 17 + 7;
    unsigned long long l8 = l7 * 19 + 8;
    unsigned long long l9 = l8 * 21 + 9;
    unsigned long long l10 = l9 * 23 + 10;
    unsigned long long l11 = l10 * 25 + 11;
    unsigned long long l12 = l11 * 27 + 12;
    unsigned long long l13 = l12 * 29 + 13;
    unsigned long long l14 = l13 * 31 + 14;
    unsigned long long l15 = l14 * 33 + 15;
    unsigned long long l16 = l15 * 35 + 16;
    unsigned long long l17 = l16 * 37 + 17;
    unsigned long long l18 = l17 * 39 + 18;
    unsigned long long l19 = l18 * 41 + 19;
    unsigned long long l20 = l19 * 43 + 20;
    unsigned long long l21 = l20 * 45 + 21;
    unsigned long long l22 = l21 * 47 + 22;
    unsigned long long l23 = l22 * 49 + 23;
    unsigned long long l24 = l23 * 51 + 24;
    unsigned long long l25 = l24 * 53 + 25;
    unsigned long long l26 = l25 * 55 + 26;
    unsigned long long l27 = l26 * 57 + 27;
    unsigned long long l28 = l27 * 59 + 28;
    unsigned long long l29 = l28 * 61 + 29;
    unsigned long long l30 = l29 * 63 + 30;
    unsigned long long l31 = l30 * 65 + 31;
    unsigned int arr[256];
    for (int i = 0; i < 256; i++) {
        arr[i] = (unsigned int)(seed + (unsigned long long)i * 2654435761u);
    }
    unsigned long long acc = 0;
    acc = acc + sum_words(arr, 256);
    acc = touch(acc, l0);
    if (depth > 0) {
        acc = acc + frame_fn(seed + 1, depth - 1);
    }
    acc = acc * 31 + l31;
    acc = acc * 31 + l30;
    acc = acc * 31 + l29;
    acc = acc * 31 + l28;
    acc = acc * 31 + l27;
    acc = acc * 31 + l26;
    acc = acc * 31 + l25;
    acc = acc * 31 + l24;
    acc = acc * 31 + l23;
    acc = acc * 31 + l22;
    acc = acc * 31 + l21;
    acc = acc * 31 + l20;
    acc = acc * 31 + l19;
    acc = acc * 31 + l18;
    acc = acc * 31 + l17;
    acc = acc * 31 + l16;
    acc = acc * 31 + l15;
    acc = acc * 31 + l14;
    acc = acc * 31 + l13;
    acc = acc * 31 + l12;
    acc = acc * 31 + l11;
    acc = acc * 31 + l10;
    acc = acc * 31 + l9;
    acc = acc * 31 + l8;
    acc = acc * 31 + l7;
    acc = acc * 31 + l6;
    acc = acc * 31 + l5;
    acc = acc * 31 + l4;
    acc = acc * 31 + l3;
    acc = acc * 31 + l2;
    acc = acc * 31 + l1;
    acc = acc * 31 + l0;
    acc = acc + arr[255] + arr[128];
    return acc;
}
static volatile unsigned long long seed_in = 20250928ull;

int main(void) {
    unsigned long long seed = seed_in;
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 0, 3)));
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 1, 3)));
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 2, 3)));
    return 0;
}
