// a recursive function with 8 locals, an array of 256 and 0 structs
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

__attribute__((noinline))
static unsigned long long sum_words(const unsigned int *p, int n) {
    unsigned long long s = 0;
    for (int i = 0; i < n; i++) {
        s = s * 33 + p[i];
    }
    return s;
}
__attribute__((noinline))
static unsigned long long touch(unsigned long long a, unsigned long long b) {
    return a * 3 + b;
}
__attribute__((noinline))
static unsigned long long frame_fn(unsigned long long seed, int depth) {
    unsigned long long l0 = seed * 3 + 1;
    unsigned long long l1 = l0 * 5 + 1;
    unsigned long long l2 = l1 * 7 + 2;
    unsigned long long l3 = l2 * 9 + 3;
    unsigned long long l4 = l3 * 11 + 4;
    unsigned long long l5 = l4 * 13 + 5;
    unsigned long long l6 = l5 * 15 + 6;
    unsigned long long l7 = l6 * 17 + 7;
    unsigned int arr[256];
    for (int i = 0; i < 256; i++) {
        arr[i] = (unsigned int)(seed + (unsigned long long)i * 2654435761u);
    }
    unsigned long long acc = 0;
    acc = acc + sum_words(arr, 256);
    acc = touch(acc, l0);
    if (depth > 0) {
        acc = acc + frame_fn(seed + 1, depth - 1);
    }
    acc = acc * 31 + l7;
    acc = acc * 31 + l6;
    acc = acc * 31 + l5;
    acc = acc * 31 + l4;
    acc = acc * 31 + l3;
    acc = acc * 31 + l2;
    acc = acc * 31 + l1;
    acc = acc * 31 + l0;
    acc = acc + arr[255] + arr[128];
    return acc;
}
static volatile unsigned long long seed_in = 20250928ull;

int main(void) {
    unsigned long long seed = seed_in;
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 0, 3)));
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 1, 3)));
    printf("%llu\n", (unsigned long long)(frame_fn(seed + 2, 3)));
    return 0;
}
