// inlined-callees after lib/vsprintf.c in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

__attribute__((noinline))
static unsigned int consume(unsigned int *buf, unsigned int n, unsigned int x) {
    unsigned int s = x;
    for (unsigned int k = 0; k < n; k++) {
        buf[k] = buf[k] * 2654435761u + s;
        s = (s ^ buf[k]) * 16777619u;
    }
    return s;
}

static inline __attribute__((always_inline))
unsigned int part_a(unsigned int x) {
    unsigned int buf[160];
    for (unsigned int k = 0; k < 160u; k++) {
        buf[k] = x + k * 3u;
    }
    return consume(buf, 160u, x);
}

static inline __attribute__((always_inline))
unsigned int part_b(unsigned int x) {
    unsigned int buf[160];
    for (unsigned int k = 0; k < 160u; k++) {
        buf[k] = x + k * 5u;
    }
    return consume(buf, 160u, x);
}

static inline __attribute__((always_inline))
unsigned int part_c(unsigned int x) {
    unsigned int buf[160];
    for (unsigned int k = 0; k < 160u; k++) {
        buf[k] = x + k * 7u;
    }
    return consume(buf, 160u, x);
}

static inline __attribute__((always_inline))
unsigned int part_d(unsigned int x) {
    unsigned int buf[160];
    for (unsigned int k = 0; k < 160u; k++) {
        buf[k] = x + k * 11u;
    }
    return consume(buf, 160u, x);
}

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    x = part_a(x);
    x = part_b(x ^ i);
    x = part_c(x + i);
    return part_d(x);
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
