// disjoint-scopes after fs/select.c in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

__attribute__((noinline))
static unsigned int consume(unsigned int *buf, unsigned int n, unsigned int x) {
    unsigned int s = x;
    for (unsigned int k = 0; k < n; k++) {
        buf[k] = buf[k] * 2654435761u + s;
        s = (s ^ buf[k]) * 16777619u;
    }
    return s;
}

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    if (i & 1u) {
        unsigned int a[160];
        for (unsigned int k = 0; k < 160u; k++) {
            a[k] = x + k * 3u;
        }
        x = consume(a, 160u, x);
    }
    if (i & 2u) {
        unsigned int b[160];
        for (unsigned int k = 0; k < 160u; k++) {
            b[k] = x + k * 5u;
        }
        x = consume(b, 160u, x);
    }
    if (i & 4u) {
        unsigned int c[160];
        for (unsigned int k = 0; k < 160u; k++) {
            c[k] = x + k * 7u;
        }
        x = consume(c, 160u, x);
    }
    {
        unsigned int d[160];
        for (unsigned int k = 0; k < 160u; k++) {
            d[k] = x + k * 11u;
        }
        x = consume(d, 160u, x);
    }
    return x + i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
