// a 2 iteration unsigned long long loop with an unknown trip count
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int limit_in = 2;

int main(void) {
    int limit = limit_in;

    unsigned long long total = 0;
    for (int i = 0; i < limit; i++) {
        total += (unsigned long long)(i * 3 + 1);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
