// a 4 iteration long long loop with an unknown trip count
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int limit_in = 4;

int main(void) {
    int limit = limit_in;

    long long total = 0;
    for (int i = 0; i < limit; i++) {
        total += (long long)(i * 3 + 1);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
