// backward after arch/x86/lib/delay.c in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    unsigned int n = (i & 7u) + 1u;
    __asm__("1:\n\taddl %2, %0\n\tdecl %1\n\tjnz 1b"
        : "+r"(x), "+r"(n) : "r"(i | 1u) : "cc");
    return x;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
