// forward after arch/x86/include/asm/bitops.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    __asm__("testl %1, %1\n\tjz 1f\n\txorl %1, %0\n1:"
        : "+r"(x) : "r"(i & 3u) : "cc");
    return x * 3u + i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
