// cast-conditional after include/linux/limits.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

#define U8_MAX ((unsigned char)~0u)
#define S8_MAX ((signed char)(U8_MAX >> 1))
#define S8_MIN ((signed char)(-S8_MAX - 1))
#define U16_MAX ((unsigned short)~0u)
#define S16_MAX ((short)(U16_MAX >> 1))
#define S16_MIN ((short)(-S16_MAX - 1))

struct rk_req {
    unsigned int op;
    unsigned int flags;
    unsigned char key[8];
    unsigned char data[16];
};

enum {
    RK_TRUNC = (int)6.75,
    RK_BOOL = (_Bool)42,
    RK_PICK = sizeof(struct rk_req) > 16 ? 3 : 5,
    RK_NESTED = (1 ? (unsigned char)300 : 7) + (0 ? 1 : RK_TRUNC),
};

_Static_assert(U8_MAX == 255 && S8_MIN == -128, "the byte limits");
_Static_assert(U16_MAX == 65535 && S16_MIN == -32768, "the short limits");

static unsigned int table[RK_PICK + RK_BOOL];

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    table[x % (RK_PICK + RK_BOOL)] += i;
    switch ((x ^ i) & 7u) {
    case RK_BOOL:
        x += U8_MAX;
        break;
    case RK_PICK:
        x ^= U16_MAX;
        break;
    case RK_TRUNC:
        x -= S8_MIN;
        break;
    case (unsigned char)0x105:
        x += (unsigned int)S16_MIN;
        break;
    default:
        x += RK_NESTED;
        break;
    }
    return x * 3u + table[i % (RK_PICK + RK_BOOL)] + i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
