// 8 live unsigned long long values at once, straight
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 1ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long v0 = seed + (unsigned long long)0ull;
    unsigned long long v1 = seed + (unsigned long long)1ull;
    unsigned long long v2 = seed + (unsigned long long)2ull;
    unsigned long long v3 = seed + (unsigned long long)3ull;
    unsigned long long v4 = seed + (unsigned long long)4ull;
    unsigned long long v5 = seed + (unsigned long long)5ull;
    unsigned long long v6 = seed + (unsigned long long)6ull;
    unsigned long long v7 = seed + (unsigned long long)7ull;

    unsigned long long total = 0;
    total += v7;
    total += v6;
    total += v5;
    total += v4;
    total += v3;
    total += v2;
    total += v1;
    total += v0;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
