// 16 live unsigned int values at once, straight
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 1u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int v0 = seed + (unsigned int)0u;
    unsigned int v1 = seed + (unsigned int)1u;
    unsigned int v2 = seed + (unsigned int)2u;
    unsigned int v3 = seed + (unsigned int)3u;
    unsigned int v4 = seed + (unsigned int)4u;
    unsigned int v5 = seed + (unsigned int)5u;
    unsigned int v6 = seed + (unsigned int)6u;
    unsigned int v7 = seed + (unsigned int)7u;
    unsigned int v8 = seed + (unsigned int)8u;
    unsigned int v9 = seed + (unsigned int)9u;
    unsigned int v10 = seed + (unsigned int)10u;
    unsigned int v11 = seed + (unsigned int)11u;
    unsigned int v12 = seed + (unsigned int)12u;
    unsigned int v13 = seed + (unsigned int)13u;
    unsigned int v14 = seed + (unsigned int)14u;
    unsigned int v15 = seed + (unsigned int)15u;

    unsigned int total = 0;
    total += v15;
    total += v14;
    total += v13;
    total += v12;
    total += v11;
    total += v10;
    total += v9;
    total += v8;
    total += v7;
    total += v6;
    total += v5;
    total += v4;
    total += v3;
    total += v2;
    total += v1;
    total += v0;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
