// 32 live unsigned long long values at once, in-a-loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 1ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long v0 = seed + (unsigned long long)0ull;
    unsigned long long v1 = seed + (unsigned long long)1ull;
    unsigned long long v2 = seed + (unsigned long long)2ull;
    unsigned long long v3 = seed + (unsigned long long)3ull;
    unsigned long long v4 = seed + (unsigned long long)4ull;
    unsigned long long v5 = seed + (unsigned long long)5ull;
    unsigned long long v6 = seed + (unsigned long long)6ull;
    unsigned long long v7 = seed + (unsigned long long)7ull;
    unsigned long long v8 = seed + (unsigned long long)8ull;
    unsigned long long v9 = seed + (unsigned long long)9ull;
    unsigned long long v10 = seed + (unsigned long long)10ull;
    unsigned long long v11 = seed + (unsigned long long)11ull;
    unsigned long long v12 = seed + (unsigned long long)12ull;
    unsigned long long v13 = seed + (unsigned long long)13ull;
    unsigned long long v14 = seed + (unsigned long long)14ull;
    unsigned long long v15 = seed + (unsigned long long)15ull;
    unsigned long long v16 = seed + (unsigned long long)16ull;
    unsigned long long v17 = seed + (unsigned long long)17ull;
    unsigned long long v18 = seed + (unsigned long long)18ull;
    unsigned long long v19 = seed + (unsigned long long)19ull;
    unsigned long long v20 = seed + (unsigned long long)20ull;
    unsigned long long v21 = seed + (unsigned long long)21ull;
    unsigned long long v22 = seed + (unsigned long long)22ull;
    unsigned long long v23 = seed + (unsigned long long)23ull;
    unsigned long long v24 = seed + (unsigned long long)24ull;
    unsigned long long v25 = seed + (unsigned long long)25ull;
    unsigned long long v26 = seed + (unsigned long long)26ull;
    unsigned long long v27 = seed + (unsigned long long)27ull;
    unsigned long long v28 = seed + (unsigned long long)28ull;
    unsigned long long v29 = seed + (unsigned long long)29ull;
    unsigned long long v30 = seed + (unsigned long long)30ull;
    unsigned long long v31 = seed + (unsigned long long)31ull;

    unsigned long long total = 0;
    for (int i = 0; i < 4; i++) {
        total += v31;
        total += v30;
        total += v29;
        total += v28;
        total += v27;
        total += v26;
        total += v25;
        total += v24;
        total += v23;
        total += v22;
        total += v21;
        total += v20;
        total += v19;
        total += v18;
        total += v17;
        total += v16;
        total += v15;
        total += v14;
        total += v13;
        total += v12;
        total += v11;
        total += v10;
        total += v9;
        total += v8;
        total += v7;
        total += v6;
        total += v5;
        total += v4;
        total += v3;
        total += v2;
        total += v1;
        total += v0;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
