// 4 live long long values at once, in-a-loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 1ll;

int main(void) {
    long long seed = seed_in;

    long long v0 = seed + (long long)0ll;
    long long v1 = seed + (long long)1ll;
    long long v2 = seed + (long long)2ll;
    long long v3 = seed + (long long)3ll;

    long long total = 0;
    for (int i = 0; i < 4; i++) {
        total += v3;
        total += v2;
        total += v1;
        total += v0;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
