// 32 live int values at once, straight
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 1;

int main(void) {
    int seed = seed_in;

    int v0 = seed + (int)0;
    int v1 = seed + (int)1;
    int v2 = seed + (int)2;
    int v3 = seed + (int)3;
    int v4 = seed + (int)4;
    int v5 = seed + (int)5;
    int v6 = seed + (int)6;
    int v7 = seed + (int)7;
    int v8 = seed + (int)8;
    int v9 = seed + (int)9;
    int v10 = seed + (int)10;
    int v11 = seed + (int)11;
    int v12 = seed + (int)12;
    int v13 = seed + (int)13;
    int v14 = seed + (int)14;
    int v15 = seed + (int)15;
    int v16 = seed + (int)16;
    int v17 = seed + (int)17;
    int v18 = seed + (int)18;
    int v19 = seed + (int)19;
    int v20 = seed + (int)20;
    int v21 = seed + (int)21;
    int v22 = seed + (int)22;
    int v23 = seed + (int)23;
    int v24 = seed + (int)24;
    int v25 = seed + (int)25;
    int v26 = seed + (int)26;
    int v27 = seed + (int)27;
    int v28 = seed + (int)28;
    int v29 = seed + (int)29;
    int v30 = seed + (int)30;
    int v31 = seed + (int)31;

    int total = 0;
    total += v31;
    total += v30;
    total += v29;
    total += v28;
    total += v27;
    total += v26;
    total += v25;
    total += v24;
    total += v23;
    total += v22;
    total += v21;
    total += v20;
    total += v19;
    total += v18;
    total += v17;
    total += v16;
    total += v15;
    total += v14;
    total += v13;
    total += v12;
    total += v11;
    total += v10;
    total += v9;
    total += v8;
    total += v7;
    total += v6;
    total += v5;
    total += v4;
    total += v3;
    total += v2;
    total += v1;
    total += v0;

    printf("%lld\n", (long long)(total));
    return 0;
}
