// 8 live int values at once, in-a-loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 1;

int main(void) {
    int seed = seed_in;

    int v0 = seed + (int)0;
    int v1 = seed + (int)1;
    int v2 = seed + (int)2;
    int v3 = seed + (int)3;
    int v4 = seed + (int)4;
    int v5 = seed + (int)5;
    int v6 = seed + (int)6;
    int v7 = seed + (int)7;

    int total = 0;
    for (int i = 0; i < 4; i++) {
        total += v7;
        total += v6;
        total += v5;
        total += v4;
        total += v3;
        total += v2;
        total += v1;
        total += v0;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
