// 16 live long long values at once, straight
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 1ll;

int main(void) {
    long long seed = seed_in;

    long long v0 = seed + (long long)0ll;
    long long v1 = seed + (long long)1ll;
    long long v2 = seed + (long long)2ll;
    long long v3 = seed + (long long)3ll;
    long long v4 = seed + (long long)4ll;
    long long v5 = seed + (long long)5ll;
    long long v6 = seed + (long long)6ll;
    long long v7 = seed + (long long)7ll;
    long long v8 = seed + (long long)8ll;
    long long v9 = seed + (long long)9ll;
    long long v10 = seed + (long long)10ll;
    long long v11 = seed + (long long)11ll;
    long long v12 = seed + (long long)12ll;
    long long v13 = seed + (long long)13ll;
    long long v14 = seed + (long long)14ll;
    long long v15 = seed + (long long)15ll;

    long long total = 0;
    total += v15;
    total += v14;
    total += v13;
    total += v12;
    total += v11;
    total += v10;
    total += v9;
    total += v8;
    total += v7;
    total += v6;
    total += v5;
    total += v4;
    total += v3;
    total += v2;
    total += v1;
    total += v0;

    printf("%lld\n", (long long)(total));
    return 0;
}
