// an interpreter of 32 opcodes with 24 values alive, dispatched through the label table from steps read through the state and checked against a switch
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

struct exprstate {
    unsigned long long seed;
    unsigned int loops;
    unsigned long long out[8];
    struct step *steps;
};

struct step {
    int opcode;
    int arg;
    int jump;
    unsigned long long pad[6];
};

static const unsigned long long data[64] = {
    0x9e3779b843248f67ull, 0x3c6ef37286491ecfull, 0xdaa66d2dc893ae67ull, 0x78dde6e50c923d9full,
    0x1715609f525ead57ull, 0xb54cda5991275ccfull, 0x53845412dc01ccb7ull, 0xf1bbcdca19247b3full,
    0x8ff347846678d3b7ull, 0x2e2ac13ea4bd5aafull, 0xcc623af9e0f72117ull, 0x6a99b4b1224eb99full,
    0x08d12e6b676a11c7ull, 0xa708a825b803996full, 0x454021deffdd0687ull, 0xe3779b963248f67full,
    0x81af155070ac17c7ull, 0x1fe68f0accf1a76full, 0xbe1e08c50ebb2407ull, 0x5c55827d497ab55full,
    0xfa8cfc368405d5d7ull, 0x98c475f1c1ee422full, 0x36fbefaa0246fab7ull, 0xd5336962449d733full,
    0x736ae31d8893d837ull, 0x11a25cd6ced4238full, 0xafd9d6913368bb17ull, 0x4e115049700732dfull,
    0xec48ca02b3e19a67ull, 0x8a8043bdffba0d0full, 0x28b7bd763b6a7c67ull, 0xc6ef372e6491ecffull,
    0x6526b0e9a2d49f67ull, 0x035e2aa2e1582f8full, 0xa195a45d2405be67ull, 0x3fcd1e1599e34edfull,
    0xde0497ced9cac097ull, 0x7c3c11881d76480full, 0x1a738b4250bff1b7ull, 0xb8ab04fa92f56abfull,
    0x56e27eb5cf292237ull, 0xf519f86f080babafull, 0x93517229472033d7ull, 0x3188ebe183dc845full,
    0xcfc0659aff970487ull, 0x6df7df54048df56full, 0x0c2f590e46f275c7ull, 0xaa66d2c6893ae67full,
    0x489e4c81cc7d5907ull, 0xe6d5c63b1127b06full, 0x850d3ff551ccc7c7ull, 0x2344b9ad9da8471full,
    0xc17c3366d893d697ull, 0x5fb3ad2066d1762full, 0xfdeb26dba2d6e537ull, 0x9c22a092e00e65bfull,
    0x3a5a1a4d23219437ull, 0xd891940767c334cfull, 0x76c90dc0bbb88357ull, 0x15008779ff741a1full,
    0xb338013232cf9367ull, 0x516f7aec76d4f8cfull, 0xefa6f4a78c196067ull, 0x8dde6e5ec923d9ffull,
};

enum {
    EEOP_ACCUM_0,
    EEOP_CALL_1,
    EEOP_BRANCH_2,
    EEOP_XOR_3,
    EEOP_LOOP_4,
    EEOP_STORE_5,
    EEOP_ACCUM_6,
    EEOP_CALL_7,
    EEOP_BRANCH_8,
    EEOP_XOR_9,
    EEOP_LOOP_10,
    EEOP_STORE_11,
    EEOP_ACCUM_12,
    EEOP_CALL_13,
    EEOP_BRANCH_14,
    EEOP_XOR_15,
    EEOP_LOOP_16,
    EEOP_STORE_17,
    EEOP_ACCUM_18,
    EEOP_CALL_19,
    EEOP_BRANCH_20,
    EEOP_XOR_21,
    EEOP_LOOP_22,
    EEOP_STORE_23,
    EEOP_ACCUM_24,
    EEOP_CALL_25,
    EEOP_BRANCH_26,
    EEOP_XOR_27,
    EEOP_LOOP_28,
    EEOP_STORE_29,
    EEOP_ACCUM_30,
    EEOP_CALL_31,
    EEOP_AGAIN,
    EEOP_DONE,
};

static struct step steps[66] = {
    { .opcode = EEOP_XOR_3, .arg = 38, .jump = 0 },
    { .opcode = EEOP_BRANCH_8, .arg = 130, .jump = 2 },
    { .opcode = EEOP_CALL_13, .arg = 222, .jump = 0 },
    { .opcode = EEOP_ACCUM_18, .arg = 314, .jump = 0 },
    { .opcode = EEOP_STORE_23, .arg = 406, .jump = 0 },
    { .opcode = EEOP_LOOP_28, .arg = 498, .jump = 3 },
    { .opcode = EEOP_CALL_1, .arg = 238, .jump = 0 },
    { .opcode = EEOP_ACCUM_6, .arg = 330, .jump = 0 },
    { .opcode = EEOP_STORE_11, .arg = 422, .jump = 0 },
    { .opcode = EEOP_LOOP_16, .arg = 514, .jump = 7 },
    { .opcode = EEOP_XOR_21, .arg = 606, .jump = 0 },
    { .opcode = EEOP_BRANCH_26, .arg = 698, .jump = 12 },
    { .opcode = EEOP_CALL_31, .arg = 790, .jump = 0 },
    { .opcode = EEOP_LOOP_4, .arg = 530, .jump = 11 },
    { .opcode = EEOP_XOR_9, .arg = 622, .jump = 0 },
    { .opcode = EEOP_BRANCH_14, .arg = 714, .jump = 16 },
    { .opcode = EEOP_CALL_19, .arg = 806, .jump = 0 },
    { .opcode = EEOP_ACCUM_24, .arg = 898, .jump = 0 },
    { .opcode = EEOP_STORE_29, .arg = 990, .jump = 0 },
    { .opcode = EEOP_BRANCH_2, .arg = 730, .jump = 20 },
    { .opcode = EEOP_CALL_7, .arg = 822, .jump = 0 },
    { .opcode = EEOP_ACCUM_12, .arg = 914, .jump = 0 },
    { .opcode = EEOP_STORE_17, .arg = 9, .jump = 0 },
    { .opcode = EEOP_LOOP_22, .arg = 101, .jump = 19 },
    { .opcode = EEOP_XOR_27, .arg = 193, .jump = 0 },
    { .opcode = EEOP_ACCUM_0, .arg = 930, .jump = 0 },
    { .opcode = EEOP_STORE_5, .arg = 25, .jump = 0 },
    { .opcode = EEOP_LOOP_10, .arg = 117, .jump = 23 },
    { .opcode = EEOP_XOR_15, .arg = 209, .jump = 0 },
    { .opcode = EEOP_BRANCH_20, .arg = 301, .jump = 30 },
    { .opcode = EEOP_CALL_25, .arg = 393, .jump = 0 },
    { .opcode = EEOP_ACCUM_30, .arg = 485, .jump = 0 },
    { .opcode = EEOP_XOR_3, .arg = 225, .jump = 0 },
    { .opcode = EEOP_BRANCH_8, .arg = 317, .jump = 35 },
    { .opcode = EEOP_CALL_13, .arg = 409, .jump = 0 },
    { .opcode = EEOP_ACCUM_18, .arg = 501, .jump = 0 },
    { .opcode = EEOP_STORE_23, .arg = 593, .jump = 0 },
    { .opcode = EEOP_LOOP_28, .arg = 685, .jump = 35 },
    { .opcode = EEOP_CALL_1, .arg = 425, .jump = 0 },
    { .opcode = EEOP_ACCUM_6, .arg = 517, .jump = 0 },
    { .opcode = EEOP_STORE_11, .arg = 609, .jump = 0 },
    { .opcode = EEOP_LOOP_16, .arg = 701, .jump = 39 },
    { .opcode = EEOP_XOR_21, .arg = 793, .jump = 0 },
    { .opcode = EEOP_BRANCH_26, .arg = 885, .jump = 46 },
    { .opcode = EEOP_CALL_31, .arg = 977, .jump = 0 },
    { .opcode = EEOP_LOOP_4, .arg = 717, .jump = 43 },
    { .opcode = EEOP_XOR_9, .arg = 809, .jump = 0 },
    { .opcode = EEOP_BRANCH_14, .arg = 901, .jump = 51 },
    { .opcode = EEOP_CALL_19, .arg = 993, .jump = 0 },
    { .opcode = EEOP_ACCUM_24, .arg = 88, .jump = 0 },
    { .opcode = EEOP_STORE_29, .arg = 180, .jump = 0 },
    { .opcode = EEOP_BRANCH_2, .arg = 917, .jump = 53 },
    { .opcode = EEOP_CALL_7, .arg = 12, .jump = 0 },
    { .opcode = EEOP_ACCUM_12, .arg = 104, .jump = 0 },
    { .opcode = EEOP_STORE_17, .arg = 196, .jump = 0 },
    { .opcode = EEOP_LOOP_22, .arg = 288, .jump = 51 },
    { .opcode = EEOP_XOR_27, .arg = 380, .jump = 0 },
    { .opcode = EEOP_ACCUM_0, .arg = 120, .jump = 0 },
    { .opcode = EEOP_STORE_5, .arg = 212, .jump = 0 },
    { .opcode = EEOP_LOOP_10, .arg = 304, .jump = 55 },
    { .opcode = EEOP_XOR_15, .arg = 396, .jump = 0 },
    { .opcode = EEOP_BRANCH_20, .arg = 488, .jump = 64 },
    { .opcode = EEOP_CALL_25, .arg = 580, .jump = 0 },
    { .opcode = EEOP_ACCUM_30, .arg = 672, .jump = 0 },
    { .opcode = EEOP_AGAIN, .arg = 0, .jump = 0 },
    { .opcode = EEOP_DONE, .arg = 0, .jump = 0 },
};

#define EEO_CASE(name) CASE_##name:
#define EEO_SWITCH()
#define EEO_DISPATCH() goto *((void *) dispatch_table[op->opcode])
#define EEO_NEXT() do { op++; EEO_DISPATCH(); } while (0)
#define EEO_JUMP(to) do { op = &state->steps[to]; EEO_DISPATCH(); } while (0)

__attribute__((noinline))
static unsigned long long interp_goto(struct step *steps, struct exprstate *state) {
    static const void *const dispatch_table[] = {
        &&CASE_EEOP_ACCUM_0,
        &&CASE_EEOP_CALL_1,
        &&CASE_EEOP_BRANCH_2,
        &&CASE_EEOP_XOR_3,
        &&CASE_EEOP_LOOP_4,
        &&CASE_EEOP_STORE_5,
        &&CASE_EEOP_ACCUM_6,
        &&CASE_EEOP_CALL_7,
        &&CASE_EEOP_BRANCH_8,
        &&CASE_EEOP_XOR_9,
        &&CASE_EEOP_LOOP_10,
        &&CASE_EEOP_STORE_11,
        &&CASE_EEOP_ACCUM_12,
        &&CASE_EEOP_CALL_13,
        &&CASE_EEOP_BRANCH_14,
        &&CASE_EEOP_XOR_15,
        &&CASE_EEOP_LOOP_16,
        &&CASE_EEOP_STORE_17,
        &&CASE_EEOP_ACCUM_18,
        &&CASE_EEOP_CALL_19,
        &&CASE_EEOP_BRANCH_20,
        &&CASE_EEOP_XOR_21,
        &&CASE_EEOP_LOOP_22,
        &&CASE_EEOP_STORE_23,
        &&CASE_EEOP_ACCUM_24,
        &&CASE_EEOP_CALL_25,
        &&CASE_EEOP_BRANCH_26,
        &&CASE_EEOP_XOR_27,
        &&CASE_EEOP_LOOP_28,
        &&CASE_EEOP_STORE_29,
        &&CASE_EEOP_ACCUM_30,
        &&CASE_EEOP_CALL_31,
        &&CASE_EEOP_AGAIN,
        &&CASE_EEOP_DONE,
    };
    unsigned long long acc = state->seed;
    unsigned int loops = state->loops;
    unsigned long long v0 = state->seed * 3ull + 0ull;
    unsigned int v1 = (unsigned int)(state->seed >> 1) + 1u;
    const unsigned long long *v2 = &data[(state->seed + 2ull) & 63];
    unsigned long long v3 = state->seed * 9ull + 3ull;
    unsigned int v4 = (unsigned int)(state->seed >> 4) + 4u;
    const unsigned long long *v5 = &data[(state->seed + 5ull) & 63];
    unsigned long long v6 = state->seed * 15ull + 6ull;
    unsigned int v7 = (unsigned int)(state->seed >> 7) + 7u;
    const unsigned long long *v8 = &data[(state->seed + 8ull) & 63];
    unsigned long long v9 = state->seed * 21ull + 9ull;
    unsigned int v10 = (unsigned int)(state->seed >> 10) + 10u;
    const unsigned long long *v11 = &data[(state->seed + 11ull) & 63];
    unsigned long long v12 = state->seed * 27ull + 12ull;
    unsigned int v13 = (unsigned int)(state->seed >> 13) + 13u;
    const unsigned long long *v14 = &data[(state->seed + 14ull) & 63];
    unsigned long long v15 = state->seed * 33ull + 15ull;
    unsigned int v16 = (unsigned int)(state->seed >> 16) + 16u;
    const unsigned long long *v17 = &data[(state->seed + 17ull) & 63];
    unsigned long long v18 = state->seed * 39ull + 18ull;
    unsigned int v19 = (unsigned int)(state->seed >> 19) + 19u;
    const unsigned long long *v20 = &data[(state->seed + 20ull) & 63];
    unsigned long long v21 = state->seed * 45ull + 21ull;
    unsigned int v22 = (unsigned int)(state->seed >> 22) + 22u;
    const unsigned long long *v23 = &data[(state->seed + 23ull) & 63];
    struct step *op = state->steps;

    EEO_DISPATCH();
    EEO_SWITCH()
    {
        EEO_CASE(EEOP_ACCUM_0)
        {
            acc = acc * 31ull + v3 + (unsigned long long)op->arg;
            v2 = &data[(v2 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_1)
        {
            acc = (acc ^ ((unsigned long long)v10 >> (op->arg & 31))) * 5ull + (unsigned long long)op->arg;
            v12 = v12 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_2)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v22 = v22 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_3)
        {
            acc = (acc ^ (v0 << 4)) + (unsigned long long)op->arg;
            v8 = &data[(v8 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_4)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v7;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_5)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v14);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_6)
        {
            acc = acc * 31ull + v21 + (unsigned long long)op->arg;
            v14 = &data[(v14 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_7)
        {
            acc = (acc ^ ((unsigned long long)v4 >> (op->arg & 31))) * 17ull + (unsigned long long)op->arg;
            v0 = v0 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_8)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v10 = v10 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_9)
        {
            acc = (acc ^ (v18 << 10)) + (unsigned long long)op->arg;
            v20 = &data[(v20 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_10)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v1;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_11)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v8);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_12)
        {
            acc = acc * 31ull + v15 + (unsigned long long)op->arg;
            v2 = &data[(v2 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_13)
        {
            acc = (acc ^ ((unsigned long long)v22 >> (op->arg & 31))) * 29ull + (unsigned long long)op->arg;
            v12 = v12 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_14)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v22 = v22 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_15)
        {
            acc = (acc ^ (v12 << 3)) + (unsigned long long)op->arg;
            v8 = &data[(v8 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_16)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v19;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_17)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v2);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_18)
        {
            acc = acc * 31ull + v9 + (unsigned long long)op->arg;
            v14 = &data[(v14 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_19)
        {
            acc = (acc ^ ((unsigned long long)v16 >> (op->arg & 31))) * 41ull + (unsigned long long)op->arg;
            v0 = v0 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_20)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v10 = v10 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_21)
        {
            acc = (acc ^ (v6 << 9)) + (unsigned long long)op->arg;
            v20 = &data[(v20 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_22)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v13;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_23)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v20);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_24)
        {
            acc = acc * 31ull + v3 + (unsigned long long)op->arg;
            v2 = &data[(v2 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_25)
        {
            acc = (acc ^ ((unsigned long long)v10 >> (op->arg & 31))) * 53ull + (unsigned long long)op->arg;
            v12 = v12 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_26)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v22 = v22 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_27)
        {
            acc = (acc ^ (v0 << 2)) + (unsigned long long)op->arg;
            v8 = &data[(v8 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_28)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v7;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_29)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v14);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_30)
        {
            acc = acc * 31ull + v21 + (unsigned long long)op->arg;
            v14 = &data[(v14 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_31)
        {
            acc = (acc ^ ((unsigned long long)v4 >> (op->arg & 31))) * 65ull + (unsigned long long)op->arg;
            v0 = v0 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_AGAIN)
        {
            if (loops != 0) {
                loops = loops - 1;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_DONE)
        {
            goto out;
        }
    }

out:
    {
        unsigned long long h = acc;
        h = h * 1000003ull + v0;
        h = h * 1000003ull + (unsigned long long)v1;
        h = h * 1000003ull + *v2;
        h = h * 1000003ull + v3;
        h = h * 1000003ull + (unsigned long long)v4;
        h = h * 1000003ull + *v5;
        h = h * 1000003ull + v6;
        h = h * 1000003ull + (unsigned long long)v7;
        h = h * 1000003ull + *v8;
        h = h * 1000003ull + v9;
        h = h * 1000003ull + (unsigned long long)v10;
        h = h * 1000003ull + *v11;
        h = h * 1000003ull + v12;
        h = h * 1000003ull + (unsigned long long)v13;
        h = h * 1000003ull + *v14;
        h = h * 1000003ull + v15;
        h = h * 1000003ull + (unsigned long long)v16;
        h = h * 1000003ull + *v17;
        h = h * 1000003ull + v18;
        h = h * 1000003ull + (unsigned long long)v19;
        h = h * 1000003ull + *v20;
        h = h * 1000003ull + v21;
        h = h * 1000003ull + (unsigned long long)v22;
        h = h * 1000003ull + *v23;
        return h * 1000003ull + loops;
    }
}

#undef EEO_CASE
#undef EEO_SWITCH
#undef EEO_DISPATCH
#define EEO_CASE(name) case name:
#define EEO_SWITCH() starteval: switch (op->opcode)
#define EEO_DISPATCH() goto starteval

__attribute__((noinline))
static unsigned long long interp_switch(struct step *steps, struct exprstate *state) {
    unsigned long long acc = state->seed;
    unsigned int loops = state->loops;
    unsigned long long v0 = state->seed * 3ull + 0ull;
    unsigned int v1 = (unsigned int)(state->seed >> 1) + 1u;
    const unsigned long long *v2 = &data[(state->seed + 2ull) & 63];
    unsigned long long v3 = state->seed * 9ull + 3ull;
    unsigned int v4 = (unsigned int)(state->seed >> 4) + 4u;
    const unsigned long long *v5 = &data[(state->seed + 5ull) & 63];
    unsigned long long v6 = state->seed * 15ull + 6ull;
    unsigned int v7 = (unsigned int)(state->seed >> 7) + 7u;
    const unsigned long long *v8 = &data[(state->seed + 8ull) & 63];
    unsigned long long v9 = state->seed * 21ull + 9ull;
    unsigned int v10 = (unsigned int)(state->seed >> 10) + 10u;
    const unsigned long long *v11 = &data[(state->seed + 11ull) & 63];
    unsigned long long v12 = state->seed * 27ull + 12ull;
    unsigned int v13 = (unsigned int)(state->seed >> 13) + 13u;
    const unsigned long long *v14 = &data[(state->seed + 14ull) & 63];
    unsigned long long v15 = state->seed * 33ull + 15ull;
    unsigned int v16 = (unsigned int)(state->seed >> 16) + 16u;
    const unsigned long long *v17 = &data[(state->seed + 17ull) & 63];
    unsigned long long v18 = state->seed * 39ull + 18ull;
    unsigned int v19 = (unsigned int)(state->seed >> 19) + 19u;
    const unsigned long long *v20 = &data[(state->seed + 20ull) & 63];
    unsigned long long v21 = state->seed * 45ull + 21ull;
    unsigned int v22 = (unsigned int)(state->seed >> 22) + 22u;
    const unsigned long long *v23 = &data[(state->seed + 23ull) & 63];
    struct step *op = state->steps;

    EEO_DISPATCH();
    EEO_SWITCH()
    {
        EEO_CASE(EEOP_ACCUM_0)
        {
            acc = acc * 31ull + v3 + (unsigned long long)op->arg;
            v2 = &data[(v2 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_1)
        {
            acc = (acc ^ ((unsigned long long)v10 >> (op->arg & 31))) * 5ull + (unsigned long long)op->arg;
            v12 = v12 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_2)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v22 = v22 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_3)
        {
            acc = (acc ^ (v0 << 4)) + (unsigned long long)op->arg;
            v8 = &data[(v8 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_4)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v7;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_5)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v14);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_6)
        {
            acc = acc * 31ull + v21 + (unsigned long long)op->arg;
            v14 = &data[(v14 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_7)
        {
            acc = (acc ^ ((unsigned long long)v4 >> (op->arg & 31))) * 17ull + (unsigned long long)op->arg;
            v0 = v0 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_8)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v10 = v10 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_9)
        {
            acc = (acc ^ (v18 << 10)) + (unsigned long long)op->arg;
            v20 = &data[(v20 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_10)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v1;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_11)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v8);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_12)
        {
            acc = acc * 31ull + v15 + (unsigned long long)op->arg;
            v2 = &data[(v2 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_13)
        {
            acc = (acc ^ ((unsigned long long)v22 >> (op->arg & 31))) * 29ull + (unsigned long long)op->arg;
            v12 = v12 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_14)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v22 = v22 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_15)
        {
            acc = (acc ^ (v12 << 3)) + (unsigned long long)op->arg;
            v8 = &data[(v8 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_16)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v19;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_17)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v2);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_18)
        {
            acc = acc * 31ull + v9 + (unsigned long long)op->arg;
            v14 = &data[(v14 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_19)
        {
            acc = (acc ^ ((unsigned long long)v16 >> (op->arg & 31))) * 41ull + (unsigned long long)op->arg;
            v0 = v0 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_20)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v10 = v10 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_21)
        {
            acc = (acc ^ (v6 << 9)) + (unsigned long long)op->arg;
            v20 = &data[(v20 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_22)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v13;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_23)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v20);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_24)
        {
            acc = acc * 31ull + v3 + (unsigned long long)op->arg;
            v2 = &data[(v2 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_25)
        {
            acc = (acc ^ ((unsigned long long)v10 >> (op->arg & 31))) * 53ull + (unsigned long long)op->arg;
            v12 = v12 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_BRANCH_26)
        {
            if ((acc >> (op->arg & 31)) & 1ull)
                EEO_JUMP(op->jump);
            v22 = v22 + (unsigned int)acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_XOR_27)
        {
            acc = (acc ^ (v0 << 2)) + (unsigned long long)op->arg;
            v8 = &data[(v8 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_LOOP_28)
        {
            if (loops != 0) {
                loops = loops - 1;
                acc = acc + (unsigned long long)v7;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_STORE_29)
        {
            state->out[op->arg & 7] = state->out[op->arg & 7] * 5ull + (acc ^ *v14);
            EEO_NEXT();
        }
        EEO_CASE(EEOP_ACCUM_30)
        {
            acc = acc * 31ull + v21 + (unsigned long long)op->arg;
            v14 = &data[(v14 - data + (long long)(acc & 7ull) + 1) & 63];
            EEO_NEXT();
        }
        EEO_CASE(EEOP_CALL_31)
        {
            acc = (acc ^ ((unsigned long long)v4 >> (op->arg & 31))) * 65ull + (unsigned long long)op->arg;
            v0 = v0 * 3ull + acc;
            EEO_NEXT();
        }
        EEO_CASE(EEOP_AGAIN)
        {
            if (loops != 0) {
                loops = loops - 1;
                EEO_JUMP(op->jump);
            }
            EEO_NEXT();
        }
        EEO_CASE(EEOP_DONE)
        {
            goto out;
        }
    }

out:
    {
        unsigned long long h = acc;
        h = h * 1000003ull + v0;
        h = h * 1000003ull + (unsigned long long)v1;
        h = h * 1000003ull + *v2;
        h = h * 1000003ull + v3;
        h = h * 1000003ull + (unsigned long long)v4;
        h = h * 1000003ull + *v5;
        h = h * 1000003ull + v6;
        h = h * 1000003ull + (unsigned long long)v7;
        h = h * 1000003ull + *v8;
        h = h * 1000003ull + v9;
        h = h * 1000003ull + (unsigned long long)v10;
        h = h * 1000003ull + *v11;
        h = h * 1000003ull + v12;
        h = h * 1000003ull + (unsigned long long)v13;
        h = h * 1000003ull + *v14;
        h = h * 1000003ull + v15;
        h = h * 1000003ull + (unsigned long long)v16;
        h = h * 1000003ull + *v17;
        h = h * 1000003ull + v18;
        h = h * 1000003ull + (unsigned long long)v19;
        h = h * 1000003ull + *v20;
        h = h * 1000003ull + v21;
        h = h * 1000003ull + (unsigned long long)v22;
        h = h * 1000003ull + *v23;
        return h * 1000003ull + loops;
    }
}

static unsigned long long run(
    unsigned long long (*interp)(struct step *, struct exprstate *),
    unsigned long long seed, unsigned int loops) {
    struct exprstate state;
    state.seed = seed;
    state.loops = loops;
    state.steps = steps;
    for (int i = 0; i < 8; i++) {
        state.out[i] = (unsigned long long)i;
    }
    unsigned long long h = interp(steps, &state);
    for (int i = 0; i < 8; i++) {
        h = h * 31ull + state.out[i];
    }
    return h;
}
static volatile unsigned long long seed_in = 20250928ull;
static volatile unsigned int loops_in = 200u;

int main(void) {
    unsigned long long seed = seed_in;
    unsigned int loops = loops_in;
    printf("%llu\n", (unsigned long long)(run(interp_goto, seed + 0, loops)));
    printf("%llu\n", (unsigned long long)(run(interp_switch, seed + 0, loops)));
    printf("%llu\n", (unsigned long long)(run(interp_goto, seed + 1, loops)));
    printf("%llu\n", (unsigned long long)(run(interp_switch, seed + 1, loops)));
    printf("%llu\n", (unsigned long long)(run(interp_goto, seed + 2, loops)));
    printf("%llu\n", (unsigned long long)(run(interp_switch, seed + 2, loops)));
    return 0;
}
