// algebraic identities on one bit values kept at one bit
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int truth_in = 1;
static volatile int falsity_in = 0;
static volatile int counter_in = 7;

int main(void) {
    _Bool p = truth_in != 0;
    _Bool q = falsity_in != 0;
    int counter = counter_in;
    _Bool r = counter > 3;

    _Bool k0 = p & p;
    printf("%lld\n", (long long)(k0));
    _Bool k1 = p | p;
    printf("%lld\n", (long long)(k1));
    _Bool k2 = p ^ p;
    printf("%lld\n", (long long)(k2));
    _Bool k3 = p & 0;
    printf("%lld\n", (long long)(k3));
    _Bool k4 = 0 & p;
    printf("%lld\n", (long long)(k4));
    _Bool k5 = p & 1;
    printf("%lld\n", (long long)(k5));
    _Bool k6 = 1 & p;
    printf("%lld\n", (long long)(k6));
    _Bool k7 = p | 0;
    printf("%lld\n", (long long)(k7));
    _Bool k8 = 0 | p;
    printf("%lld\n", (long long)(k8));
    _Bool k9 = p | 1;
    printf("%lld\n", (long long)(k9));
    _Bool k10 = 1 | p;
    printf("%lld\n", (long long)(k10));
    _Bool k11 = p ^ 0;
    printf("%lld\n", (long long)(k11));
    _Bool k12 = 0 ^ p;
    printf("%lld\n", (long long)(k12));

    _Bool k13 = q & q;
    printf("%lld\n", (long long)(k13));
    _Bool k14 = q | q;
    printf("%lld\n", (long long)(k14));
    _Bool k15 = q ^ q;
    printf("%lld\n", (long long)(k15));
    _Bool k16 = q & 0;
    printf("%lld\n", (long long)(k16));
    _Bool k17 = 0 & q;
    printf("%lld\n", (long long)(k17));
    _Bool k18 = q & 1;
    printf("%lld\n", (long long)(k18));
    _Bool k19 = 1 & q;
    printf("%lld\n", (long long)(k19));
    _Bool k20 = q | 0;
    printf("%lld\n", (long long)(k20));
    _Bool k21 = 0 | q;
    printf("%lld\n", (long long)(k21));
    _Bool k22 = q | 1;
    printf("%lld\n", (long long)(k22));
    _Bool k23 = 1 | q;
    printf("%lld\n", (long long)(k23));
    _Bool k24 = q ^ 0;
    printf("%lld\n", (long long)(k24));
    _Bool k25 = 0 ^ q;
    printf("%lld\n", (long long)(k25));

    _Bool k26 = r & r;
    printf("%lld\n", (long long)(k26));
    _Bool k27 = r | r;
    printf("%lld\n", (long long)(k27));
    _Bool k28 = r ^ r;
    printf("%lld\n", (long long)(k28));
    _Bool k29 = r & 0;
    printf("%lld\n", (long long)(k29));
    _Bool k30 = 0 & r;
    printf("%lld\n", (long long)(k30));
    _Bool k31 = r & 1;
    printf("%lld\n", (long long)(k31));
    _Bool k32 = 1 & r;
    printf("%lld\n", (long long)(k32));
    _Bool k33 = r | 0;
    printf("%lld\n", (long long)(k33));
    _Bool k34 = 0 | r;
    printf("%lld\n", (long long)(k34));
    _Bool k35 = r | 1;
    printf("%lld\n", (long long)(k35));
    _Bool k36 = 1 | r;
    printf("%lld\n", (long long)(k36));
    _Bool k37 = r ^ 0;
    printf("%lld\n", (long long)(k37));
    _Bool k38 = 0 ^ r;
    printf("%lld\n", (long long)(k38));

    _Bool k39 = p & q;
    printf("%lld\n", (long long)(k39));
    _Bool k40 = p | q;
    printf("%lld\n", (long long)(k40));
    _Bool k41 = p ^ q;
    printf("%lld\n", (long long)(k41));
    _Bool k42 = p & r;
    printf("%lld\n", (long long)(k42));
    _Bool k43 = p | r;
    printf("%lld\n", (long long)(k43));
    _Bool k44 = p ^ r;
    printf("%lld\n", (long long)(k44));

    _Bool k45 = q & p;
    printf("%lld\n", (long long)(k45));
    _Bool k46 = q | p;
    printf("%lld\n", (long long)(k46));
    _Bool k47 = q ^ p;
    printf("%lld\n", (long long)(k47));
    _Bool k48 = q & r;
    printf("%lld\n", (long long)(k48));
    _Bool k49 = q | r;
    printf("%lld\n", (long long)(k49));
    _Bool k50 = q ^ r;
    printf("%lld\n", (long long)(k50));

    _Bool k51 = r & p;
    printf("%lld\n", (long long)(k51));
    _Bool k52 = r | p;
    printf("%lld\n", (long long)(k52));
    _Bool k53 = r ^ p;
    printf("%lld\n", (long long)(k53));
    _Bool k54 = r & q;
    printf("%lld\n", (long long)(k54));
    _Bool k55 = r | q;
    printf("%lld\n", (long long)(k55));
    _Bool k56 = r ^ q;
    printf("%lld\n", (long long)(k56));

    return 0;
}
