// bitwise-constant identities on long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long x0_in = (-9223372036854775807ll - 1);
static volatile long long x1_in = (-2ll);
static volatile long long x2_in = 1ll;
static volatile long long x3_in = 7ll;
static volatile long long x4_in = 255ll;
static volatile long long x5_in = 9223372036854775807ll;

int main(void) {
    long long x0 = x0_in;
    printf("%lld\n", (long long)(x0 & (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll & x0));
    printf("%lld\n", (long long)(x0 & (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) & x0));
    printf("%lld\n", (long long)(x0 | (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll | x0));
    printf("%lld\n", (long long)(x0 | (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) | x0));
    printf("%lld\n", (long long)(x0 ^ (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll ^ x0));

    long long x1 = x1_in;
    printf("%lld\n", (long long)(x1 & (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll & x1));
    printf("%lld\n", (long long)(x1 & (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) & x1));
    printf("%lld\n", (long long)(x1 | (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll | x1));
    printf("%lld\n", (long long)(x1 | (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) | x1));
    printf("%lld\n", (long long)(x1 ^ (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll ^ x1));

    long long x2 = x2_in;
    printf("%lld\n", (long long)(x2 & (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll & x2));
    printf("%lld\n", (long long)(x2 & (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) & x2));
    printf("%lld\n", (long long)(x2 | (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll | x2));
    printf("%lld\n", (long long)(x2 | (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) | x2));
    printf("%lld\n", (long long)(x2 ^ (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll ^ x2));

    long long x3 = x3_in;
    printf("%lld\n", (long long)(x3 & (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll & x3));
    printf("%lld\n", (long long)(x3 & (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) & x3));
    printf("%lld\n", (long long)(x3 | (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll | x3));
    printf("%lld\n", (long long)(x3 | (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) | x3));
    printf("%lld\n", (long long)(x3 ^ (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll ^ x3));

    long long x4 = x4_in;
    printf("%lld\n", (long long)(x4 & (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll & x4));
    printf("%lld\n", (long long)(x4 & (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) & x4));
    printf("%lld\n", (long long)(x4 | (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll | x4));
    printf("%lld\n", (long long)(x4 | (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) | x4));
    printf("%lld\n", (long long)(x4 ^ (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll ^ x4));

    long long x5 = x5_in;
    printf("%lld\n", (long long)(x5 & (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll & x5));
    printf("%lld\n", (long long)(x5 & (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) & x5));
    printf("%lld\n", (long long)(x5 | (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll | x5));
    printf("%lld\n", (long long)(x5 | (long long)(-1ll)));
    printf("%lld\n", (long long)((long long)(-1ll) | x5));
    printf("%lld\n", (long long)(x5 ^ (long long)0ll));
    printf("%lld\n", (long long)((long long)0ll ^ x5));

    return 0;
}
