// canonical identities on short
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short x0_in = (-32767 - 1);
static volatile short x1_in = (-2);
static volatile short x2_in = 1;
static volatile short x3_in = 7;
static volatile short x4_in = 255;
static volatile short x5_in = 32767;

int main(void) {
    short x0 = x0_in;
    printf("%lld\n", (long long)((int)3 + x0));
    printf("%lld\n", (long long)(x0 + (int)3));
    printf("%lld\n", (long long)((int)5 * x0));
    printf("%lld\n", (long long)(x0 * (int)5));
    printf("%lld\n", (long long)((int)12 & x0));
    printf("%lld\n", (long long)(x0 & (int)12));
    printf("%lld\n", (long long)((int)9 | x0));
    printf("%lld\n", (long long)(x0 | (int)9));
    printf("%lld\n", (long long)((int)6 ^ x0));
    printf("%lld\n", (long long)(x0 ^ (int)6));

    short x1 = x1_in;
    printf("%lld\n", (long long)((int)3 + x1));
    printf("%lld\n", (long long)(x1 + (int)3));
    printf("%lld\n", (long long)((int)5 * x1));
    printf("%lld\n", (long long)(x1 * (int)5));
    printf("%lld\n", (long long)((int)12 & x1));
    printf("%lld\n", (long long)(x1 & (int)12));
    printf("%lld\n", (long long)((int)9 | x1));
    printf("%lld\n", (long long)(x1 | (int)9));
    printf("%lld\n", (long long)((int)6 ^ x1));
    printf("%lld\n", (long long)(x1 ^ (int)6));

    short x2 = x2_in;
    printf("%lld\n", (long long)((int)3 + x2));
    printf("%lld\n", (long long)(x2 + (int)3));
    printf("%lld\n", (long long)((int)5 * x2));
    printf("%lld\n", (long long)(x2 * (int)5));
    printf("%lld\n", (long long)((int)12 & x2));
    printf("%lld\n", (long long)(x2 & (int)12));
    printf("%lld\n", (long long)((int)9 | x2));
    printf("%lld\n", (long long)(x2 | (int)9));
    printf("%lld\n", (long long)((int)6 ^ x2));
    printf("%lld\n", (long long)(x2 ^ (int)6));

    short x3 = x3_in;
    printf("%lld\n", (long long)((int)3 + x3));
    printf("%lld\n", (long long)(x3 + (int)3));
    printf("%lld\n", (long long)((int)5 * x3));
    printf("%lld\n", (long long)(x3 * (int)5));
    printf("%lld\n", (long long)((int)12 & x3));
    printf("%lld\n", (long long)(x3 & (int)12));
    printf("%lld\n", (long long)((int)9 | x3));
    printf("%lld\n", (long long)(x3 | (int)9));
    printf("%lld\n", (long long)((int)6 ^ x3));
    printf("%lld\n", (long long)(x3 ^ (int)6));

    short x4 = x4_in;
    printf("%lld\n", (long long)((int)3 + x4));
    printf("%lld\n", (long long)(x4 + (int)3));
    printf("%lld\n", (long long)((int)5 * x4));
    printf("%lld\n", (long long)(x4 * (int)5));
    printf("%lld\n", (long long)((int)12 & x4));
    printf("%lld\n", (long long)(x4 & (int)12));
    printf("%lld\n", (long long)((int)9 | x4));
    printf("%lld\n", (long long)(x4 | (int)9));
    printf("%lld\n", (long long)((int)6 ^ x4));
    printf("%lld\n", (long long)(x4 ^ (int)6));

    short x5 = x5_in;
    printf("%lld\n", (long long)((int)3 + x5));
    printf("%lld\n", (long long)(x5 + (int)3));
    printf("%lld\n", (long long)((int)5 * x5));
    printf("%lld\n", (long long)(x5 * (int)5));
    printf("%lld\n", (long long)((int)12 & x5));
    printf("%lld\n", (long long)(x5 & (int)12));
    printf("%lld\n", (long long)((int)9 | x5));
    printf("%lld\n", (long long)(x5 | (int)9));
    printf("%lld\n", (long long)((int)6 ^ x5));
    printf("%lld\n", (long long)(x5 ^ (int)6));

    return 0;
}
