// shift identities on int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int x2_in = 1;
static volatile int x3_in = 7;
static volatile int x4_in = 255;
static volatile int x5_in = 2147483647;

int main(void) {
    int x2 = x2_in;
    printf("%lld\n", (long long)(x2 << 0));
    printf("%lld\n", (long long)(x2 >> 0));

    int x3 = x3_in;
    printf("%lld\n", (long long)(x3 << 0));
    printf("%lld\n", (long long)(x3 >> 0));

    int x4 = x4_in;
    printf("%lld\n", (long long)(x4 << 0));
    printf("%lld\n", (long long)(x4 >> 0));

    int x5 = x5_in;
    printf("%lld\n", (long long)(x5 << 0));
    printf("%lld\n", (long long)(x5 >> 0));

    return 0;
}
