// a select moving a running unsigned short by its condition, down-mirrored
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    unsigned short acc = 0;
    for (int r = 0; r < 64; r++) {
        int k = r * 4;
        for (int i = 0; i < 256; i++) {
            int v = data[i];
            acc = v < k ? acc : acc - 1;
        }
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
