// a select moving a running signed char by its condition, one-zero
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 7;

int main(void) {
    int seed = seed_in;

    int data[256];
    for (int i = 0; i < 256; i++) {
        data[i] = (i * 37 + seed) & 255;
    }

    signed char acc = 0;
    for (int r = 0; r < 64; r++) {
        int k = r * 4;
        for (int i = 0; i < 256; i++) {
            int v = data[i];
            acc += v < k ? 1 : 0;
        }
    }

    printf("%lld\n", (long long)(acc));
    return 0;
}
