// algebraic identities on one bit values
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int truth_in = 1;
static volatile int falsity_in = 0;
static volatile int counter_in = 7;

int main(void) {
    _Bool p = truth_in != 0;
    _Bool q = falsity_in != 0;
    int counter = counter_in;
    _Bool r = counter > 3;

    printf("%lld\n", (long long)(p & p));
    printf("%lld\n", (long long)(p | p));
    printf("%lld\n", (long long)(p ^ p));
    printf("%lld\n", (long long)(p & 0));
    printf("%lld\n", (long long)(0 & p));
    printf("%lld\n", (long long)(p & 1));
    printf("%lld\n", (long long)(1 & p));
    printf("%lld\n", (long long)(p | 0));
    printf("%lld\n", (long long)(0 | p));
    printf("%lld\n", (long long)(p | 1));
    printf("%lld\n", (long long)(1 | p));
    printf("%lld\n", (long long)(p ^ 0));
    printf("%lld\n", (long long)(0 ^ p));

    printf("%lld\n", (long long)(q & q));
    printf("%lld\n", (long long)(q | q));
    printf("%lld\n", (long long)(q ^ q));
    printf("%lld\n", (long long)(q & 0));
    printf("%lld\n", (long long)(0 & q));
    printf("%lld\n", (long long)(q & 1));
    printf("%lld\n", (long long)(1 & q));
    printf("%lld\n", (long long)(q | 0));
    printf("%lld\n", (long long)(0 | q));
    printf("%lld\n", (long long)(q | 1));
    printf("%lld\n", (long long)(1 | q));
    printf("%lld\n", (long long)(q ^ 0));
    printf("%lld\n", (long long)(0 ^ q));

    printf("%lld\n", (long long)(r & r));
    printf("%lld\n", (long long)(r | r));
    printf("%lld\n", (long long)(r ^ r));
    printf("%lld\n", (long long)(r & 0));
    printf("%lld\n", (long long)(0 & r));
    printf("%lld\n", (long long)(r & 1));
    printf("%lld\n", (long long)(1 & r));
    printf("%lld\n", (long long)(r | 0));
    printf("%lld\n", (long long)(0 | r));
    printf("%lld\n", (long long)(r | 1));
    printf("%lld\n", (long long)(1 | r));
    printf("%lld\n", (long long)(r ^ 0));
    printf("%lld\n", (long long)(0 ^ r));

    return 0;
}
