// a known unsigned int value reaching a use, direct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    unsigned int value = (unsigned int)21u;

    printf("%llu\n", (unsigned long long)(value + value));
    return 0;
}
