// a known long long value reaching a use, direct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    long long value = (long long)21ll;

    printf("%lld\n", (long long)(value + value));
    return 0;
}
