// a known unsigned int value reaching a use, same-on-both-arms
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    unsigned int value;
    if (flag) {
        value = (unsigned int)21u;
    } else {
        value = (unsigned int)21u;
    }

    printf("%llu\n", (unsigned long long)(value + value));
    return 0;
}
