// a known unsigned long long value reaching a use, direct
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    unsigned long long value = (unsigned long long)21ull;

    printf("%llu\n", (unsigned long long)(value + value));
    return 0;
}
