// A module reading and writing 5 kinds of executable global
// Generated by rucc-corpus. Edit the generator, not this file.

#include <dlfcn.h>

int printf(const char *, ...);

static void *load(const char *path)
{
    void *handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!handle) {
        printf("dlopen %s: %s\n", path, dlerror());
    }
    return handle;
}

static void *find(void *handle, const char *name)
{
    void *found = dlsym(handle, name);
    if (!found) {
        printf("dlsym %s: %s\n", name, dlerror());
    }
    return found;
}

struct config {
    int a;
    long long b;
    unsigned char c;
    short d;
    double e;
};

int NBuffers = 65;
long long counter = 2000;
struct config Config = { 8, 100001, 220, -31, 3.25 };
int table[5] = { 2, 3, 6, 11, 18 };
const char *const names[3] = { "alpha", "beta", "gamma" };

static volatile int r0_in = 2;
static volatile int r1_in = 3;

int main(void) {
    void *m0 = load("./m0.so");
    if (!m0) {
        return 1;
    }
    long long (*run)(int) = (long long (*)(int))find(m0, "mod_run");
    int r0 = r0_in;
    printf("%lld\n", (long long)(run(r0)));
    int r1 = r1_in;
    printf("%lld\n", (long long)(run(r1)));
    printf("%lld\n", (long long)(counter));
    printf("%lld\n", (long long)(NBuffers));
    long long sum = 0;
    for (int i = 0; i < 5; i++) {
        sum += table[i];
    }
    printf("%lld\n", (long long)(sum));
    printf("%lld\n", (long long)(Config.b));
    printf("%llu\n", (unsigned long long)(Config.c));
    return 0;
}
