// Two modules registering 9 callbacks in a table the executable calls
// Generated by rucc-corpus. Edit the generator, not this file.

#include <dlfcn.h>

int printf(const char *, ...);

static void *load(const char *path)
{
    void *handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!handle) {
        printf("dlopen %s: %s\n", path, dlerror());
    }
    return handle;
}

static void *find(void *handle, const char *name)
{
    void *found = dlsym(handle, name);
    if (!found) {
        printf("dlsym %s: %s\n", name, dlerror());
    }
    return found;
}

typedef long long (*callback_fn)(long long, int);

struct callback {
    callback_fn fn;
    long long arg;
    int priority;
};

static struct callback callbacks[16];
static int ncallbacks;

void RegisterCallback(callback_fn fn, long long arg, int priority)
{
    int at = ncallbacks;
    while (at > 0 && callbacks[at - 1].priority > priority) {
        callbacks[at] = callbacks[at - 1];
        at--;
    }
    callbacks[at].fn = fn;
    callbacks[at].arg = arg;
    callbacks[at].priority = priority;
    ncallbacks++;
}

static long long fire(int event)
{
    long long acc = 0;
    for (int i = 0; i < ncallbacks; i++) {
        acc = acc * 3 + callbacks[i].fn(callbacks[i].arg, event);
    }
    return acc;
}

int main(void) {
    void *m0 = load("./m0.so");
    if (!m0) {
        return 1;
    }
    void (*init0)(void) = (void (*)(void))find(m0, "_PG_init");
    init0();
    void *m1 = load("./m1.so");
    if (!m1) {
        return 1;
    }
    void (*init1)(void) = (void (*)(void))find(m1, "_PG_init");
    init1();
    printf("%lld\n", (long long)(ncallbacks));
    printf("%lld\n", (long long)(fire(1)));
    printf("%lld\n", (long long)(fire(2)));
    printf("%lld\n", (long long)(fire(3)));
    long long (*seen0)(void) = (long long (*)(void))find(m0, "mod_seen");
    printf("%lld\n", (long long)(seen0()));
    long long (*seen1)(void) = (long long (*)(void))find(m1, "mod_seen");
    printf("%lld\n", (long long)(seen1()));
    return 0;
}
