// Raises messages through the executable's variadic elog.
// Generated by rucc-corpus. Edit the generator, not this file.

#include <stdarg.h>

void elog(int, const char *, ...);
void elog_valist(int, const char *, va_list);

static void mylog(int level, const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    elog_valist(level, fmt, ap);
    va_end(ap);
}

void mod_run(void)
{
    elog(15, "m0 %d", -19);
    mylog(17, "m1 %L %u %f %s", -2999999986LL, 3999998999u, -0.875, "heap");
    elog(19, "m2 %u %f %s %c %d %L %u", 3999998000u, -0.875, "heap", 'g', 7, 13000000126LL, 3999997994u);
    mylog(21, "m3 %f %s %c %d %L %u %f %s %c %d", -0.875, "heap", 'g', 11, 15000000140LL, 3999996995u, 1.375, "index", 'm', 29);
    elog(10, "m4");
    mylog(15, "m5 %c %d %L", 'g', 19, 13000000126LL);
    elog(17, "m6 %d %L %u %f %s %c", 23, 9000000098LL, 3999993998u, 1.375, "index", 'm');
    mylog(19, "m7 %L %u %f %s %c %d %L %u %f", 3000000056LL, 3999992999u, 1.375, "index", 'm', 45, 51000000392LL, 3999992993u, 3.625);
}
