// Thread locals across the module boundary, 6 calls
// Generated by rucc-corpus. Edit the generator, not this file.

#include <dlfcn.h>

int printf(const char *, ...);

static void *load(const char *path)
{
    void *handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!handle) {
        printf("dlopen %s: %s\n", path, dlerror());
    }
    return handle;
}

static void *find(void *handle, const char *name)
{
    void *found = dlsym(handle, name);
    if (!found) {
        printf("dlsym %s: %s\n", name, dlerror());
    }
    return found;
}

_Thread_local int exe_depth = 7;
_Thread_local long long exe_tl_acc;


int main(void) {
    void *m0 = load("./m0.so");
    if (!m0) {
        return 1;
    }
    long long (*enter)(int) = (long long (*)(int))find(m0, "mod_enter");
    int (*get_calls)(void) = (int (*)(void))find(m0, "mod_get_calls");
    printf("%lld\n", (long long)(enter(1)));
    printf("%lld\n", (long long)(enter(4)));
    printf("%lld\n", (long long)(enter(7)));
    printf("%lld\n", (long long)(enter(10)));
    printf("%lld\n", (long long)(enter(13)));
    printf("%lld\n", (long long)(enter(16)));
    printf("%lld\n", (long long)(exe_depth));
    printf("%lld\n", (long long)(exe_tl_acc));
    printf("%lld\n", (long long)(get_calls()));
    return 0;
}
