// Chains a planner hook onto the one before it.
// Generated by rucc-corpus. Edit the generator, not this file.

typedef long long (*planner_hook_type)(int);

extern planner_hook_type planner_hook;
long long standard_planner(int);

static planner_hook_type prev_planner_hook;
static int calls;

static long long my_planner(int q)
{
    calls++;
    long long r = prev_planner_hook ? prev_planner_hook(q) : standard_planner(q);
    return r * 3 + 11;
}

void _PG_init(void)
{
    prev_planner_hook = planner_hook;
    planner_hook = my_planner;
}

int mod_calls(void)
{
    return calls;
}
