// Defines configuration variables the executable sets.
// Generated by rucc-corpus. Edit the generator, not this file.

extern int work_mem;
void DefineCustomIntVariable(const char *, int *, int, int, int);

static int threshold;
int limit;

void _PG_init(void)
{
    DefineCustomIntVariable("mod.threshold", &threshold, 20, 0, 100);
    DefineCustomIntVariable("mod.limit", &limit, 5, 1, 50);
}

long long mod_eval(int x)
{
    return x > threshold ? (long long)x * limit + work_mem : work_mem - x;
}
