// Registers callbacks in the executable's table.
// Generated by rucc-corpus. Edit the generator, not this file.

typedef long long (*callback_fn)(long long, int);

void RegisterCallback(callback_fn, long long, int);

static long long seen;

static long long cb0(long long arg, int event)
{
    seen += event;
    return arg * 1 + event * 2;
}

static long long cb1(long long arg, int event)
{
    seen += event;
    return arg * 2 + event * 2;
}

static long long cb2(long long arg, int event)
{
    seen += event;
    return arg * 3 + event * 2;
}

static callback_fn const mine[3] = { cb0, cb1, cb2 };
static const int priorities[3] = { 1, 2, 3 };

void _PG_init(void)
{
    for (int i = 0; i < 3; i++) {
        RegisterCallback(mine[i], 10 + i, priorities[i]);
    }
}

long long mod_seen(void)
{
    return seen;
}
