// Calls back into the executable as it loads.
// Generated by rucc-corpus. Edit the generator, not this file.

extern int load_generation;
void note_init(int, int);

static int *const generation_at = &load_generation;
static void (*const report)(int, int) = note_init;
static int my_generation = -1;

__attribute__((constructor)) static void mod_init(void)
{
    my_generation = *generation_at;
    report(3, my_generation);
}

int mod_generation(void)
{
    return my_generation;
}
