// 3 modules chaining onto one planner hook
// Generated by rucc-corpus. Edit the generator, not this file.

#include <dlfcn.h>

int printf(const char *, ...);

static void *load(const char *path)
{
    void *handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!handle) {
        printf("dlopen %s: %s\n", path, dlerror());
    }
    return handle;
}

static void *find(void *handle, const char *name)
{
    void *found = dlsym(handle, name);
    if (!found) {
        printf("dlsym %s: %s\n", name, dlerror());
    }
    return found;
}

typedef long long (*planner_hook_type)(int);

planner_hook_type planner_hook;

long long standard_planner(int q)
{
    return q * 3LL + 1;
}

static long long plan(int q)
{
    return planner_hook ? planner_hook(q) : standard_planner(q);
}

static volatile int q_in = 1;

int main(void) {
    int q = q_in;
    printf("%lld\n", (long long)(plan(q)));
    void *m0 = load("./m0.so");
    if (!m0) {
        return 1;
    }
    void (*init0)(void) = (void (*)(void))find(m0, "_PG_init");
    init0();
    printf("%lld\n", (long long)(plan(q)));
    void *m1 = load("./m1.so");
    if (!m1) {
        return 1;
    }
    void (*init1)(void) = (void (*)(void))find(m1, "_PG_init");
    init1();
    printf("%lld\n", (long long)(plan(q)));
    void *m2 = load("./m2.so");
    if (!m2) {
        return 1;
    }
    void (*init2)(void) = (void (*)(void))find(m2, "_PG_init");
    init2();
    printf("%lld\n", (long long)(plan(q)));
    printf("%lld\n", (long long)(plan(1)));
    printf("%lld\n", (long long)(plan(6)));
    printf("%lld\n", (long long)(plan(9)));
    int (*calls0)(void) = (int (*)(void))find(m0, "mod_calls");
    printf("%lld\n", (long long)(calls0()));
    int (*calls1)(void) = (int (*)(void))find(m1, "mod_calls");
    printf("%lld\n", (long long)(calls1()));
    int (*calls2)(void) = (int (*)(void))find(m2, "mod_calls");
    printf("%lld\n", (long long)(calls2()));
    return 0;
}
