// One of two modules with exactly the same names in them.
// Generated by rucc-corpus. Edit the generator, not this file.

static long long state = 102;
int shared_name = 52;

static int bump(void)
{
    return ++shared_name;
}

long long step(int x)
{
    state = state * 2 + x + shared_name;
    bump();
    return state;
}

int get_shared(void)
{
    return shared_name;
}
