// A module raising 8 messages through a variadic elog
// Generated by rucc-corpus. Edit the generator, not this file.

#include <dlfcn.h>
#include <stdarg.h>

int printf(const char *, ...);

static void *load(const char *path)
{
    void *handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!handle) {
        printf("dlopen %s: %s\n", path, dlerror());
    }
    return handle;
}

static void *find(void *handle, const char *name)
{
    void *found = dlsym(handle, name);
    if (!found) {
        printf("dlsym %s: %s\n", name, dlerror());
    }
    return found;
}

static unsigned long long elog_hash = 1469598103934665603ULL;
static int elog_count;
static int elog_errors;

static void mix(unsigned long long v)
{
    elog_hash = (elog_hash ^ v) * 1099511628211ULL;
}

void elog_valist(int level, const char *fmt, va_list ap)
{
    elog_count++;
    if (level >= 21) {
        elog_errors++;
    }
    mix((unsigned long long)level);
    for (const char *p = fmt; *p; p++) {
        if (*p != '%') {
            mix((unsigned char)*p);
            continue;
        }
        p++;
        switch (*p) {
        case 'd':
            mix((unsigned long long)(long long)va_arg(ap, int));
            break;
        case 'L':
            mix((unsigned long long)va_arg(ap, long long));
            break;
        case 'u':
            mix((unsigned long long)va_arg(ap, unsigned));
            break;
        case 'f':
            mix((unsigned long long)(long long)(va_arg(ap, double) * 8.0));
            break;
        case 's':
            for (const char *s = va_arg(ap, const char *); *s; s++) {
                mix((unsigned char)*s);
            }
            break;
        case 'c':
            mix((unsigned long long)va_arg(ap, int));
            break;
        }
    }
}

void elog(int level, const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    elog_valist(level, fmt, ap);
    va_end(ap);
}

int main(void) {
    void *m0 = load("./m0.so");
    if (!m0) {
        return 1;
    }
    void (*run)(void) = (void (*)(void))find(m0, "mod_run");
    run();
    printf("%lld\n", (long long)(elog_count));
    printf("%lld\n", (long long)(elog_errors));
    printf("%llu\n", (unsigned long long)(elog_hash));
    return 0;
}
