// a widened unsigned short read whole as well as narrow
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned short a_in = 200u;
static volatile int flag_in = 1;

int main(void) {
    unsigned short a = a_in;
    int flag = flag_in;

    int wide = a;
    unsigned short low = (unsigned short)0u;
    int beyond = 0;
    if (flag) {
        low = (unsigned short)wide;
        beyond = wide > 127;
    }
    unsigned short total = (unsigned short)(low + (unsigned short)beyond);

    printf("%lld\n", (long long)(total));
    return 0;
}
