// a widened signed char whose only reader is in another block
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile signed char a_in = 40;
static volatile int flag_in = 1;

int main(void) {
    signed char a = a_in;
    int flag = flag_in;

    int wide = a;
    signed char low = (signed char)0;
    if (flag) {
        low = (signed char)wide;
    }
    signed char total = low;

    printf("%lld\n", (long long)(total));
    return 0;
}
