// a widened unsigned short widened twice and read back at its own width
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned short a_in = 40u;
static volatile int flag_in = 1;

int main(void) {
    unsigned short a = a_in;
    int flag = flag_in;

    int wide = a;
    long long wider = wide;
    unsigned short low = (unsigned short)0u;
    if (flag) {
        low = (unsigned short)wider;
    }
    unsigned short total = low;

    printf("%lld\n", (long long)(total));
    return 0;
}
