// a widened short widened twice and read back at its own width
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short a_in = 40;
static volatile int flag_in = 1;

int main(void) {
    short a = a_in;
    int flag = flag_in;

    int wide = a;
    long long wider = wide;
    short low = (short)0;
    if (flag) {
        low = (short)wider;
    }
    short total = low;

    printf("%lld\n", (long long)(total));
    return 0;
}
