// a widened unsigned char narrowed out of a double by the selector
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile double source_in = 40.75;
static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    double source = source_in;
    unsigned char total = (unsigned char)source;
    if (flag) {
        total = (unsigned char)(source + 1.0);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
