// a widened short widened in both arms and read narrow at the join
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile short a_in = 40;
static volatile short b_in = 15;
static volatile int flag_in = 1;

int main(void) {
    short a = a_in;
    short b = b_in;
    int flag = flag_in;

    int wide;
    if (flag) {
        wide = a;
    } else {
        wide = b;
    }
    short total = (short)wide;

    printf("%lld\n", (long long)(total));
    return 0;
}
