// a widened unsigned short whose only reader is in a loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned short a_in = 5u;
static volatile int count_in = 3;

int main(void) {
    unsigned short a = a_in;
    int count = count_in;

    int wide = a;
    unsigned short total = (unsigned short)0u;
    for (int i = 0; i < count; i = i + 1) {
        total = (unsigned short)(total + (unsigned short)wide);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
