// a widened signed char narrowed out of a double by the selector
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile double source_in = 40.75;
static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    double source = source_in;
    signed char total = (signed char)source;
    if (flag) {
        total = (signed char)(source + 1.0);
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
