// left, right and balanced and chains on int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a0_in = 15;
static volatile int a1_in = 51;
static volatile int a2_in = 85;
static volatile int a3_in = 170;

int main(void) {
    int a0 = a0_in;
    int a1 = a1_in;
    int a2 = a2_in;
    int a3 = a3_in;

    printf("%lld\n", (long long)((((a0 & a1) & a2) & a3)));
    printf("%lld\n", (long long)((a0 & (a1 & (a2 & a3)))));
    printf("%lld\n", (long long)(((a0 & a1) & (a2 & a3))));
    printf("%lld\n", (long long)(((a3 & a2) & (a1 & a0))));
    return 0;
}
