// left, right and balanced and chains on long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a0_in = 15ll;
static volatile long long a1_in = 51ll;
static volatile long long a2_in = 85ll;
static volatile long long a3_in = 170ll;

int main(void) {
    long long a0 = a0_in;
    long long a1 = a1_in;
    long long a2 = a2_in;
    long long a3 = a3_in;

    printf("%lld\n", (long long)((((a0 & a1) & a2) & a3)));
    printf("%lld\n", (long long)((a0 & (a1 & (a2 & a3)))));
    printf("%lld\n", (long long)(((a0 & a1) & (a2 & a3))));
    printf("%lld\n", (long long)(((a3 & a2) & (a1 & a0))));
    return 0;
}
