// left, right and balanced mul chains on long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long a0_in = 1ll;
static volatile long long a1_in = 2ll;
static volatile long long a2_in = 3ll;
static volatile long long a3_in = 5ll;

int main(void) {
    long long a0 = a0_in;
    long long a1 = a1_in;
    long long a2 = a2_in;
    long long a3 = a3_in;

    printf("%lld\n", (long long)((((a0 * a1) * a2) * a3)));
    printf("%lld\n", (long long)((a0 * (a1 * (a2 * a3)))));
    printf("%lld\n", (long long)(((a0 * a1) * (a2 * a3))));
    printf("%lld\n", (long long)(((a3 * a2) * (a1 * a0))));
    return 0;
}
