// left, right and balanced add chains on unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long a0_in = 1ull;
static volatile unsigned long long a1_in = 2ull;
static volatile unsigned long long a2_in = 3ull;
static volatile unsigned long long a3_in = 5ull;

int main(void) {
    unsigned long long a0 = a0_in;
    unsigned long long a1 = a1_in;
    unsigned long long a2 = a2_in;
    unsigned long long a3 = a3_in;

    printf("%llu\n", (unsigned long long)((((a0 + a1) + a2) + a3)));
    printf("%llu\n", (unsigned long long)((a0 + (a1 + (a2 + a3)))));
    printf("%llu\n", (unsigned long long)(((a0 + a1) + (a2 + a3))));
    printf("%llu\n", (unsigned long long)(((a3 + a2) + (a1 + a0))));
    return 0;
}
