// a static loop helper of 4 steps called from one place in a hot loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static unsigned int spin(unsigned int value) {
    unsigned int rounds = value & 7u;
    for (unsigned int round = 0; round < rounds; round++) {
        value = value * 3u + round;
    }
    value = value * 1u + 17u;
    value ^= value >> 13;
    value = value * 2654435761u + 40520u;
    value ^= value >> 13;
    value = value * 1013904227u + 81023u;
    value ^= value >> 13;
    value = value * 3668339987u + 121526u;
    value ^= value >> 13;
    return value;
}
static volatile unsigned int seed_in = 7u;

int main(void) {
    unsigned long long total = 0;
    unsigned int seed = seed_in;

    static unsigned int values[4096];
    unsigned int drawn = seed;
    for (int i = 0; i < 4096; i++) {
        drawn = drawn * 1103515245u + 12345u;
        values[i] = drawn >> 8;
    }
    for (unsigned int at = 0; at < 4194304u; at++) {
        total += spin(values[at & 4095u]);
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
