// one frame address, used at one offsets
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 5ll;

int main(void) {
    long long seed = seed_in;

    long long room[1];
    room[0] = seed;
    long long total = room[0];

    printf("%lld\n", (long long)(total));
    return 0;
}
