// one frame address, used at three offsets
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 5ll;

int main(void) {
    long long seed = seed_in;

    long long room[3];
    room[0] = seed;
    room[1] = seed + (long long)1ll;
    room[2] = seed + (long long)2ll;
    long long total = room[0] + room[1] + room[2];

    printf("%lld\n", (long long)(total));
    return 0;
}
