// a clamp on int with an unpredictable condition
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int a_in = 20;
static volatile int b_in = 12;

int main(void) {
    int a = a_in;
    int b = b_in;

    int total = 0;
    for (int i = 0; i < 1000; i++) {
        int odd = i & 1;
        int raw = odd ? a : b;
        int low = raw < (int)15 ? (int)15 : raw;
        total += low > (int)18 ? (int)18 : low;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
