// a diamond with work in both arms, taken 99 times in a hundred, with wrong hint
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned state = seed;
    unsigned long long total = 0;
    for (int i = 0; i < 20000000; i++) {
        state = state * 1103515245u + 12345u;
        unsigned x = state >> 24;
        int taken = (state >> 16) % 100u < 99u;
        unsigned v;
        if (__builtin_expect(taken, 0)) {
            v = x * 3u;
        } else {
            v = x + 7u;
        }
        total += v;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
