// an invariant test inside a 8 iteration unsigned int loop, flag 1
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    unsigned int total = 0;
    for (int i = 0; i < 8; i++) {
        if (flag) {
            total += (unsigned int)(i * 2);
        } else {
            total += (unsigned int)(i + 1);
        }
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
