// an invariant test inside a 7 iteration unsigned long long loop, flag 1
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int flag_in = 1;

int main(void) {
    int flag = flag_in;

    unsigned long long total = 0;
    for (int i = 0; i < 7; i++) {
        if (flag) {
            total += (unsigned long long)(i * 2);
        } else {
            total += (unsigned long long)(i + 1);
        }
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
