// two int references, restrict
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static int combine(int *restrict left, int *restrict right) {
    *left += 1;
    *right += 2;
    return *left + *right;
}

int main(void) {
    int seed = seed_in;

    int left = seed, right = seed;
    int total = combine(&left, &right);

    printf("%lld\n", (long long)(total));
    return 0;
}
