// two unsigned long long references, distinct-indices
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;

int main(void) {
    unsigned long long seed = seed_in;

    unsigned long long buffer[4] = { 0 };
    buffer[0] = seed + (unsigned long long)1ull;
    buffer[3] = seed + (unsigned long long)2ull;
    unsigned long long total = buffer[0] + buffer[3];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
