// escaped-local references to int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int index_in = 1;
static int *kept;
static void keep(int *of) {
    kept = of;
}
static void overwrite(void) {
    *kept = *kept + 2;
}

int main(void) {
    int seed = seed_in;
    int index = index_in;

    int local = seed;
    keep(&local);
    local = seed + (int)1;
    overwrite();
    int total = local;

    printf("%lld\n", (long long)(total));
    return 0;
}
