// char-pointer references to long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 5ll;
static volatile int index_in = 1;

int main(void) {
    long long seed = seed_in;
    int index = index_in;

    long long object = seed;
    long long *at = &object;
    unsigned char *bytes = (unsigned char *)&object;
    *at = seed + (long long)1ll;
    for (int i = 0; i < 8; i++) {
        bytes[i] = 0;
    }
    long long total = *at + (long long)7ll;

    printf("%lld\n", (long long)(total));
    return 0;
}
