// computed-same-index references to long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile long long seed_in = 5ll;
static volatile int index_in = 1;

int main(void) {
    long long seed = seed_in;
    int index = index_in;

    long long buffer[4] = { 0 };
    int here = index;
    int there = index * 3 - 2;
    buffer[here] = seed + (long long)1ll;
    buffer[there] = seed + (long long)2ll;
    long long total = buffer[here] + buffer[there];

    printf("%lld\n", (long long)(total));
    return 0;
}
