// computed-same-index references to unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int index_in = 1;

int main(void) {
    unsigned int seed = seed_in;
    int index = index_in;

    unsigned int buffer[4] = { 0 };
    int here = index;
    int there = index * 3 - 2;
    buffer[here] = seed + (unsigned int)1u;
    buffer[there] = seed + (unsigned int)2u;
    unsigned int total = buffer[here] + buffer[there];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
