// two unsigned int references, restrict
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static unsigned int combine(unsigned int *restrict left, unsigned int *restrict right) {
    *left += 1;
    *right += 2;
    return *left + *right;
}

int main(void) {
    unsigned int seed = seed_in;

    unsigned int left = seed, right = seed;
    unsigned int total = combine(&left, &right);

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
