// union-pun references to unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;
static volatile int index_in = 1;
union both { unsigned int whole; unsigned char parts[4]; };

int main(void) {
    unsigned int seed = seed_in;
    int index = index_in;

    union both holder;
    holder.whole = seed + (unsigned int)1u;
    for (int i = 0; i < 4; i++) {
        holder.parts[i] = 0;
    }
    unsigned int total = holder.whole + (unsigned int)7u;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
