// two unsigned int references, distinct-locals
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 5u;

int main(void) {
    unsigned int seed = seed_in;

    unsigned int left = seed;
    unsigned int right = seed;
    unsigned int *pl = &left, *pr = &right;
    *pl = seed + (unsigned int)1u;
    *pr = seed + (unsigned int)2u;
    unsigned int total = *pl + *pr;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
