// char-pointer references to int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int index_in = 1;

int main(void) {
    int seed = seed_in;
    int index = index_in;

    int object = seed;
    int *at = &object;
    unsigned char *bytes = (unsigned char *)&object;
    *at = seed + (int)1;
    for (int i = 0; i < 4; i++) {
        bytes[i] = 0;
    }
    int total = *at + (int)7;

    printf("%lld\n", (long long)(total));
    return 0;
}
