// computed-same-index references to unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int index_in = 1;

int main(void) {
    unsigned long long seed = seed_in;
    int index = index_in;

    unsigned long long buffer[4] = { 0 };
    int here = index;
    int there = index * 3 - 2;
    buffer[here] = seed + (unsigned long long)1ull;
    buffer[there] = seed + (unsigned long long)2ull;
    unsigned long long total = buffer[here] + buffer[there];

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
