// distinct-types references to int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int index_in = 1;

int main(void) {
    int seed = seed_in;
    int index = index_in;

    int left = seed;
    short right = 1;
    int *pl = &left;
    short *pr = &right;
    *pl = seed + (int)1;
    *pr = 2;
    int total = *pl + (int)*pr;

    printf("%lld\n", (long long)(total));
    return 0;
}
