// distinct-types references to unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned long long seed_in = 5ull;
static volatile int index_in = 1;

int main(void) {
    unsigned long long seed = seed_in;
    int index = index_in;

    unsigned long long left = seed;
    short right = 1;
    unsigned long long *pl = &left;
    short *pr = &right;
    *pl = seed + (unsigned long long)1ull;
    *pr = 2;
    unsigned long long total = *pl + (unsigned long long)*pr;

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
