// computed-same-index references to int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 5;
static volatile int index_in = 1;

int main(void) {
    int seed = seed_in;
    int index = index_in;

    int buffer[4] = { 0 };
    int here = index;
    int there = index * 3 - 2;
    buffer[here] = seed + (int)1;
    buffer[there] = seed + (int)2;
    int total = buffer[here] + buffer[there];

    printf("%lld\n", (long long)(total));
    return 0;
}
