// a do while, which is already the rotated shape, int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    int total = 0;
    int i = 0;
    do {
        total += (int)i;
        i++;
    } while (i < 6);

    printf("%lld\n", (long long)(total));
    return 0;
}
