// counting up to a bound the loop does reach, unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned long long total = 0;
    for (int i = 0; i <= 7; i++) {
        total += (unsigned long long)i;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
