// a loop that never runs at all, unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned long long total = 99;
    for (int i = 0; i < 0; i++) {
        total += (unsigned long long)1;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
