// a loop with a continue in it, unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned int total = 0;
    for (int i = 0; i < 6; i++) {
        if (i & 1) {
            continue;
        }
        total += (unsigned int)i;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
