// a loop that ends on != rather than <, int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    int total = 0;
    for (int i = 0; i != 8; i += 2) {
        total += (int)i;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
