// a step that overshoots the bound, unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned long long total = 0;
    for (int i = 0; i < 10; i += 3) {
        total += (unsigned long long)i;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
