// a nest whose inner bound is not known, long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int inner_in = 4;

int main(void) {
    int inner = inner_in;

    long long total = 0;
    for (int x = 0; x < 3; x++) {
        for (int y = 0; y < inner; y++) {
            total += (long long)y;
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
