// a loop that runs exactly once, long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    long long total = 0;
    for (int i = 0; i < 1; i++) {
        total += (long long)5;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
