// a loop that never runs at all, int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    int total = 99;
    for (int i = 0; i < 0; i++) {
        total += (int)1;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
