// a loop counted by an unsigned variable, unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned long long total = 0;
    for (unsigned i = 0u; i < 9u; i++) {
        total += (unsigned long long)i;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
