// counting down through zero, unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned int total = 0;
    for (int i = 6; i >= 0; i--) {
        total += (unsigned int)i;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
