// a loop counted by an unsigned variable, long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    long long total = 0;
    for (unsigned i = 0u; i < 9u; i++) {
        total += (long long)i;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
