// a nest whose loops both have a known count, long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    long long total = 0;
    for (int x = 0; x < 4; x++) {
        for (int y = 0; y < 3; y++) {
            total += (long long)(x * y);
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
