// filling an array through a pointer, unsigned long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    int room[6];
    int *at = room;
    for (int i = 0; i < 6; i++) {
        at[i] = i * 3;
    }
    unsigned long long total = 0;
    for (int i = 0; i < 6; i++) {
        total += (unsigned long long)room[i];
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
