// a loop counted by an unsigned char, long long
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    long long total = 0;
    for (unsigned char i = 0; i < 200; i++) {
        total += (long long)1;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
