// a loop with a break in it, int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int stop_in = 4;

int main(void) {
    int stop = stop_in;

    int total = 0;
    for (int i = 0; i < 6; i++) {
        if (i == stop) {
            break;
        }
        total += (int)i;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
