// a counter that outlives its loop, unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned int total = 0;
    int last = -1;
    for (int i = 0; i < 5; i++) {
        total += (unsigned int)i;
        last = i;
    }

    printf("%lld\n", (long long)(last));

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
