// a loop that never runs at all, unsigned int
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

int main(void) {

    unsigned int total = 99;
    for (int i = 0; i < 0; i++) {
        total += (unsigned int)1;
    }

    printf("%llu\n", (unsigned long long)(total));
    return 0;
}
