// a hot-then branch in a hot loop, with the builtin hint on it
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int oops_count;
static void oops(void) {
    oops_count = oops_count + 1;
}
static void (*volatile cold)(void) = oops;
static volatile int rare_in = 0;

int main(void) {
    int rare = rare_in;

    long long total = 0;
    for (int i = 0; i < 1000; i++) {
        if (__builtin_expect(rare == 0, 1)) {
            total += 1;
        } else {
            cold();
        }
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
