// a early-exit branch inside a hot loop
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int rare_in = 0;

int main(void) {
    int rare = rare_in;

    long long total = 0;
    for (int i = 0; i < 1000; i++) {
        if (rare) {
            break;
        }
        total += 1;
    }

    printf("%lld\n", (long long)(total));
    return 0;
}
