// static-key-on after arch/x86/include/asm/jump_label.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

static inline __attribute__((always_inline)) int key_enabled(void) {
    asm goto("jmp %l[yes]" : : : : yes);
    return 0;
yes:
    return 1;
}

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    if (key_enabled()) {
        return (x ^ i) * 5u + 1u;
    }
    return x + i * 7u;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
