// param-table after include/linux/moduleparam.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

struct kernel_param {
    const char *name;
    unsigned int key;
    unsigned int (*set)(unsigned int, unsigned int);
};

#define __module_param_call(name, key, set) \
    static const struct kernel_param __param_##name \
        __attribute__((used, section("rk_param"), \
                       aligned(__alignof__(struct kernel_param)))) \
        = { #name, key, set }

extern const struct kernel_param __start_rk_param[];
extern const struct kernel_param __stop_rk_param[];

static unsigned int set_add(unsigned int x, unsigned int i) {
    return x + i * 3u;
}

static unsigned int set_xor(unsigned int x, unsigned int i) {
    return x ^ (i << 7);
}

static unsigned int set_mul(unsigned int x, unsigned int i) {
    return x * 5u + i;
}

__module_param_call(debug, 1u, set_add);
__module_param_call(quiet, 3u, set_xor);
__module_param_call(loglevel, 4u, set_mul);
__module_param_call(panic, 6u, set_add);

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    unsigned int key = (x ^ i) & 7u;
    unsigned int count = 0;
    for (const struct kernel_param *p = __start_rk_param; p < __stop_rk_param; p++) {
        count++;
        if (p->key == key) {
            x = p->set(x, i) + (unsigned char)p->name[0];
        }
    }
    return x + count * i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
