// aligned-entries after include/linux/serial_core.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

struct earlycon_id {
    char name[16];
    char compatible[16];
    unsigned int flags;
};

#define EARLYCON_DECLARE(_name, _flags) \
    static const struct earlycon_id __earlycon_##_name \
        __attribute__((used, section("rk_earlycon"), \
                       aligned(__alignof__(struct earlycon_id)))) \
        = { .name = #_name, .compatible = "rk," #_name, .flags = _flags }

extern const struct earlycon_id __start_rk_earlycon[];
extern const struct earlycon_id __stop_rk_earlycon[];

EARLYCON_DECLARE(uart8250, 1u);
EARLYCON_DECLARE(pl011, 2u);
EARLYCON_DECLARE(ns16550, 4u);

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    unsigned int h = 0, count = 0;
    for (const struct earlycon_id *e = __start_rk_earlycon; e < __stop_rk_earlycon; e++) {
        h += e->flags * (unsigned char)e->name[1] + (unsigned char)e->compatible[3];
        count++;
    }
    return (x ^ h) + count * (i + 1u);
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
