// initcall-table after include/linux/init.h in Linux 7.2
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile unsigned int seed_in = 7;

typedef unsigned int (*initcall_t)(unsigned int);

#define __define_initcall(fn, id) \
    static initcall_t __initcall_##fn##id \
        __attribute__((used, section("rk_initcall"))) = fn
#define device_initcall(fn) __define_initcall(fn, 6)

extern initcall_t __start_rk_initcall[];
extern initcall_t __stop_rk_initcall[];

static unsigned int init_clock(unsigned int x) {
    return x * 3u + 1u;
}

static unsigned int init_irq(unsigned int x) {
    return x ^ 0x5bd1e995u;
}

static unsigned int init_mm(unsigned int x) {
    return (x << 5) | (x >> 27);
}

static unsigned int init_net(unsigned int x) {
    return x + 0x9e3779b9u;
}

device_initcall(init_clock);
device_initcall(init_irq);
device_initcall(init_mm);
device_initcall(init_net);

__attribute__((noinline))
static unsigned int step(unsigned int x, unsigned int i) {
    unsigned int sum = 0, count = 0;
    for (initcall_t *fn = __start_rk_initcall; fn < __stop_rk_initcall; fn++) {
        sum += (*fn)(x + i);
        count++;
    }
    return (x ^ sum) + count * i;
}

int main(void) {
    unsigned int acc = seed_in;
    for (unsigned int i = 0; i < 64u; i++) {
        acc = step(acc, i);
    }

    printf("%llu\n", (unsigned long long)(acc));
    return 0;
}
