// a volatile-compare the compiler must not optimize away
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int want_in = 7;
static volatile int status = 7;

int main(void) {
    int want = want_in;

    int tally = 0;
    if (status == 7) tally += 1;
    status = want + 1;
    if (status == 7) tally += 10;
    if (status == want + 1) tally += 100;

    printf("%lld\n", (long long)(tally));
    return 0;
}
