// a char-aliasing the compiler must not optimize away
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int seed_in = 0;

int main(void) {
    int seed = seed_in;

    int value = seed;
    unsigned char *bytes = (unsigned char *)&value;
    bytes[0] = 1;

    printf("%lld\n", (long long)(bytes[0]));
    printf("%lld\n", (long long)(value != 0));
    return 0;
}
