// a volatile-widths the compiler must not optimize away
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile signed char narrow = 3;
static volatile short half = 300;
static volatile int whole = 70000;
static volatile long long wide = 5000000000ll;

int main(void) {

    narrow += 1;
    half += 1;
    whole += 1;
    wide += 1;

    printf("%lld\n", (long long)(narrow));
    printf("%lld\n", (long long)(half));
    printf("%lld\n", (long long)(whole));
    printf("%lld\n", (long long)(wide));
    return 0;
}
