// a volatile-order the compiler must not optimize away
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int port = 0;
static int trace[4];

int main(void) {

    port = 1;
    trace[0] = port;
    port = 2;
    trace[1] = port;
    port = 3;
    trace[2] = port;

    printf("%lld\n", (long long)(trace[0] + trace[1] * 10 + trace[2] * 100));
    return 0;
}
