// a volatile-in-loop the compiler must not optimize away
// Generated by rucc-corpus. Edit the generator, not this file.

int printf(const char *, ...);

static volatile int counter = 0;

int main(void) {

    for (int i = 0; i < 100; i++) {
        counter = counter + 1;
    }

    printf("%lld\n", (long long)(counter));
    return 0;
}
